import type { StrategyRecord } from './contracts';

export type PolicyAudience = StrategyRecord & {
  configuration: Record<string, unknown> & { systemKey: string; origin: 'SYSTEM_POLICY' };
};

/**
 * System audience personas for Stage 01.
 * Qualitative fit only — no fabricated engagement or conversion metrics.
 */
export const AUDIENCES_POLICY: PolicyAudience[] = [
  {
    name: 'Learners · Primary',
    description:
      'Primary audience seeking clear, evidence-led educational media they can revisit and share.',
    status: 'ACTIVE',
    priority: 95,
    configuration: {
      systemKey: 'aud.learners.primary',
      origin: 'SYSTEM_POLICY',
      audienceTier: 'primary',
      ageRange: '14–35 (core); adjacent ages when story-fit',
      knowledgeLevel: 'Introductory to intermediate',
      interestGroup: 'Learners',
      countryRegion: 'Priority operating regions + diaspora',
      languages: 'English primary; local languages when localisation active',
      accessibilityNeeds: 'Captions preferred; plain-language summaries',
      informationNeeds: 'What / why / how explained with concrete examples',
      questions: 'Is this accurate? Can I use this for study or teaching?',
      preferredTone: 'Clear, respectful, non-patronising',
      formats: 'Short-form video, explainer, lesson segment',
      duration: '2–12 minutes typical',
      channels: 'Owned platforms, classroom distribution, social cut-downs',
      deviceBandwidth: 'Mobile-first; resilient to mid bandwidth',
      viewingBehaviour: 'Skim then rewatch key beats',
      engagementObjectives: 'Comprehension and voluntary revisit — UNMEASURED numerically',
      sensitivityTolerance: 'STANDARD',
      learningOutcomes: 'Can restate the core claim and cite the evidence trail',
      successMetrics: 'UNMEASURED — qualitative comprehension fit only',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Educators · Primary',
    description:
      'Primary audience of teachers and facilitators who need classroom-safe, citable materials.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'aud.educators.primary',
      origin: 'SYSTEM_POLICY',
      audienceTier: 'primary',
      ageRange: 'Adult professionals',
      knowledgeLevel: 'Intermediate to advanced pedagogical framing',
      interestGroup: 'Educators',
      countryRegion: 'Priority operating regions',
      languages: 'English; local instructional languages when available',
      accessibilityNeeds: 'Transcripts, chapter markers, downloadable stills',
      informationNeeds: 'Curriculum fit, source quality, discussion prompts',
      questions: 'Is this classroom-safe? What should learners do next?',
      preferredTone: 'Professional, precise, supportive',
      formats: 'Explainer, lesson segment, documentary clip',
      duration: '5–15 minutes segments',
      channels: 'LMS, school networks, educator communities',
      deviceBandwidth: 'Classroom projection and mobile review',
      viewingBehaviour: 'Preview fully before assigning',
      engagementObjectives: 'Adoption for instruction — UNMEASURED numerically',
      sensitivityTolerance: 'ELEVATED for minors in class contexts',
      learningOutcomes: 'Can scaffold a short lesson around the piece',
      successMetrics: 'UNMEASURED — qualitative instructional fit only',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'General public · Secondary',
    description:
      'Secondary broad audience for civic and cultural literacy without specialist prerequisites.',
    status: 'ACTIVE',
    priority: 80,
    configuration: {
      systemKey: 'aud.general-public.secondary',
      origin: 'SYSTEM_POLICY',
      audienceTier: 'secondary',
      ageRange: '16+',
      knowledgeLevel: 'General interest',
      interestGroup: 'General public',
      countryRegion: 'Configured geographies',
      languages: 'English primary',
      accessibilityNeeds: 'Captions; avoid unexplained jargon',
      informationNeeds: 'Why this matters now; trustworthy framing',
      questions: 'Is this fair? Why should I care?',
      preferredTone: 'Inviting, neutral, non-sensational',
      formats: 'Short-form video, explainer, featurette',
      duration: '1–8 minutes',
      channels: 'Social, broadcast cut-downs, owned web',
      deviceBandwidth: 'Mobile-first',
      viewingBehaviour: 'Interruptible; needs strong open',
      engagementObjectives: 'Informed attention — UNMEASURED numerically',
      sensitivityTolerance: 'STANDARD',
      learningOutcomes: 'Can summarise the civic or cultural takeaway',
      successMetrics: 'UNMEASURED',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Regional audiences · Secondary',
    description:
      'Secondary audience anchored to configured geographies and local cultural relevance.',
    status: 'ACTIVE',
    priority: 76,
    configuration: {
      systemKey: 'aud.regional.secondary',
      origin: 'SYSTEM_POLICY',
      audienceTier: 'secondary',
      ageRange: '14+',
      knowledgeLevel: 'Locally informed to intermediate',
      interestGroup: 'Regional audiences',
      countryRegion: 'Configured geographies (e.g. Nigeria, West Africa)',
      languages: 'English + relevant local languages',
      accessibilityNeeds: 'Local language captions when available',
      informationNeeds: 'Local accuracy, recognisable places, fair portrayal',
      questions: 'Does this look like our place? Who is speaking for us?',
      preferredTone: 'Respectful, locally fluent',
      formats: 'Documentary segment, short-form, featurette',
      duration: '2–12 minutes',
      channels: 'Local platforms, community distribution, social',
      deviceBandwidth: 'Mobile-first; variable connectivity',
      viewingBehaviour: 'Share within community networks',
      engagementObjectives: 'Local trust and relevance — UNMEASURED numerically',
      sensitivityTolerance: 'ELEVATED for cultural and ethnic depiction',
      learningOutcomes: 'Recognises authentic local framing',
      successMetrics: 'UNMEASURED',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Clinical advice seekers · Excluded',
    description:
      'Excluded audience intent: people seeking personal medical diagnosis or treatment advice.',
    status: 'ACTIVE',
    priority: 40,
    configuration: {
      systemKey: 'aud.clinical-advice.excluded',
      origin: 'SYSTEM_POLICY',
      audienceTier: 'excluded',
      ageRange: 'Any',
      knowledgeLevel: 'Any',
      interestGroup: 'Clinical advice seekers',
      countryRegion: 'All',
      languages: 'Any',
      accessibilityNeeds: 'N/A — content must not target this intent',
      informationNeeds: 'Personal medical decisions (out of scope)',
      questions: 'What should I take? What is my diagnosis?',
      preferredTone: 'N/A',
      formats: 'None for clinical advice',
      duration: 'N/A',
      channels: 'N/A',
      deviceBandwidth: 'N/A',
      viewingBehaviour: 'N/A',
      engagementObjectives: 'Must not be served clinical advice content',
      sensitivityTolerance: 'CRITICAL',
      learningOutcomes: 'Redirect to qualified clinicians / official guidance only',
      successMetrics: 'UNMEASURED — exclusion compliance only',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
