import type { StrategyRecord } from './contracts';

export type PolicyChannel = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    lane: 'owned' | 'social' | 'education' | 'partner' | 'internal';
  };
};

/**
 * System channel strategy for Stage 01.
 * Separates strategic enablement from provider availability — no fabricated reach metrics.
 */
export const CHANNELS_POLICY: PolicyChannel[] = [
  {
    name: 'Owned long-form library',
    description: 'Primary owned destination for explainers, lessons, and documentary segments.',
    status: 'ACTIVE',
    priority: 96,
    configuration: {
      systemKey: 'ch.owned-library',
      origin: 'SYSTEM_POLICY',
      lane: 'owned',
      channel: 'Owned long-form library',
      enabled: 'ENABLED',
      objective: 'Host durable educational catalogue with full metadata and captions',
      audiences: 'Learners, educators, general public',
      formats: 'Explainer, lesson segment, documentary segment, featurette',
      aspectRatios: '16:9 primary',
      durationLimits: '2m–20m per unit; series allowed',
      resolutionCodec: '1080p H.264/H.265; archive master retained',
      metadataRequirements: 'Title, description, taxonomy tags, sources, language, accessibility flags',
      thumbnailRequirements: 'Subject-led still; no clickbait faces; brand secondary',
      captionRequirements: 'Full captions required before publish',
      cadence: 'Steady publish when Stage 01–10 complete quality gates',
      publishingWindows: 'Any WAT business day; avoid election blackout windows when flagged',
      geographicTargeting: 'Nigeria primary; West Africa secondary; unrestricted elsewhere unless geo policy restricts',
      restrictions: 'No electioneering; restricted clinical content stays unpublished',
      providerAvailability: 'Owned platform path; provider optional for CDN only',
      automationPermissions: 'Auto-publish after quality pass; human escalate on risk flags',
      successMetrics: 'UNMEASURED until analytics stage; track publish readiness only',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Short-form social feed',
    description: 'Strategic enablement for short-form cutdowns — gated by provider readiness.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'ch.short-form-social',
      origin: 'SYSTEM_POLICY',
      lane: 'social',
      channel: 'Short-form social feed',
      enabled: 'ENABLED',
      objective: 'Surface one-takeaway clips that point back to owned library',
      audiences: 'Primary learners and secondary general public',
      formats: 'Short-form video; explainer cutdowns',
      aspectRatios: '9:16 primary; 1:1 approved',
      durationLimits: '30s–90s',
      resolutionCodec: 'Platform-native vertical encode',
      metadataRequirements: 'Hook title, source link, disclosure tags, language',
      thumbnailRequirements: 'First-frame readable title card preferred',
      captionRequirements: 'Burn-in or open captions; silent-autoplay safe',
      cadence: 'High when Running; never outpace evidence/quality gates',
      publishingWindows: 'Peak learner windows WAT; suppress during emergency stop',
      geographicTargeting: 'Follow geography policy; no fabricated geo-performance targeting',
      restrictions: 'No prohibited content; AI disclosure when material',
      providerAvailability: 'Depends on configured social provider; UNMEASURED if provider offline',
      automationPermissions: 'Queue for publish; block if provider unavailable or risk flag',
      successMetrics: 'UNMEASURED reach; operational metric is queue→publish success',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Classroom / LMS pack',
    description: 'Education-channel enablement for lesson segments with teacher-facing metadata.',
    status: 'ACTIVE',
    priority: 90,
    configuration: {
      systemKey: 'ch.classroom-lms',
      origin: 'SYSTEM_POLICY',
      lane: 'education',
      channel: 'Classroom / LMS pack',
      enabled: 'ENABLED',
      objective: 'Deliver classroom-ready units with outcomes and captions',
      audiences: 'Primary educators and learners',
      formats: 'Lesson segment; explainer',
      aspectRatios: '16:9; 4:3 crop allowed',
      durationLimits: '3m–12m',
      resolutionCodec: '1080p progressive; downloadable pack optional',
      metadataRequirements: 'Learning outcome, reading level, taxonomy, teacher notes link',
      thumbnailRequirements: 'Neutral instructional still; no sensational framing',
      captionRequirements: 'Full captions; glossary terms marked',
      cadence: 'Curriculum-aligned batches, not viral spikes',
      publishingWindows: 'School-term friendly WAT windows preferred',
      geographicTargeting: 'Nigeria classroom contexts first; localisation policy applies',
      restrictions: 'Age-appropriate only; no restricted clinical advice',
      providerAvailability: 'LMS/export provider optional; owned pack always required',
      automationPermissions: 'Auto-package after quality; teacher publish may require export step',
      successMetrics: 'UNMEASURED adoption; track pack completeness',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Partner education platforms',
    description: 'Partner distribution enabled strategically; actual delivery waits on provider contracts.',
    status: 'ACTIVE',
    priority: 84,
    configuration: {
      systemKey: 'ch.partner-education',
      origin: 'SYSTEM_POLICY',
      lane: 'partner',
      channel: 'Partner education platforms',
      enabled: 'STAGED',
      objective: 'Extend reach via partners without surrendering editorial control',
      audiences: 'Secondary educators and institutional learners',
      formats: 'Explainer, documentary segment, featurette',
      aspectRatios: '16:9',
      durationLimits: 'Per partner spec within format policy',
      resolutionCodec: 'Partner delivery profile when available',
      metadataRequirements: 'Partner schema mapping; retain source citations',
      thumbnailRequirements: 'Partner-safe stills; brand rules still apply',
      captionRequirements: 'Captions mandatory; language per localisation policy',
      cadence: 'Selective; portfolio-gated',
      publishingWindows: 'Partner windows only when enablement=STAGED→ENABLED and provider ready',
      geographicTargeting: 'Partner territories subject to geography restrictions',
      restrictions: 'No exclusive rights that block owned library; no fabricated endorsements',
      providerAvailability: 'UNAVAILABLE until partner connector healthy',
      automationPermissions: 'No auto-publish while STAGED; require provider health check',
      successMetrics: 'UNMEASURED partner views; track handoff success only',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Internal review staging',
    description: 'Non-public channel for risk review and correction previews.',
    status: 'ACTIVE',
    priority: 80,
    configuration: {
      systemKey: 'ch.internal-review',
      origin: 'SYSTEM_POLICY',
      lane: 'internal',
      channel: 'Internal review staging',
      enabled: 'ENABLED',
      objective: 'Hold restricted or high-sensitivity packages for editorial/risk review',
      audiences: 'Internal editors and compliance reviewers only',
      formats: 'All formats pending review',
      aspectRatios: 'Source format preserved',
      durationLimits: 'N/A — staging',
      resolutionCodec: 'Working copy acceptable',
      metadataRequirements: 'Risk flags, reviewer notes, source trail, disclosure state',
      thumbnailRequirements: 'Internal placeholder allowed',
      captionRequirements: 'Draft captions acceptable pre-publish',
      cadence: 'Continuous while Running',
      publishingWindows: 'Internal only; never public auto-route',
      geographicTargeting: 'N/A',
      restrictions: 'Must not fan-out to public channels without clearance',
      providerAvailability: 'Internal storage always; external providers blocked',
      automationPermissions: 'Auto-ingest for review; never auto-public-publish',
      successMetrics: 'Time-in-review operational only; no public KPIs',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
