import type { StrategyRecord } from './contracts';

export type PolicyEditorial = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    chapter: string;
  };
};

/**
 * System editorial & brand charter for Stage 01.
 * Normative rules only — no fabricated compliance scores.
 */
export const EDITORIAL_POLICY: PolicyEditorial[] = [
  {
    name: 'I. Brand purpose & editorial mission',
    description: 'Why CACSMS produces educational media and what mission constraints apply.',
    status: 'ACTIVE',
    priority: 100,
    configuration: {
      systemKey: 'ed.brand-mission',
      origin: 'SYSTEM_POLICY',
      chapter: 'mission',
      brandPurpose:
        'Produce evidence-led educational and documentary media that improves public understanding without inventing authority.',
      editorialMission:
        'Advance learning outcomes through accurate framing, clear sourcing, and culturally responsible storytelling.',
      voiceAndTone: 'Clear, respectful, non-sensational; never patronising',
      documentaryStyle: 'Observational and explanatory; dramatisation only when labelled',
      narrativePrinciples: 'Claim → evidence → implication; no unsupported leaps',
      factualityRules: 'Material claims require attributable sources before publication',
      neutrality: 'Fair presentation of contested civic topics; no covert advocacy',
      representationStandards: 'Avoid stereotypes; depict communities with specificity',
      culturalSensitivity: 'Defer to geography and localisation policy for place-bound content',
      prohibitedContent: 'Hate, sexual exploitation, graphic cruelty for shock',
      restrictedContent: 'Clinical advice, unverified atrocity claims, electioneering',
      disclosures: 'Conflicts of interest and sponsorship must be disclosed',
      aiDisclosure: 'AI-assisted generation and editing must be disclosed when material',
      quotationRules: 'Quotes must be accurate; paraphrase must not invent meaning',
      correctionPolicy: 'Substantive errors corrected promptly with visible notice',
      citationStandards: 'Prefer primary or institutionally authoritative sources',
      brandingRules: 'CACSMS marks must not overpower educational subject matter',
      reviewRequirements: 'High-sensitivity topics require elevated editorial review before release',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'II. Voice, tone & documentary style',
    description: 'How the product should sound and look in narration and framing.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'ed.voice-style',
      origin: 'SYSTEM_POLICY',
      chapter: 'voice',
      brandPurpose: 'Serve learners and educators with trustworthy media',
      editorialMission: 'Prefer clarity over spectacle',
      voiceAndTone: 'Measured, accessible, confident without swagger',
      documentaryStyle: 'Explanatory documentary and short-form education',
      narrativePrinciples: 'Open with the question; close with the verified takeaway',
      factualityRules: 'Do not present speculation as established fact',
      neutrality: 'Separate description from evaluation',
      representationStandards: 'Diverse subjects without tokenism',
      culturalSensitivity: 'Local honorifics and place names when relevant',
      prohibitedContent: 'Mockery of protected characteristics',
      restrictedContent: 'Satire that could be mistaken for factual reportage',
      disclosures: 'Sponsored segments must be labelled at open',
      aiDisclosure: 'Disclose synthetic voice or likeness when used',
      quotationRules: 'Attribute spoken claims to named speakers when known',
      correctionPolicy: 'Tone errors that change meaning are treated as substantive',
      citationStandards: 'On-screen or companion citations for contested claims',
      brandingRules: 'Lower-third branding must remain secondary to content',
      reviewRequirements: 'Style deviations from charter require editor approval',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'III. Factuality, neutrality & citation',
    description: 'Evidence and fairness gates for claims entering production.',
    status: 'ACTIVE',
    priority: 96,
    configuration: {
      systemKey: 'ed.factuality',
      origin: 'SYSTEM_POLICY',
      chapter: 'factuality',
      brandPurpose: 'Protect audience trust through verifiable claims',
      editorialMission: 'Fail closed when evidence is insufficient',
      voiceAndTone: 'Precise language; hedge uncertainty honestly',
      documentaryStyle: 'Evidence-first exposition',
      narrativePrinciples: 'No composite quotes; no invented statistics',
      factualityRules:
        'Material factual claims need attributable sources; UNMEASURED metrics must remain labelled UNMEASURED',
      neutrality: 'Present material disagreements when they are part of the story',
      representationStandards: 'Do not erase minority scholarly views when relevant',
      culturalSensitivity: 'Local knowledge claims need local authoritative sources',
      prohibitedContent: 'Fabricated data, deepfake evidence presented as real',
      restrictedContent: 'Anonymous primary allegations without corroboration',
      disclosures: 'Funding that could bias topic selection must be disclosed',
      aiDisclosure: 'Model-generated factual assertions require human verification',
      quotationRules: 'Ellipses must not change meaning; translations noted',
      correctionPolicy: 'Factual corrections are logged and surfaced to downstream stages',
      citationStandards: 'Prefer peer-reviewed, official, or primary documentary sources',
      brandingRules: 'Brand claims about impact must not invent measured outcomes',
      reviewRequirements: 'High-impact factual packages require dual review',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'IV. Representation & cultural sensitivity',
    description: 'How people, places, and cultures may be depicted.',
    status: 'ACTIVE',
    priority: 90,
    configuration: {
      systemKey: 'ed.representation',
      origin: 'SYSTEM_POLICY',
      chapter: 'representation',
      brandPurpose: 'Portray communities with dignity and specificity',
      editorialMission: 'Align with geography and audience authenticity policies',
      voiceAndTone: 'Respectful; avoid exoticising language',
      documentaryStyle: 'Contextualise cultural practices; avoid spectacle',
      narrativePrinciples: 'Subjects are agents, not props',
      factualityRules: 'Cultural claims require culturally authoritative sources',
      neutrality: 'Do not moralise unfamiliar practices without evidence',
      representationStandards:
        'No racial, ethnic, gender, or disability stereotypes; show internal diversity',
      culturalSensitivity: 'Sacred and ceremonial content needs elevated care',
      prohibitedContent: 'Blackface, cultural mockery, sexualised minors',
      restrictedContent: 'Trauma imagery; conflict zones without context',
      disclosures: 'Re-enactments and composites must be labelled',
      aiDisclosure: 'Synthetic faces of real cultural groups require disclosure and review',
      quotationRules: 'Translate faithfully; retain culturally meaningful terms',
      correctionPolicy: 'Harmful representation errors are priority corrections',
      citationStandards: 'Community or institutional cultural authorities preferred',
      brandingRules: 'Do not use sacred symbols as decorative brand marks',
      reviewRequirements: 'Elevated sensitivity content requires specialist review',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'V. Prohibitions, restrictions & risk gates',
    description: 'Hard stops and conditional content that must fail closed.',
    status: 'ACTIVE',
    priority: 98,
    configuration: {
      systemKey: 'ed.prohibitions',
      origin: 'SYSTEM_POLICY',
      chapter: 'prohibitions',
      brandPurpose: 'Keep production within lawful and ethical bounds',
      editorialMission: 'Prefer omission over unsafe publication',
      voiceAndTone: 'Do not soften hard prohibitions with humour',
      documentaryStyle: 'No gore-for-engagement packaging',
      narrativePrinciples: 'Risk assessment precedes creative flourish',
      factualityRules: 'Safety claims require authoritative basis',
      neutrality: 'Neutrality never excuses prohibited content',
      representationStandards: 'Do not platform extremist recruitment aesthetics',
      culturalSensitivity: 'Respect legal and cultural bans on depiction',
      prohibitedContent:
        'Child sexual content, non-consensual intimate imagery, actionable violence instruction, hate incitement',
      restrictedContent:
        'Self-harm detail, clinical diagnosis advice, unverified atrocity attribution, live electioneering',
      disclosures: 'Restricted topics that proceed must carry context and source trail',
      aiDisclosure: 'Models must not be used to generate prohibited content',
      quotationRules: 'Do not quote actionable harm instructions',
      correctionPolicy: 'Prohibition breaches trigger emergency stop review',
      citationStandards: 'Official safety guidance when publishing restricted public-health literacy',
      brandingRules: 'Brand must not appear to endorse prohibited acts',
      reviewRequirements: 'Restricted content cannot ship without risk review sign-off',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'VI. Disclosure, corrections & branding discipline',
    description: 'Transparency, remediation, and brand presentation rules.',
    status: 'ACTIVE',
    priority: 88,
    configuration: {
      systemKey: 'ed.disclosure-brand',
      origin: 'SYSTEM_POLICY',
      chapter: 'disclosure',
      brandPurpose: 'Maintain transparent relationship with audiences',
      editorialMission: 'Correct fast; disclose material process choices',
      voiceAndTone: 'Corrections are plain and specific',
      documentaryStyle: 'Process labels (re-enactment, AI assist) appear near first use',
      narrativePrinciples: 'Do not bury disclosures in end cards only',
      factualityRules: 'Corrected claims replace prior erroneous claims in distribution',
      neutrality: 'Corrections must not be used for score-settling',
      representationStandards: 'Apology language must not re-harm subjects',
      culturalSensitivity: 'Local disclosure norms may require additional notice',
      prohibitedContent: 'Astroturf testimonials',
      restrictedContent: 'Native advertising without label',
      disclosures: 'Sponsorship, partnerships, and material AI assistance',
      aiDisclosure: 'Required when AI materially shapes script, image, or voice',
      quotationRules: 'Corrected quotes supersede prior versions',
      correctionPolicy: 'Log correction, notify dependent stages, retain audit trail',
      citationStandards: 'Cite the corrected source of record',
      brandingRules: 'Logo and wordmark secondary to educational content; no false authority seals',
      reviewRequirements: 'Brand campaign crossovers need editorial+brand dual approval',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
