import type { StrategyRecord } from './contracts';

export type PolicyFormat = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    family: string;
    durationMinSec: number;
    durationMaxSec: number;
  };
};

/**
 * Format production briefs plotted on a duration timeline.
 * Unique constraints per format — less boilerplate duplication.
 */
export const FORMATS_POLICY: PolicyFormat[] = [
  {
    name: 'Short-form video',
    description: 'Hook-led clips for mobile silent autoplay.',
    status: 'ACTIVE',
    priority: 96,
    configuration: {
      systemKey: 'fmt.short-form',
      origin: 'SYSTEM_POLICY',
      family: 'short_form',
      durationMinSec: 30,
      durationMaxSec: 90,
      format: 'Short-form video',
      purpose: 'One learning takeaway + soft CTA to owned library',
      minimumDuration: '30s',
      maximumDuration: '90s',
      narrativeStructure: 'Hook (3s) → claim → evidence beat → takeaway',
      evidenceDepth: 'Single verified fact card — no stacked contests',
      visualRequirements: '9:16 first; readable burn-in; subject-safe B-roll',
      audioRequirements: 'Captions-first; music under speech',
      aspectRatios: '9:16 · 1:1 crop',
      captions: 'Burn-in or open captions required',
      accessibility: 'Silent-autoplay safe; no flashing patterns',
      fields: 'Science, civics, skills',
      audiences: 'Primary learners; secondary public',
      channels: 'Short-form social + owned cutdowns',
      costBoundary: 'Low–medium; template-led',
      frequency: 'High cadence after quality gate',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Explainer',
    description: 'Bounded concept walkthrough with claim–evidence–implication.',
    status: 'ACTIVE',
    priority: 94,
    configuration: {
      systemKey: 'fmt.explainer',
      origin: 'SYSTEM_POLICY',
      family: 'explainer',
      durationMinSec: 120,
      durationMaxSec: 480,
      format: 'Explainer',
      purpose: 'Teach one concept with attributable sources',
      minimumDuration: '2m',
      maximumDuration: '8m',
      narrativeStructure: 'Question → definitions → evidence steps → recap',
      evidenceDepth: '≥2 attributable sources for material claims',
      visualRequirements: 'Diagrams + labelled plates; 16:9 master',
      audioRequirements: 'Measured VO; chapter markers',
      aspectRatios: '16:9 · 9:16 cutdown',
      captions: 'Full captions; glossary on first use',
      accessibility: 'High-contrast graphics',
      fields: 'Cross-domain where taxonomy allows',
      audiences: 'Learners + educators',
      channels: 'Owned long-form',
      costBoundary: 'Medium',
      frequency: 'Steady with domain priorities',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Lesson segment',
    description: 'Classroom unit with stated outcome and checkpoint.',
    status: 'ACTIVE',
    priority: 90,
    configuration: {
      systemKey: 'fmt.lesson-segment',
      origin: 'SYSTEM_POLICY',
      family: 'lesson',
      durationMinSec: 180,
      durationMaxSec: 720,
      format: 'Lesson segment',
      purpose: 'One learning outcome + pause-and-discuss checkpoint',
      minimumDuration: '3m',
      maximumDuration: '12m',
      narrativeStructure: 'Outcome → teach → example → checkpoint → recap',
      evidenceDepth: 'Curriculum-aligned; teacher-note sources',
      visualRequirements: 'Clear boards; step numbering; minimal decoration',
      audioRequirements: 'Pace for pause-and-discuss',
      aspectRatios: '16:9 · 4:3 classroom crop',
      captions: 'Full captions; key terms emphasised',
      accessibility: 'Captions required; companion text options',
      fields: 'Classroom-fit taxonomy subjects',
      audiences: 'Primary educators + learners',
      channels: 'LMS / lesson library',
      costBoundary: 'Medium; template-led',
      frequency: 'Curriculum packs — not viral spikes',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Documentary segment',
    description: 'Place-and-people context with stronger evidence bar.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'fmt.documentary-segment',
      origin: 'SYSTEM_POLICY',
      family: 'documentary',
      durationMinSec: 240,
      durationMaxSec: 900,
      format: 'Documentary segment',
      purpose: 'Situate a real-world topic with verifiable context',
      minimumDuration: '4m',
      maximumDuration: '15m',
      narrativeStructure: 'Scene → stakes → evidence journey → grounded close',
      evidenceDepth: 'Primary/institutional sources; attributed interviews',
      visualRequirements: 'Location-authentic; re-enactments labelled',
      audioRequirements: 'Interview intelligibility first',
      aspectRatios: '16:9',
      captions: 'Full captions; speaker IDs',
      accessibility: 'Content warnings when warranted',
      fields: 'Civics, history, geography, science-in-society',
      audiences: 'Educators + general public',
      channels: 'Owned documentary playlists',
      costBoundary: 'Medium–high; authenticity gates first',
      frequency: 'Lower cadence; higher review',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Featurette',
    description: 'Mid-length story unit with act structure.',
    status: 'ACTIVE',
    priority: 86,
    configuration: {
      systemKey: 'fmt.featurette',
      origin: 'SYSTEM_POLICY',
      family: 'featurette',
      durationMinSec: 360,
      durationMaxSec: 1200,
      format: 'Featurette',
      purpose: 'Contained story with stronger craft than short-form',
      minimumDuration: '6m',
      maximumDuration: '20m',
      narrativeStructure: 'Cold open → acts → evidence beats → reflective close',
      evidenceDepth: 'Multiple sources; fair contested points',
      visualRequirements: 'Cinematic but educational; brand secondary',
      audioRequirements: 'Full mix; VO optional',
      aspectRatios: '16:9 · 2.39:1 only if justified',
      captions: 'Full captions; optional SDH',
      accessibility: 'Warnings for sensitive subjects',
      fields: 'Priority domains + geography-linked stories',
      audiences: 'Secondary public + educators',
      channels: 'Owned long-form / partners',
      costBoundary: 'High; objective-aligned only',
      frequency: 'Selective; portfolio-gated',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
