import type { StrategyRecord } from './contracts';

export type PolicyGeography = StrategyRecord & {
  configuration: Record<string, unknown> & { systemKey: string; origin: 'SYSTEM_POLICY' };
};

/**
 * System country & regional profiles for Stage 01.
 * Directional authenticity policy only — no fabricated reach or census metrics.
 */
export const GEOGRAPHIES_POLICY: PolicyGeography[] = [
  {
    name: 'Nigeria · National production context',
    description:
      'Primary operating geography for CACSMS production authenticity, language mix, and cultural safeguards.',
    status: 'ACTIVE',
    priority: 95,
    configuration: {
      systemKey: 'geo.nigeria.national',
      origin: 'SYSTEM_POLICY',
      country: 'Nigeria',
      region: 'West Africa',
      state: 'National / multi-state',
      timeZone: 'Africa/Lagos (WAT)',
      supportedLanguages: 'English, Hausa, Yoruba, Igbo (contextual)',
      culturalContext:
        'Multi-ethnic federation; respect regional customs, dress, and communal norms in depiction.',
      historicalContext:
        'Post-independence civic and cultural narratives require documented local framing; avoid colonial caricature.',
      representationRules:
        'Prefer locally recognisable settings and people; do not flatten Nigeria into a single stereotype.',
      sensitiveSubjects: 'Ethnic conflict, religious tension, electoral violence',
      restrictedSubjects: 'Unverified atrocity claims; medical diagnosis directed at individuals',
      localSourceRequirements: 'At least one Nigerian-authoritative source for material local claims',
      localTerminology: 'Use locally current place names and honorifics where relevant',
      authenticityRules: 'Fail closed on invented landmarks, dialects, or ceremonial detail',
      demographics: 'UNMEASURED — qualitative audience fit only',
      eventsAndSeasons: 'Independence commemorations, major festivals, academic calendar windows',
      visualRepresentation: 'Authentic urban/rural variety; avoid poverty-only or safari tropes',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'West Africa · Regional adjacency',
    description:
      'Adjacent West African context for cross-border cultural literacy without inventing market metrics.',
    status: 'ACTIVE',
    priority: 85,
    configuration: {
      systemKey: 'geo.west-africa.regional',
      origin: 'SYSTEM_POLICY',
      country: 'Multi-country (West Africa)',
      region: 'West Africa',
      state: 'Regional',
      timeZone: 'WAT / GMT variants by country',
      supportedLanguages: 'English, French, major regional languages (contextual)',
      culturalContext: 'Shared Sahelian and coastal cultural corridors; country-specific validation required.',
      historicalContext: 'Colonial borders and trade routes shape contemporary identities — cite carefully.',
      representationRules: 'Do not treat West Africa as a monolith; name the country when known.',
      sensitiveSubjects: 'Border disputes, coups, xenophobia',
      restrictedSubjects: 'Unverified conflict footage claims',
      localSourceRequirements: 'Country-level authoritative sources when a specific state is depicted',
      localTerminology: 'Prefer endonyms; avoid outdated colonial labels',
      authenticityRules: 'Geography and costume must match the named country',
      demographics: 'UNMEASURED',
      eventsAndSeasons: 'Regional festival and rainy/dry season awareness',
      visualRepresentation: 'Distinct city/coast/sahel visual grammar when specified',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'United Kingdom · Anglophone reference',
    description:
      'Secondary operating geography for UK-facing educational and documentary framing.',
    status: 'ACTIVE',
    priority: 78,
    configuration: {
      systemKey: 'geo.uk.national',
      origin: 'SYSTEM_POLICY',
      country: 'United Kingdom',
      region: 'Northern Europe',
      state: 'England / Scotland / Wales / Northern Ireland (as specified)',
      timeZone: 'Europe/London',
      supportedLanguages: 'English; Welsh/Scottish Gaelic when story-relevant',
      culturalContext: 'Nation and home-nation identities; avoid London-only defaults.',
      historicalContext: 'Imperial history must be evidence-led when referenced.',
      representationRules: 'Show regional diversity; do not erase minority communities',
      sensitiveSubjects: 'Sectarian conflict, race riots, monarchy controversy',
      restrictedSubjects: 'Unverified defamation of living persons',
      localSourceRequirements: 'UK institutional or peer-reviewed sources for civic claims',
      localTerminology: 'Use correct home-nation terminology',
      authenticityRules: 'Architecture, signage, and weather must be plausible for the named place',
      demographics: 'UNMEASURED',
      eventsAndSeasons: 'Academic terms, remembrance periods, national holidays',
      visualRepresentation: 'Urban/rural UK variety; avoid stock “Big Ben only” framing',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'United States · Broad educational reach',
    description:
      'Secondary geography for US educational explainers with state-aware authenticity gates.',
    status: 'ACTIVE',
    priority: 74,
    configuration: {
      systemKey: 'geo.us.national',
      origin: 'SYSTEM_POLICY',
      country: 'United States',
      region: 'North America',
      state: 'Multi-state (specify when known)',
      timeZone: 'Multiple US time zones',
      supportedLanguages: 'English; Spanish when story-relevant',
      culturalContext: 'Federal + state variation; avoid single-coast stereotypes.',
      historicalContext: 'Civil rights, Indigenous, and immigration histories require careful sourcing.',
      representationRules: 'Do not erase racial or regional diversity',
      sensitiveSubjects: 'Gun violence, racial violence, election denial',
      restrictedSubjects: 'Partisan campaign content presented as neutral fact',
      localSourceRequirements: 'Federal/state authoritative or peer-reviewed sources for civic claims',
      localTerminology: 'Use correct state and city names',
      authenticityRules: 'Fail closed on invented institutions or geography',
      demographics: 'UNMEASURED',
      eventsAndSeasons: 'School calendar, federal holidays, major civic dates',
      visualRepresentation: 'Region-appropriate landscapes and built environment',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Global diaspora · Cross-border audiences',
    description:
      'Conditional geography for diaspora-facing stories that must still anchor to a primary place.',
    status: 'ACTIVE',
    priority: 60,
    configuration: {
      systemKey: 'geo.global.diaspora',
      origin: 'SYSTEM_POLICY',
      country: 'Multi-country (diaspora)',
      region: 'Transnational',
      state: 'Not applicable',
      timeZone: 'Audience-local',
      supportedLanguages: 'English plus audience home languages',
      culturalContext: 'Diaspora identity is dual-context; avoid erasing either home or host culture.',
      historicalContext: 'Migration histories must be sourced; no invented origin myths',
      representationRules: 'Name both origin and host contexts when depicted',
      sensitiveSubjects: 'Xenophobia, immigration enforcement trauma',
      restrictedSubjects: 'Unverified diaspora population statistics presented as measured',
      localSourceRequirements: 'Sources from both origin and host contexts when claims span both',
      localTerminology: 'Respect community self-identifiers',
      authenticityRules: 'Do not invent diaspora size or influence metrics',
      demographics: 'UNMEASURED',
      eventsAndSeasons: 'Home-country commemorations observed abroad',
      visualRepresentation: 'Hybrid places; avoid exoticising either context',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
