import type { StrategyRecord } from './contracts';

export type PolicyLocalisation = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    localeFamily: string;
  };
};

/**
 * Locale constellation — EN-NG hub + language satellites.
 * Cultural adaptation beyond literal translation; no fluency scores.
 */
export const LOCALISATION_POLICY: PolicyLocalisation[] = [
  {
    name: 'EN-NG hub',
    description: 'Default production language — centre of the constellation.',
    status: 'ACTIVE',
    priority: 98,
    configuration: {
      systemKey: 'loc.en-ng',
      origin: 'SYSTEM_POLICY',
      localeFamily: 'english',
      primaryLanguage: 'English (Nigeria)',
      secondaryLanguages: 'HA, YO, IG, PCM (register-gated)',
      countryMappings: 'Nigeria primary; West Africa instructional EN',
      translationRules: 'Produce in EN-NG; translate out only when a satellite kit is selected',
      transliterationRules: 'Keep geo-policy spellings for places and names',
      accentPreferences: 'Neutral Nigerian educational VO',
      pronunciationDictionary: 'Institutions, places, honorifics',
      localTerminology: 'Nigerian educational/civic terms over US/UK defaults',
      dateNumberFormats: 'DD/MM/YYYY · metric · Naira labelled',
      measurementUnits: 'Metric',
      captions: 'EN required; bilingual packs per satellite',
      subtitleLanguages: 'EN; HA/YO/IG/PCM when kit approved',
      readingLevel: 'Secondary default; simplify for primary lessons',
      culturalAdaptation: 'Nigerian classroom and civic examples',
      regionalVariants: 'North/south examples without stereotyping',
      machineTranslationThreshold: 'No raw MT to learners',
      humanReview: 'First locale launch + sensitive civic/cultural topics',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Hausa satellite',
    description: 'Northern emphasis — orthography and honorific care.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'loc.ha-ng',
      origin: 'SYSTEM_POLICY',
      localeFamily: 'hausa',
      primaryLanguage: 'Hausa',
      secondaryLanguages: 'English (Nigeria)',
      countryMappings: 'Northern Nigeria emphasis; national OK',
      translationRules: 'Meaning-first Hausa; preserve educational precision',
      transliterationRules: 'Standard Hausa orthography',
      accentPreferences: 'Natural Hausa VO — no parody',
      pronunciationDictionary: 'STEM borrowings + toponyms',
      localTerminology: 'Established Hausa educational vocabulary',
      dateNumberFormats: 'EN-NG numerals on screen unless pack overrides',
      measurementUnits: 'Metric',
      captions: 'HA when VO is HA; EN companion encouraged',
      subtitleLanguages: 'HA, EN',
      readingLevel: 'Outcome-aligned; limit loanword density',
      culturalAdaptation: 'Honorifics, dress norms, religious sensitivity',
      regionalVariants: 'Do not flatten all Hausa contexts',
      machineTranslationThreshold: 'MT draft only → human localisation',
      humanReview: 'Mandatory for cultural, religious, civic packs',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Yoruba satellite',
    description: 'Tone marks and broadly understood national forms.',
    status: 'ACTIVE',
    priority: 90,
    configuration: {
      systemKey: 'loc.yo-ng',
      origin: 'SYSTEM_POLICY',
      localeFamily: 'yoruba',
      primaryLanguage: 'Yoruba',
      secondaryLanguages: 'English (Nigeria)',
      countryMappings: 'South-West emphasis; national OK',
      translationRules: 'Tone marks where required; meaning over calque',
      transliterationRules: 'Standard Yoruba orthography',
      accentPreferences: 'Natural Yoruba VO — no comic register for serious topics',
      pronunciationDictionary: 'Technical terms + toponyms',
      localTerminology: 'Established educational Yoruba; gloss coinages',
      dateNumberFormats: 'EN-NG conventions unless overridden',
      measurementUnits: 'Metric',
      captions: 'YO when VO is YO; EN companion encouraged',
      subtitleLanguages: 'YO, EN',
      readingLevel: 'Speakable VO rhythm',
      culturalAdaptation: 'Greetings, community framing, festival care',
      regionalVariants: 'Prefer broadly understood forms nationally',
      machineTranslationThreshold: 'No raw MT to learners',
      humanReview: 'Mandatory for cultural and civic packs',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Igbo satellite',
    description: 'Modern educational Igbo with oral clarity.',
    status: 'ACTIVE',
    priority: 88,
    configuration: {
      systemKey: 'loc.ig-ng',
      origin: 'SYSTEM_POLICY',
      localeFamily: 'igbo',
      primaryLanguage: 'Igbo',
      secondaryLanguages: 'English (Nigeria)',
      countryMappings: 'South-East emphasis; national OK',
      translationRules: 'Clear modern educational Igbo',
      transliterationRules: 'Standard Igbo orthography',
      accentPreferences: 'Natural Igbo VO',
      pronunciationDictionary: 'STEM borrowings + place names',
      localTerminology: 'Community-accepted terms; gloss innovations',
      dateNumberFormats: 'EN-NG unless overridden',
      measurementUnits: 'Metric',
      captions: 'IG when VO is IG; EN companion encouraged',
      subtitleLanguages: 'IG, EN',
      readingLevel: 'Oral clarity first',
      culturalAdaptation: 'Kinship language and local examples without stereotyping',
      regionalVariants: 'Widely understood national forms',
      machineTranslationThreshold: 'MT draft + human localisation',
      humanReview: 'Mandatory for cultural and civic packs',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'PCM satellite · register-gated',
    description: 'Optional reach language — never default for formal instruction.',
    status: 'ACTIVE',
    priority: 82,
    configuration: {
      systemKey: 'loc.pcm-ng',
      origin: 'SYSTEM_POLICY',
      localeFamily: 'pidgin',
      primaryLanguage: 'Nigerian Pidgin',
      secondaryLanguages: 'English (Nigeria) always paired',
      countryMappings: 'National informal reach; formal packs stay EN/HA/YO/IG',
      translationRules: 'Clarity first — do not dilute factual precision',
      transliterationRules: 'Consistent PCM spelling within a package',
      accentPreferences: 'Natural PCM — never mockery for serious topics',
      pronunciationDictionary: 'Gloss technical terms in EN when unstable in PCM',
      localTerminology: 'Everyday PCM for hooks; EN for formal definitions',
      dateNumberFormats: 'EN-NG on screen',
      measurementUnits: 'Metric',
      captions: 'PCM + EN when PCM VO used',
      subtitleLanguages: 'PCM, EN',
      readingLevel: 'Spoken clarity over literary flourish',
      culturalAdaptation: 'Warmth and access — never ridicule communities',
      regionalVariants: 'Broadly intelligible national PCM only',
      machineTranslationThreshold: 'Do not trust generic MT for PCM meaning',
      humanReview: 'Required for every PCM learner-facing package',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
