import type { StrategyRecord } from './contracts';

export type PolicyPortfolio = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    allocationCategory: string;
  };
};

/**
 * Portfolio allocation rules for Stage 01.
 * Normative share bands only — capacity utilization and diversity outcomes remain UNMEASURED
 * until production selection runs persist measured results.
 */
export const PORTFOLIO_POLICY: PolicyPortfolio[] = [
  {
    name: 'Domain · Education & literacy',
    description: 'Anchor share for education and literacy domains in the active package.',
    status: 'ACTIVE',
    priority: 96,
    configuration: {
      systemKey: 'port.domain.education',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'domains',
      dimension: 'domain',
      dimensionValue: 'education-literacy',
      minimumAllocation: '25',
      maximumAllocation: '45',
      targetPercentage: '35',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'No hard cap beyond diversityRequirement',
      diversityRequirement: 'At least 2 education sub-topics per cycle',
      repetitionLimit: 'Avoid consecutive identical topic packs',
      capacityLimit: 'Subject to production capacity band',
      budgetLimit: 'Within education objective envelope',
      balancingLogic: 'Raise share when under-coverage detected vs objectives',
      autoOptimize: 'YES — rebalance within min/max after validate',
      linkedObjectives: 'audience literacy, coverage balance',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Domain · Civics & history',
    description: 'Maintain civic and historical coverage without crowding education share.',
    status: 'ACTIVE',
    priority: 94,
    configuration: {
      systemKey: 'port.domain.civics',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'domains',
      dimension: 'domain',
      dimensionValue: 'civics-history',
      minimumAllocation: '15',
      maximumAllocation: '35',
      targetPercentage: '25',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Elevated review cadence for contested topics',
      diversityRequirement: 'Mix eras and geographies',
      repetitionLimit: 'No more than 1 contested election pack per window',
      capacityLimit: 'Subject to risk-review capacity',
      budgetLimit: 'Within civics objective envelope',
      balancingLogic: 'Hold at minimum during electoral blackouts',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'civic literacy, geographic authenticity',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Domain · Health literacy',
    description: 'Protect health-literacy share with institutional evidence preference.',
    status: 'ACTIVE',
    priority: 93,
    configuration: {
      systemKey: 'port.domain.health',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'domains',
      dimension: 'domain',
      dimensionValue: 'health-literacy',
      minimumAllocation: '10',
      maximumAllocation: '30',
      targetPercentage: '20',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Review-gated for clinical framing',
      diversityRequirement: 'Prevention + literacy topics both present',
      repetitionLimit: 'No back-to-back identical condition packs',
      capacityLimit: 'Medical review capacity',
      budgetLimit: 'Within health objective envelope',
      balancingLogic: 'Do not steal share from education below its minimum',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'public health literacy',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Domain · Culture & society',
    description: 'Residual domain share for culture and society topics.',
    status: 'ACTIVE',
    priority: 90,
    configuration: {
      systemKey: 'port.domain.culture',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'domains',
      dimension: 'domain',
      dimensionValue: 'culture-society',
      minimumAllocation: '10',
      maximumAllocation: '30',
      targetPercentage: '20',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Localisation review when place-bound',
      diversityRequirement: 'Avoid single-region cultural monopoly',
      repetitionLimit: 'Rotate cultural themes',
      capacityLimit: 'Localisation capacity',
      budgetLimit: 'Within culture objective envelope',
      balancingLogic: 'Fill residual after education/civics/health targets',
      autoOptimize: 'YES — domains group targets sum to 100',
      linkedObjectives: 'cultural authenticity',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Audience · General adult',
    description: 'Primary audience share for general adult educational viewers.',
    status: 'ACTIVE',
    priority: 88,
    configuration: {
      systemKey: 'port.audience.general',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'audiences',
      dimension: 'audience',
      dimensionValue: 'general-adult',
      minimumAllocation: '30',
      maximumAllocation: '55',
      targetPercentage: '40',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Aligned to channel cadence',
      diversityRequirement: 'Pair with learner and local community shares',
      repetitionLimit: 'Rotate formats within audience',
      capacityLimit: 'Production capacity band',
      budgetLimit: 'Primary audience envelope',
      balancingLogic: 'Protect learner minimum before raising general share',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'broad literacy reach',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Audience · Learners',
    description: 'Protect learner-oriented pack share with age-suitability gates.',
    status: 'ACTIVE',
    priority: 89,
    configuration: {
      systemKey: 'port.audience.learners',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'audiences',
      dimension: 'audience',
      dimensionValue: 'learners',
      minimumAllocation: '25',
      maximumAllocation: '45',
      targetPercentage: '35',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Lesson-pack friendly windows',
      diversityRequirement: 'Multiple reading levels represented',
      repetitionLimit: 'Avoid identical lesson repeats in-window',
      capacityLimit: 'Format packaging capacity',
      budgetLimit: 'Learner objective envelope',
      balancingLogic: 'Mandatory floor; cannot be optimized below min',
      autoOptimize: 'YES above minimum only',
      linkedObjectives: 'learner literacy',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Audience · Local community',
    description: 'Local and diaspora community share tied to geography policy.',
    status: 'ACTIVE',
    priority: 86,
    configuration: {
      systemKey: 'port.audience.local',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'audiences',
      dimension: 'audience',
      dimensionValue: 'local-community',
      minimumAllocation: '15',
      maximumAllocation: '35',
      targetPercentage: '25',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Geography publishing windows',
      diversityRequirement: 'Multiple localities when capacity allows',
      repetitionLimit: 'Rotate localities',
      capacityLimit: 'Localisation capacity',
      budgetLimit: 'Community envelope',
      balancingLogic: 'Audiences group targets sum to 100',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'local relevance',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Geography · Primary markets',
    description: 'Primary geography share for configured launch markets.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'port.geography.primary',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'regions',
      dimension: 'geography',
      dimensionValue: 'primary-markets',
      minimumAllocation: '35',
      maximumAllocation: '60',
      targetPercentage: '45',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Respect channel blackout windows',
      diversityRequirement: 'At least 2 primary localities',
      repetitionLimit: 'Rotate place-bound packs',
      capacityLimit: 'Localisation kit readiness',
      budgetLimit: 'Primary market envelope',
      balancingLogic: 'Fail-closed on restricted geographies',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'geographic authenticity',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Geography · Secondary markets',
    description: 'Secondary geography share for expansion markets.',
    status: 'ACTIVE',
    priority: 84,
    configuration: {
      systemKey: 'port.geography.secondary',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'regions',
      dimension: 'geography',
      dimensionValue: 'secondary-markets',
      minimumAllocation: '20',
      maximumAllocation: '45',
      targetPercentage: '35',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Lower than primary until kit ready',
      diversityRequirement: 'Do not collapse into one secondary locale',
      repetitionLimit: 'Rotate secondary localities',
      capacityLimit: 'Localisation backlog',
      budgetLimit: 'Secondary envelope',
      balancingLogic: 'Raise only when primary minimum satisfied',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'coverage expansion',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Geography · Exploratory',
    description: 'Limited exploratory geography share for discovery packs.',
    status: 'ACTIVE',
    priority: 78,
    configuration: {
      systemKey: 'port.geography.exploratory',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'regions',
      dimension: 'geography',
      dimensionValue: 'exploratory',
      minimumAllocation: '5',
      maximumAllocation: '25',
      targetPercentage: '20',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Low; review-gated',
      diversityRequirement: 'One exploratory locale at a time preferred',
      repetitionLimit: 'Strict — no consecutive exploratory repeats',
      capacityLimit: 'Research capacity',
      budgetLimit: 'Exploratory envelope',
      balancingLogic: 'Regions group targets sum to 100',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'discovery coverage',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Format · Long-form explainers',
    description: 'Primary format share for long-form educational explainers.',
    status: 'ACTIVE',
    priority: 87,
    configuration: {
      systemKey: 'port.format.longform',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'formats',
      dimension: 'format',
      dimensionValue: 'longform-explainer',
      minimumAllocation: '30',
      maximumAllocation: '55',
      targetPercentage: '40',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Production capacity gated',
      diversityRequirement: 'Pair with shorts and lessons',
      repetitionLimit: 'Rotate subjects within long-form',
      capacityLimit: 'Visual production capacity',
      budgetLimit: 'Long-form envelope',
      balancingLogic: 'Protect lesson-pack floor for learners',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'depth coverage',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Format · Short-form',
    description: 'Short-form share for social and snackable educational units.',
    status: 'ACTIVE',
    priority: 85,
    configuration: {
      systemKey: 'port.format.shortform',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'formats',
      dimension: 'format',
      dimensionValue: 'short-form',
      minimumAllocation: '25',
      maximumAllocation: '45',
      targetPercentage: '35',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Channel cadence',
      diversityRequirement: 'Multiple topics per window',
      repetitionLimit: 'Cap identical hook reuse',
      capacityLimit: 'Edit capacity',
      budgetLimit: 'Short-form envelope',
      balancingLogic: 'Do not exceed max when long-form under minimum',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'reach',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Format · Lesson packs',
    description: 'Lesson-pack share for structured learner formats.',
    status: 'ACTIVE',
    priority: 86,
    configuration: {
      systemKey: 'port.format.lessons',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'formats',
      dimension: 'format',
      dimensionValue: 'lesson-packs',
      minimumAllocation: '15',
      maximumAllocation: '35',
      targetPercentage: '25',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Learner calendar windows',
      diversityRequirement: 'Multiple reading levels',
      repetitionLimit: 'Rotate modules',
      capacityLimit: 'Instructional design capacity',
      budgetLimit: 'Lesson envelope',
      balancingLogic: 'Formats group targets sum to 100',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'learner outcomes',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Channel · Owned surfaces',
    description: 'Owned-channel share for durable educational distribution.',
    status: 'ACTIVE',
    priority: 91,
    configuration: {
      systemKey: 'port.channel.owned',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'channels',
      dimension: 'channel',
      dimensionValue: 'owned',
      minimumAllocation: '40',
      maximumAllocation: '65',
      targetPercentage: '50',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Owned publishing calendar',
      diversityRequirement: 'Mix formats on owned',
      repetitionLimit: 'Standard editorial rotation',
      capacityLimit: 'Publishing ops capacity',
      budgetLimit: 'Owned distribution envelope',
      balancingLogic: 'Prefer owned when social blackout active',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'durable distribution',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Channel · Social',
    description: 'Social channel share gated by brand safety and windows.',
    status: 'ACTIVE',
    priority: 82,
    configuration: {
      systemKey: 'port.channel.social',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'channels',
      dimension: 'channel',
      dimensionValue: 'social',
      minimumAllocation: '15',
      maximumAllocation: '40',
      targetPercentage: '30',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Platform cadence + blackout windows',
      diversityRequirement: 'Avoid single-platform monopoly',
      repetitionLimit: 'Cap identical short reuse',
      capacityLimit: 'Social ops capacity',
      budgetLimit: 'Social envelope',
      balancingLogic: 'Reduce during elevated political sensitivity',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'reach',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Channel · Partner',
    description: 'Partner channel residual share with rights clearance.',
    status: 'ACTIVE',
    priority: 80,
    configuration: {
      systemKey: 'port.channel.partner',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'channels',
      dimension: 'channel',
      dimensionValue: 'partner',
      minimumAllocation: '10',
      maximumAllocation: '30',
      targetPercentage: '20',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Partner calendar',
      diversityRequirement: 'Rights-cleared partners only',
      repetitionLimit: 'Contractual reuse limits',
      capacityLimit: 'Partnership ops',
      budgetLimit: 'Partner envelope',
      balancingLogic: 'Channels group targets sum to 100',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'distribution partnerships',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Language · Primary language',
    description: 'Primary language share before satellite localisation.',
    status: 'ACTIVE',
    priority: 83,
    configuration: {
      systemKey: 'port.language.primary',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'languages',
      dimension: 'language',
      dimensionValue: 'primary',
      minimumAllocation: '55',
      maximumAllocation: '80',
      targetPercentage: '65',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Hub language first',
      diversityRequirement: 'Satellite languages present when kit ready',
      repetitionLimit: 'N/A',
      capacityLimit: 'Translation capacity',
      budgetLimit: 'Language envelope',
      balancingLogic: 'Localisation ladder — hub before satellites',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'localisation readiness',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Language · Satellite languages',
    description: 'Satellite language share for configured localisation kits.',
    status: 'ACTIVE',
    priority: 81,
    configuration: {
      systemKey: 'port.language.satellite',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'languages',
      dimension: 'language',
      dimensionValue: 'satellite',
      minimumAllocation: '20',
      maximumAllocation: '45',
      targetPercentage: '35',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'After hub language ready',
      diversityRequirement: 'Human review when localisation kit requires',
      repetitionLimit: 'Avoid duplicate MT without review',
      capacityLimit: 'MT + human review capacity',
      budgetLimit: 'Satellite envelope',
      balancingLogic: 'Languages group targets sum to 100',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'multilingual coverage',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Capacity · Production bandwidth',
    description: 'Global production capacity ceiling for the strategy cycle.',
    status: 'ACTIVE',
    priority: 97,
    configuration: {
      systemKey: 'port.capacity.production',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'production_capacity',
      dimension: 'capacity',
      dimensionValue: 'production-bandwidth',
      minimumAllocation: '0',
      maximumAllocation: '100',
      targetPercentage: 'UNMEASURED',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Do not schedule beyond declared capacityLimit',
      diversityRequirement: 'Preserve diversity floors under load',
      repetitionLimit: 'Defer low-priority repeats first',
      capacityLimit: 'Declared production bandwidth — utilization UNMEASURED',
      budgetLimit: 'Within portfolio budgetLimit aggregate',
      balancingLogic: 'Shed optional share before mandatory floors',
      autoOptimize: 'YES — queue optional when capacity conflict detected',
      linkedObjectives: 'sustainable throughput',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Frequency · Publishing cadence',
    description: 'Publishing frequency caps aligned to channel enablement.',
    status: 'ACTIVE',
    priority: 79,
    configuration: {
      systemKey: 'port.frequency.publishing',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'publishing_frequency',
      dimension: 'frequency',
      dimensionValue: 'publishing-cadence',
      minimumAllocation: '0',
      maximumAllocation: '100',
      targetPercentage: 'UNMEASURED',
      timeWindow: 'Per channel publishingWindows',
      frequencyCap: 'Respect channel cadence + blackouts',
      diversityRequirement: 'Maintain dimension diversity under cadence pressure',
      repetitionLimit: 'Enforce per-dimension repetitionLimit',
      capacityLimit: 'Publishing ops',
      budgetLimit: 'Distribution envelope',
      balancingLogic: 'Owned preferred when social cadence saturated',
      autoOptimize: 'YES',
      linkedObjectives: 'publishing readiness',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Budget · Portfolio envelope',
    description: 'Aggregate budget envelope — no fabricated spend utilization.',
    status: 'ACTIVE',
    priority: 95,
    configuration: {
      systemKey: 'port.budget.envelope',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'budgets',
      dimension: 'budget',
      dimensionValue: 'portfolio-envelope',
      minimumAllocation: '0',
      maximumAllocation: '100',
      targetPercentage: 'UNMEASURED',
      timeWindow: 'Strategy version lifetime',
      frequencyCap: 'N/A',
      diversityRequirement: 'Do not starve mandatory dimension floors',
      repetitionLimit: 'N/A',
      capacityLimit: 'Budget governance',
      budgetLimit: 'Declared portfolio envelope — spend UNMEASURED',
      balancingLogic: 'Mandatory floors > optional exploratory share',
      autoOptimize: 'YES — flag over-allocation conflicts',
      linkedObjectives: 'strategic objectives funding alignment',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Priority · Strategic objective alignment',
    description: 'Prioritise packs mapped to active strategic objectives.',
    status: 'ACTIVE',
    priority: 98,
    configuration: {
      systemKey: 'port.priority.objectives',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'priorities',
      dimension: 'priority',
      dimensionValue: 'strategic-objectives',
      minimumAllocation: '70',
      maximumAllocation: '100',
      targetPercentage: '85',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Objective-driven queue',
      diversityRequirement: 'Still honour domain/audience floors',
      repetitionLimit: 'Objective packs rotate evidence angles',
      capacityLimit: 'Subject to production capacity',
      budgetLimit: 'Objective envelopes',
      balancingLogic: 'Objective-aligned share before discretionary topics',
      autoOptimize: 'YES within min/max',
      linkedObjectives: 'all ACTIVE objectives',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Priority · Discretionary discovery',
    description: 'Residual discretionary share for discovery packs outside core objectives.',
    status: 'ACTIVE',
    priority: 70,
    configuration: {
      systemKey: 'port.priority.discretionary',
      origin: 'SYSTEM_POLICY',
      allocationCategory: 'priorities',
      dimension: 'priority',
      dimensionValue: 'discretionary-discovery',
      minimumAllocation: '0',
      maximumAllocation: '30',
      targetPercentage: '15',
      timeWindow: 'Rolling strategy cycle',
      frequencyCap: 'Shed first under capacity pressure',
      diversityRequirement: 'Optional; do not displace mandatory floors',
      repetitionLimit: 'Strict — discovery does not repeat consecutively',
      capacityLimit: 'Only when production headroom exists',
      budgetLimit: 'Discretionary envelope',
      balancingLogic: 'Priorities group targets sum to 100',
      autoOptimize: 'YES — first to reduce when capacity conflicts',
      linkedObjectives: 'discovery coverage',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
