import type { StrategyRecord } from './contracts';

export type PolicyRisk = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    riskCategory: string;
  };
};

/**
 * System risk & sensitivity policies for Stage 01.
 * Normative gates only — no fabricated probability or residual-risk scores.
 */
export const RISK_POLICY: PolicyRisk[] = [
  {
    name: 'Misinformation & contested claims',
    description: 'Fail-closed on unverified material claims; escalate contested civic topics.',
    status: 'ACTIVE',
    priority: 98,
    configuration: {
      systemKey: 'risk.misinformation',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'misinformation',
      category: 'Misinformation',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'All domains with factual claims',
      countries: 'Configured geographies',
      audiences: 'All; elevated for learners',
      formats: 'All publishable formats',
      channels: 'All channels',
      detectionMethod: 'Source-policy rung checks + corroboration gates + editorial conflict flags',
      automaticAction: 'BLOCK sole anonymous/social evidence; HOLD contested claims for review',
      escalationRequired: 'YES for election, atrocity, or public-health contests',
      blockingThreshold: 'Material claim without ALLOWED/CONDITIONAL source class',
      reviewRequired: 'YES when corroboration incomplete',
      remediation: 'Add higher-rung sources or downgrade claim certainty',
      closureEvidence: 'Citation package + reviewer note before release',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Harmful & violent content',
    description: 'Block graphic cruelty and weaponised harm framing for shock value.',
    status: 'ACTIVE',
    priority: 97,
    configuration: {
      systemKey: 'risk.harm-violence',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'violence',
      category: 'Violence / harmful content',
      severity: 'CRITICAL',
      likelihood: 'UNMEASURED',
      fields: 'News, civics, conflict education',
      countries: 'All',
      audiences: 'All; minors elevated',
      formats: 'Video, image, short-form',
      channels: 'Social + owned',
      detectionMethod: 'Editorial prohibited/restricted lists + human review on conflict packs',
      automaticAction: 'BLOCK prohibited depictions; REVIEW educational conflict framing',
      escalationRequired: 'YES for graphic injury or real-person harm',
      blockingThreshold: 'Prohibited content class from editorial policy',
      reviewRequired: 'YES for any educational violence depiction',
      remediation: 'Reframe with documentary necessity + warnings, or remove',
      closureEvidence: 'Editorial sign-off + audience suitability note',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Hate speech & protected characteristics',
    description: 'Zero tolerance for demeaning protected groups; educational critique must stay evidence-led.',
    status: 'ACTIVE',
    priority: 96,
    configuration: {
      systemKey: 'risk.hate-speech',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'hate_speech',
      category: 'Hate speech',
      severity: 'CRITICAL',
      likelihood: 'UNMEASURED',
      fields: 'Civics, culture, history',
      countries: 'All',
      audiences: 'All',
      formats: 'All',
      channels: 'All',
      detectionMethod: 'Editorial representation rules + human review for identity topics',
      automaticAction: 'BLOCK demeaning content; ESCALATE borderline satire',
      escalationRequired: 'YES',
      blockingThreshold: 'Mockery or dehumanisation of protected characteristics',
      reviewRequired: 'YES for identity-sensitive educational critique',
      remediation: 'Rewrite to evidence-led analysis without demeaning framing',
      closureEvidence: 'Editorial + risk reviewer acknowledgement',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Copyright & rights clearance',
    description: 'Require rights recording before reuse of third-party media or long quotes.',
    status: 'ACTIVE',
    priority: 94,
    configuration: {
      systemKey: 'risk.copyright',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'copyright',
      category: 'Copyright',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'All media assets',
      countries: 'All',
      audiences: 'All',
      formats: 'Video, audio, image, text',
      channels: 'All publish channels',
      detectionMethod: 'Source-policy rightsRequired + asset metadata checks',
      automaticAction: 'HOLD publish until rights field populated',
      escalationRequired: 'YES for commercial soundtrack or full republication risk',
      blockingThreshold: 'Missing rightsRequired for non-owned assets',
      reviewRequired: 'Conditional for fair-quote educational use',
      remediation: 'Replace asset, shorten quote, or obtain licence',
      closureEvidence: 'Licence / fair-use rationale recorded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Privacy & personal data',
    description: 'Protect identifiable individuals; no non-consensual private media.',
    status: 'ACTIVE',
    priority: 95,
    configuration: {
      systemKey: 'risk.privacy',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'privacy',
      category: 'Privacy',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'Biographical and local stories',
      countries: 'Configured geographies',
      audiences: 'All; elevated for minors',
      formats: 'All',
      channels: 'All',
      detectionMethod: 'Editorial disclosures + source anonymousRestrictions',
      automaticAction: 'BLOCK non-consensual private media; REVIEW identifiable minors',
      escalationRequired: 'YES for minors or sensitive personal data',
      blockingThreshold: 'Private / non-consensual media present',
      reviewRequired: 'YES when naming living private individuals',
      remediation: 'Anonymise, blur, or obtain consent documentation',
      closureEvidence: 'Consent or anonymisation checklist',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Medical & clinical advice',
    description: 'No individual diagnosis or treatment directives; educational framing only.',
    status: 'ACTIVE',
    priority: 93,
    configuration: {
      systemKey: 'risk.medical',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'medical',
      category: 'Medical',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'Health literacy domains',
      countries: 'All',
      audiences: 'General public elevated',
      formats: 'Explainers, shorts, lessons',
      channels: 'Owned + social',
      detectionMethod: 'Editorial restrictedContent + source authority gates',
      automaticAction: 'BLOCK individual clinical directives; REVIEW health explainers',
      escalationRequired: 'YES for treatment claims',
      blockingThreshold: 'Personal diagnosis / prescribe language',
      reviewRequired: 'YES for health-literacy packs',
      remediation: 'Reframe as general education with institutional sources',
      closureEvidence: 'Institutional citations + disclaimer',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Political & electoral sensitivity',
    description: 'No electioneering; contested political claims need elevated evidence and review.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'risk.political',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'political',
      category: 'Political',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'Civics, governance',
      countries: 'Configured geographies; blackout windows when flagged',
      audiences: 'All',
      formats: 'All',
      channels: 'Social elevated',
      detectionMethod: 'Channel publishingWindows + editorial neutrality rules',
      automaticAction: 'BLOCK electioneering; HOLD contested political claims',
      escalationRequired: 'YES during electoral blackout windows',
      blockingThreshold: 'Campaign advocacy presented as neutral fact',
      reviewRequired: 'YES for contested electoral content',
      remediation: 'Neutral framing + multi-source corroboration',
      closureEvidence: 'Editorial neutrality checklist',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Cultural & regional sensitivity',
    description: 'Defer to geography and localisation policy for place-bound cultural depiction.',
    status: 'ACTIVE',
    priority: 90,
    configuration: {
      systemKey: 'risk.cultural',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'cultural',
      category: 'Cultural',
      severity: 'ELEVATED',
      likelihood: 'UNMEASURED',
      fields: 'Culture, history, religion-adjacent education',
      countries: 'Configured geographies',
      audiences: 'Local + diaspora',
      formats: 'All',
      channels: 'All',
      detectionMethod: 'Geography sensitiveSubjects + localisation humanReview',
      automaticAction: 'REVIEW place-bound cultural packs; BLOCK stereotypes',
      escalationRequired: 'YES for religious or ethnic tension topics',
      blockingThreshold: 'Stereotype flattening or invented ceremonial detail',
      reviewRequired: 'YES when localisation kit marks mandatory review',
      remediation: 'Apply local terminology and geography authenticity rules',
      closureEvidence: 'Geography + localisation reviewer notes',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Brand safety & reputation',
    description: 'Protect CACSMS educational brand from sensational or undisclosed AI-assisted framing.',
    status: 'ACTIVE',
    priority: 88,
    configuration: {
      systemKey: 'risk.brand-safety',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'brand_safety',
      category: 'Brand safety',
      severity: 'MEDIUM',
      likelihood: 'UNMEASURED',
      fields: 'All',
      countries: 'All',
      audiences: 'All',
      formats: 'All',
      channels: 'Social elevated',
      detectionMethod: 'Editorial brandingRules + aiDisclosure checks',
      automaticAction: 'WARN missing AI disclosure; HOLD clickbait packaging',
      escalationRequired: 'Conditional for partnership content',
      blockingThreshold: 'Sensational packaging that overpowers educational subject',
      reviewRequired: 'Conditional',
      remediation: 'Restore subject-led framing and required disclosures',
      closureEvidence: 'Brand packaging checklist',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'AI safety & synthetic media',
    description: 'Disclose material AI assistance; block deceptive synthetic likeness without disclosure.',
    status: 'ACTIVE',
    priority: 91,
    configuration: {
      systemKey: 'risk.ai-safety',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'ai_safety',
      category: 'AI safety',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'All AI-assisted production',
      countries: 'All',
      audiences: 'All',
      formats: 'Video, audio, image',
      channels: 'All',
      detectionMethod: 'Editorial aiDisclosure + production metadata flags',
      automaticAction: 'HOLD missing material AI disclosure; BLOCK deceptive deepfakes',
      escalationRequired: 'YES for synthetic likeness of real persons',
      blockingThreshold: 'Undisclosed synthetic personation',
      reviewRequired: 'YES for synthetic voice/likeness',
      remediation: 'Add disclosure or regenerate without deceptive synthesis',
      closureEvidence: 'Disclosure text + generation provenance',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Legal & regulatory exposure',
    description: 'Avoid legal advice framing; map regulated claims to jurisdiction requirements.',
    status: 'ACTIVE',
    priority: 89,
    configuration: {
      systemKey: 'risk.legal',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'legal',
      category: 'Legal',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'Law, rights, regulated topics',
      countries: 'Configured geographies',
      audiences: 'All',
      formats: 'All',
      channels: 'All',
      detectionMethod: 'Editorial restrictedContent + geography regulatory notes',
      automaticAction: 'BLOCK personal legal advice; REVIEW jurisdiction-bound claims',
      escalationRequired: 'YES for defamation or injunction risk',
      blockingThreshold: 'Specific legal advice to an identifiable person',
      reviewRequired: 'YES for contested legal assertions',
      remediation: 'Reframe as general education with institutional citations',
      closureEvidence: 'Jurisdiction note + citation package',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Financial advice & market claims',
    description: 'No personalised investment directives; disclose uncertainty on market statements.',
    status: 'ACTIVE',
    priority: 87,
    configuration: {
      systemKey: 'risk.financial',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'financial',
      category: 'Financial',
      severity: 'HIGH',
      likelihood: 'UNMEASURED',
      fields: 'Economics, personal finance literacy',
      countries: 'All',
      audiences: 'General public elevated',
      formats: 'Explainers, shorts',
      channels: 'Owned + social',
      detectionMethod: 'Editorial restrictedContent + source authority gates',
      automaticAction: 'BLOCK personalised investment directives; WARN speculative claims',
      escalationRequired: 'YES for product endorsements framed as advice',
      blockingThreshold: 'Buy/sell directives for identifiable instruments',
      reviewRequired: 'YES for market prediction content',
      remediation: 'Educational framing + uncertainty disclosure',
      closureEvidence: 'Disclaimer + institutional sources',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Adult & explicit content',
    description: 'Block non-educational explicit sexual content; age-gate residual edge cases.',
    status: 'ACTIVE',
    priority: 94,
    configuration: {
      systemKey: 'risk.adult-content',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'adult_content',
      category: 'Adult content',
      severity: 'CRITICAL',
      likelihood: 'UNMEASURED',
      fields: 'Health education edge cases only',
      countries: 'All',
      audiences: 'Adults only when educationally necessary',
      formats: 'All',
      channels: 'All',
      detectionMethod: 'Editorial prohibited lists + format suitability',
      automaticAction: 'BLOCK non-educational explicit content',
      escalationRequired: 'YES for any residual edge-case depiction',
      blockingThreshold: 'Explicit sexual content without educational necessity',
      reviewRequired: 'YES for anatomy education packs',
      remediation: 'Clinical educational framing or remove',
      closureEvidence: 'Audience suitability + educational necessity note',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Regional restrictions & sanctions',
    description: 'Honour geography publishing windows, sanctions, and local legal blackouts.',
    status: 'ACTIVE',
    priority: 86,
    configuration: {
      systemKey: 'risk.regional-restrictions',
      origin: 'SYSTEM_POLICY',
      riskCategory: 'regional_restrictions',
      category: 'Regional restrictions',
      severity: 'ELEVATED',
      likelihood: 'UNMEASURED',
      fields: 'All geo-scoped packs',
      countries: 'Configured geographies',
      audiences: 'Local markets',
      formats: 'All',
      channels: 'Channel publishingWindows',
      detectionMethod: 'Geography policy + channel windows + localisation kit',
      automaticAction: 'HOLD during blackout; BLOCK sanctioned destinations',
      escalationRequired: 'YES for sanctions or electoral blackouts',
      blockingThreshold: 'Publish attempt into restricted geography/window',
      reviewRequired: 'Conditional for adjacent markets',
      remediation: 'Retarget geography or wait for window reopen',
      closureEvidence: 'Geography + channel clearance note',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
