import type { StrategyRecord } from './contracts';

export type PolicyThreshold = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    ruleCategory: string;
  };
};

/**
 * Autonomous selection thresholds for Stage 01.
 * Normative decision gates only — no fabricated accuracy or confidence percentages.
 */
export const SELECTION_THRESHOLDS: PolicyThreshold[] = [
  {
    name: 'Evidence quality gate',
    description: 'Reject packs whose sole evidence sits below Conditional on the source ladder.',
    status: 'ACTIVE',
    priority: 97,
    configuration: {
      systemKey: 'thr.evidence-quality',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'evidence_quality',
      metric: 'evidenceQuality',
      operator: 'GTE',
      value: 'CONDITIONAL',
      scopeType: 'GLOBAL',
      scopeId: 'all',
      mandatory: 'YES',
      decisionAction: 'REJECT',
      escalationAction: 'REVIEW when sole source is journalism-class for contested claims',
      overrideAllowed: 'NO for material factual claims',
      auditRequired: 'YES — record ladder rung used',
      linkedSections: 'source-policy,risk-policy,objectives',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Risk severity gate',
    description: 'Hold CRITICAL risk-class content for human review before autonomous accept.',
    status: 'ACTIVE',
    priority: 98,
    configuration: {
      systemKey: 'thr.risk-level',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'risk_levels',
      metric: 'riskSeverity',
      operator: 'NE',
      value: 'CRITICAL_WITHOUT_REVIEW',
      scopeType: 'GLOBAL',
      scopeId: 'all',
      mandatory: 'YES',
      decisionAction: 'REVIEW',
      escalationAction: 'ESCALATE CRITICAL to risk owner',
      overrideAllowed: 'NO',
      auditRequired: 'YES — risk policy systemKey',
      linkedSections: 'risk-policy,editorial-policy',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Audience fit gate',
    description: 'Require declared audience suitability before accept for age-sensitive packs.',
    status: 'ACTIVE',
    priority: 90,
    configuration: {
      systemKey: 'thr.audience-fit',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'audience_fit',
      metric: 'audienceFit',
      operator: 'EQ',
      value: 'DECLARED',
      scopeType: 'AUDIENCE',
      scopeId: 'configured-audiences',
      mandatory: 'YES for minors / learners',
      decisionAction: 'REVIEW',
      escalationAction: 'HOLD until audience segment mapped',
      overrideAllowed: 'Conditional with editorial note',
      auditRequired: 'YES — audience systemKey',
      linkedSections: 'audiences,formats,channels',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Domain relevance gate',
    description: 'Accept only packs that map to an active domain in the strategy package.',
    status: 'ACTIVE',
    priority: 88,
    configuration: {
      systemKey: 'thr.domain-relevance',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'domain_relevance',
      metric: 'domainRelevance',
      operator: 'EQ',
      value: 'MAPPED_ACTIVE_DOMAIN',
      scopeType: 'DOMAIN',
      scopeId: 'active-domains',
      mandatory: 'YES',
      decisionAction: 'REJECT',
      escalationAction: 'REGENERATE topic toward active domains',
      overrideAllowed: 'NO',
      auditRequired: 'YES — domain systemKey',
      linkedSections: 'domains,taxonomy,objectives',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Geographic suitability gate',
    description: 'Fail-closed when geography policy marks destination restricted or in blackout.',
    status: 'ACTIVE',
    priority: 93,
    configuration: {
      systemKey: 'thr.geographic-suitability',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'geographic_suitability',
      metric: 'geographicSuitability',
      operator: 'EQ',
      value: 'ALLOWED_WINDOW',
      scopeType: 'GEOGRAPHY',
      scopeId: 'configured-geographies',
      mandatory: 'YES',
      decisionAction: 'REJECT',
      escalationAction: 'HOLD during blackout; retarget geography',
      overrideAllowed: 'NO during sanctions/electoral blackout',
      auditRequired: 'YES — geography + channel window',
      linkedSections: 'geographies,channels,localisation,risk-policy',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Editorial compliance gate',
    description: 'Require editorial policy compliance before autonomous accept.',
    status: 'ACTIVE',
    priority: 95,
    configuration: {
      systemKey: 'thr.editorial-compliance',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'editorial_compliance',
      metric: 'editorialCompliance',
      operator: 'EQ',
      value: 'PASS',
      scopeType: 'GLOBAL',
      scopeId: 'all',
      mandatory: 'YES',
      decisionAction: 'REJECT',
      escalationAction: 'REVIEW prohibited/restricted hits',
      overrideAllowed: 'NO for prohibited classes',
      auditRequired: 'YES — editorial rule ids',
      linkedSections: 'editorial-policy,risk-policy',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Content quality gate',
    description: 'Hold packs with incomplete format or channel packaging requirements.',
    status: 'ACTIVE',
    priority: 85,
    configuration: {
      systemKey: 'thr.content-quality',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'content_quality',
      metric: 'contentQuality',
      operator: 'EQ',
      value: 'PACKAGING_COMPLETE',
      scopeType: 'FORMAT',
      scopeId: 'active-formats',
      mandatory: 'YES for publish candidates',
      decisionAction: 'REGENERATE',
      escalationAction: 'REVIEW after second packaging failure',
      overrideAllowed: 'Conditional for draft research packs',
      auditRequired: 'YES — missing packaging fields',
      linkedSections: 'formats,channels,localisation',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'AI model confidence declaration',
    description: 'Do not invent numeric model confidence; require UNMEASURED or measured provenance.',
    status: 'ACTIVE',
    priority: 92,
    configuration: {
      systemKey: 'thr.ai-model-confidence',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'ai_model_confidence',
      metric: 'aiModelConfidence',
      operator: 'IN',
      value: 'MEASURED_WITH_PROVENANCE|UNMEASURED',
      scopeType: 'GLOBAL',
      scopeId: 'all',
      mandatory: 'YES',
      decisionAction: 'REVIEW',
      escalationAction: 'Block fabricated confidence percentages',
      overrideAllowed: 'NO',
      auditRequired: 'YES — confidence provenance note',
      linkedSections: 'source-policy,risk-policy',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Publishing readiness gate',
    description: 'Accept for publish only when channel enablement and localisation kit are ready.',
    status: 'ACTIVE',
    priority: 91,
    configuration: {
      systemKey: 'thr.publishing-readiness',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'publishing_readiness',
      metric: 'publishingReadiness',
      operator: 'EQ',
      value: 'READY',
      scopeType: 'CHANNEL',
      scopeId: 'enabled-channels',
      mandatory: 'YES for publish handoff',
      decisionAction: 'HOLD',
      escalationAction: 'ESCALATE incomplete channel or locale kit',
      overrideAllowed: 'NO for live publish',
      auditRequired: 'YES — channel + locale keys',
      linkedSections: 'channels,localisation,formats',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Approval gate — contested topics',
    description: 'Escalate contested civic, medical, or political packs to mandatory review.',
    status: 'ACTIVE',
    priority: 96,
    configuration: {
      systemKey: 'thr.approval-gate',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'approval_gates',
      metric: 'approvalRequired',
      operator: 'EQ',
      value: 'HUMAN_REVIEW_WHEN_FLAGGED',
      scopeType: 'TOPIC',
      scopeId: 'contested-classes',
      mandatory: 'YES',
      decisionAction: 'ESCALATE',
      escalationAction: 'Route to editorial + risk owners',
      overrideAllowed: 'NO',
      auditRequired: 'YES — reviewer identity + decision',
      linkedSections: 'risk-policy,editorial-policy,objectives',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Package confidence score gate',
    description: 'Strategy package readiness must be READY/ACTIVE before autonomous selection proceeds.',
    status: 'ACTIVE',
    priority: 94,
    configuration: {
      systemKey: 'thr.confidence-scores',
      origin: 'SYSTEM_POLICY',
      ruleCategory: 'confidence_scores',
      metric: 'packageReadiness',
      operator: 'IN',
      value: 'READY|ACTIVE',
      scopeType: 'PACKAGE',
      scopeId: 'strategy-version',
      mandatory: 'YES',
      decisionAction: 'HOLD',
      escalationAction: 'Complete Stage 01 validate/activate first',
      overrideAllowed: 'NO',
      auditRequired: 'YES — version status snapshot',
      linkedSections: 'objectives,domains,taxonomy',
      effectiveFromNote: 'Package effective window',
      effectiveToNote: 'Until superseded',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
