import type { StrategyRecord } from './contracts';

export type PolicySource = StrategyRecord & {
  configuration: Record<string, unknown> & {
    systemKey: string;
    origin: 'SYSTEM_POLICY';
    evidenceClass: string;
    ladderRank: number;
  };
};

/**
 * Evidence ladder — strongest to weakest.
 * Short structured gates only; no fabricated authority scores.
 */
export const SOURCE_POLICY: PolicySource[] = [
  {
    name: 'Rung 1 · Institutional & official',
    description: 'Strongest class for material factual claims.',
    status: 'ACTIVE',
    priority: 98,
    configuration: {
      systemKey: 'src.institutional-primary',
      origin: 'SYSTEM_POLICY',
      evidenceClass: 'primary_institutional',
      ladderRank: 1,
      sourceCategory: 'Primary institutional / official',
      state: 'ALLOWED',
      minimumAuthorityScore: 'Statutory or institutional issuer',
      minimumCorroboration: '1 primary OK; +1 if contested',
      maximumAge: 'Current guidance; historical OK for historical claims',
      geographicRelevance: 'Must match geography policy for place-bound claims',
      primarySourcePreference: 'Instruments, releases, official datasets',
      publicationDateRequired: 'When currency matters',
      retrievalDateRequired: 'Web official pages',
      authorRequired: 'Institution OK; named officer preferred',
      citationRequired: 'Mandatory before production',
      rightsRequired: 'Reuse / fair-quote recorded',
      conflictCheck: 'Disclose material institutional conflicts',
      correctionCheck: 'Prefer updated official versions',
      anonymousRestrictions: 'Leaks ≠ primary official',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Rung 2 · Peer-reviewed scholarly',
    description: 'Research class for scientific and academic claims.',
    status: 'ACTIVE',
    priority: 94,
    configuration: {
      systemKey: 'src.scholarly',
      origin: 'SYSTEM_POLICY',
      evidenceClass: 'scholarly',
      ladderRank: 2,
      sourceCategory: 'Peer-reviewed scholarly',
      state: 'ALLOWED',
      minimumAuthorityScore: 'Peer-reviewed venue or equivalent',
      minimumCorroboration: '2 independent sources for high-impact contests',
      maximumAge: 'Flag outdated consensus when newer reviews exist',
      geographicRelevance: 'Note study population when generalising',
      primarySourcePreference: 'Papers/reviews over press summaries',
      publicationDateRequired: 'Required',
      retrievalDateRequired: 'Preprints / online-only',
      authorRequired: 'Named authors',
      citationRequired: 'DOI when available',
      rightsRequired: 'Publisher licence respected',
      conflictCheck: 'Surface funding conflicts when material',
      correctionCheck: 'Check errata / retractions',
      anonymousRestrictions: 'Anonymous commentary ≠ scholarly primary',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Rung 3 · Reputable journalism',
    description: 'Reportage with stricter corroboration for contested events.',
    status: 'ACTIVE',
    priority: 88,
    configuration: {
      systemKey: 'src.journalism',
      origin: 'SYSTEM_POLICY',
      evidenceClass: 'journalism',
      ladderRank: 3,
      sourceCategory: 'Reputable journalism',
      state: 'CONDITIONAL',
      minimumAuthorityScore: 'Newsroom with corrections policy',
      minimumCorroboration: '2 outlets for contested breaking; 1 for uncontroversial context',
      maximumAge: 'Breaking = recency; evergreen = durable reportage',
      geographicRelevance: 'Local desk preferred for local events',
      primarySourcePreference: 'Reporting that cites primaries / on-record officials',
      publicationDateRequired: 'Required',
      retrievalDateRequired: 'Required',
      authorRequired: 'Byline preferred',
      citationRequired: 'Permalink mandatory',
      rightsRequired: 'Quote limits; no full republication',
      conflictCheck: 'Note ownership conflicts when material',
      correctionCheck: 'Check updates before publish',
      anonymousRestrictions: 'Anonymous sources need elevated corroboration',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Rung 4 · NGO & civil society',
    description: 'Useful field sources — never sole proof for contested civic claims.',
    status: 'ACTIVE',
    priority: 84,
    configuration: {
      systemKey: 'src.civil-society',
      origin: 'SYSTEM_POLICY',
      evidenceClass: 'civil_society',
      ladderRank: 4,
      sourceCategory: 'NGO / civil society / practitioner',
      state: 'CONDITIONAL',
      minimumAuthorityScore: 'Named org + transparent method',
      minimumCorroboration: 'Must pair with institutional or scholarly for contests',
      maximumAge: 'Latest report edition',
      geographicRelevance: 'Operating context must fit claim geography',
      primarySourcePreference: 'Original reports/datasets over social posts',
      publicationDateRequired: 'Required',
      retrievalDateRequired: 'Required',
      authorRequired: 'Organisation named',
      citationRequired: 'Mandatory',
      rightsRequired: 'Licence recorded',
      conflictCheck: 'Disclose advocacy stance in framing',
      correctionCheck: 'Check updates and caveats',
      anonymousRestrictions: 'Beneficiary testimony needs corroboration + harm review',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
  {
    name: 'Rung 5 · Anonymous / social / unverified',
    description: 'Fail-closed — blocked as sole evidence.',
    status: 'ACTIVE',
    priority: 96,
    configuration: {
      systemKey: 'src.anonymous-restricted',
      origin: 'SYSTEM_POLICY',
      evidenceClass: 'restricted_anonymous',
      ladderRank: 5,
      sourceCategory: 'Anonymous / social / unverified',
      state: 'RESTRICTED',
      minimumAuthorityScore: 'Insufficient alone',
      minimumCorroboration: 'Cannot self-corroborate; needs higher rungs',
      maximumAge: 'Viral age irrelevant — verification governs',
      geographicRelevance: 'Geo-tags still require verification',
      primarySourcePreference: 'Tip leads only — not publishable proof',
      publicationDateRequired: 'Capture timestamp if used as lead',
      retrievalDateRequired: 'If archived as investigative lead',
      authorRequired: 'Mark anonymous → escalate',
      citationRequired: 'Label unverified if mentioned',
      rightsRequired: 'No private / non-consensual media',
      conflictCheck: 'Assume unknown motive',
      correctionCheck: 'Withdraw if debunked',
      anonymousRestrictions: 'BLOCKED as sole evidence for material claims',
    },
    effectiveFrom: null,
    effectiveTo: null,
  },
];
