import type { StoryboardWorkspaceModel } from './types';

/**
 * PRESENTATION FIXTURES ONLY.
 * Used to demonstrate layout density and hierarchy. Not production truth.
 * Replace by fetching persisted storyboard state when APIs exist.
 */
export const STORYBOARD_PRESENTATION_FIXTURES: StoryboardWorkspaceModel = {
  provenance: 'presentation',
  summary: {
    storyboardId: 'sb-presentation-001',
    title: 'Harbor Dawn — Sequence Board',
    scriptTitle: 'Harbor Lights',
    sceneCount: 6,
    shotCount: 8,
    approvedShots: 2,
    openContinuityIssues: 2,
    openExceptions: 1,
    assetVersions: 5,
    videoReadyShots: 1,
  },
  autonomy: {
    state: 'UNAVAILABLE',
    currentStage: null,
    correlationId: null,
    updatedAt: null,
    unavailableReason:
      'Storyboard autonomy APIs are not connected. Controls are present for integration and will bind to Start/Pause/Resume/Stop/Emergency Stop once the backend exists.',
  },
  pipeline: [
    { id: 'interpret', label: 'Interpret', status: 'pending' },
    { id: 'decompose', label: 'Decompose', status: 'pending' },
    { id: 'cinematography', label: 'Cinematography', status: 'pending' },
    { id: 'continuity', label: 'Continuity', status: 'pending' },
    { id: 'generate', label: 'Generate', status: 'pending' },
    { id: 'evaluate', label: 'Evaluate', status: 'pending' },
    { id: 'approve', label: 'Approve', status: 'pending' },
    { id: 'version', label: 'Version', status: 'pending' },
    { id: 'handoff', label: 'Video handoff', status: 'pending' },
  ],
  shots: [
    {
      id: 'shot-01',
      sequence: 1,
      shotCode: 'S01-A',
      sceneRef: '01',
      title: 'Establishing harbor',
      description: 'Wide dawn plate across fogged piers; sodium spill from loading cranes.',
      camera: 'Wide',
      lens: '24mm',
      movement: 'Slow push-in',
      durationSec: 4,
      status: 'APPROVED',
      continuityLock: true,
      hasApprovedAsset: true,
      frameLabel: 'Approved plate',
    },
    {
      id: 'shot-02',
      sequence: 2,
      shotCode: 'S01-B',
      sceneRef: '01',
      title: 'Courier silhouette',
      description: 'Medium of courier against mist; rim light from east quay.',
      camera: 'Medium',
      lens: '35mm',
      movement: 'Static',
      durationSec: 3,
      status: 'APPROVED',
      continuityLock: true,
      hasApprovedAsset: true,
      frameLabel: 'Approved plate',
    },
    {
      id: 'shot-03',
      sequence: 3,
      shotCode: 'S02-A',
      sceneRef: '02',
      title: 'Dock detail insert',
      description: 'Close insert on wet rope and stamped crate mark.',
      camera: 'Close',
      lens: '85mm',
      movement: 'Slight tilt',
      durationSec: 2,
      status: 'NEEDS_REVIEW',
      continuityLock: false,
      hasApprovedAsset: false,
      frameLabel: 'Awaiting review',
    },
    {
      id: 'shot-04',
      sequence: 4,
      shotCode: 'S02-B',
      sceneRef: '02',
      title: 'Crane POV',
      description: 'High angle over deck traffic; preserve geographic pier layout.',
      camera: 'High angle',
      lens: '28mm',
      movement: 'Pan left',
      durationSec: 5,
      status: 'BLOCKED',
      continuityLock: false,
      hasApprovedAsset: false,
      frameLabel: 'Blocked',
    },
    {
      id: 'shot-05',
      sequence: 5,
      shotCode: 'S03-A',
      sceneRef: '03',
      title: 'Warehouse threshold',
      description: 'Interior threshold with motivated practicals; no invented signage.',
      camera: 'Medium wide',
      lens: '32mm',
      movement: 'Track forward',
      durationSec: 4,
      status: 'READY',
      continuityLock: true,
      hasApprovedAsset: false,
      frameLabel: 'Ready',
    },
    {
      id: 'shot-06',
      sequence: 6,
      shotCode: 'S03-B',
      sceneRef: '03',
      title: 'Hand-off beat',
      description: 'Two-shot exchange; identity continuity with S01-B wardrobe.',
      camera: 'Two-shot',
      lens: '40mm',
      movement: 'Static',
      durationSec: 3,
      status: 'QUEUED',
      continuityLock: false,
      hasApprovedAsset: false,
      frameLabel: 'Queued',
    },
    {
      id: 'shot-07',
      sequence: 7,
      shotCode: 'S04-A',
      sceneRef: '04',
      title: 'Alley egress',
      description: 'Exit into alley; geography must match prior pier map.',
      camera: 'Wide',
      lens: '27mm',
      movement: 'Handheld light',
      durationSec: 3,
      status: 'PLANNING',
      continuityLock: false,
      hasApprovedAsset: false,
      frameLabel: 'Planning',
    },
    {
      id: 'shot-08',
      sequence: 8,
      shotCode: 'S05-A',
      sceneRef: '05',
      title: 'Dawn resolution',
      description: 'Final still — reflective tone, coherent lighting with S01-A.',
      camera: 'Wide',
      lens: '24mm',
      movement: 'Static',
      durationSec: 5,
      status: 'QUEUED',
      continuityLock: false,
      hasApprovedAsset: false,
      frameLabel: 'Queued',
    },
  ],
  continuityIssues: [
    {
      id: 'ci-01',
      shotId: 'shot-03',
      code: 'WARDROBE_DRIFT',
      severity: 'HIGH',
      status: 'OPEN',
      description: 'Courier sleeve cuff colour diverges from locked reference on S01-B.',
      recommendedAction: 'Re-lock wardrobe package before regeneration.',
    },
    {
      id: 'ci-02',
      shotId: 'shot-04',
      code: 'GEOGRAPHY_CONFLICT',
      severity: 'CRITICAL',
      status: 'OPEN',
      description: 'Crane POV reverses pier axis relative to scene graph.',
      recommendedAction: 'Resolve scene-graph conflict before release.',
    },
  ],
  exceptions: [
    {
      id: 'ex-01',
      shotId: 'shot-04',
      code: 'HUMAN_EXCEPTION_REQUIRED',
      status: 'OPEN',
      title: 'Unsafe geography resolution',
      detail: 'Autonomous planner cannot reconcile pier axis without operator guidance.',
      raisedAt: '2026-07-22T10:14:00.000Z',
    },
  ],
  assets: [
    {
      id: 'av-01',
      shotId: 'shot-01',
      version: 2,
      status: 'APPROVED',
      sha256Preview: '9f2c…a1b3',
      mimeType: 'image/png',
      width: 1280,
      height: 720,
      createdAt: '2026-07-22T09:40:00.000Z',
      videoReady: true,
    },
    {
      id: 'av-02',
      shotId: 'shot-02',
      version: 1,
      status: 'APPROVED',
      sha256Preview: '44ab…91de',
      mimeType: 'image/png',
      width: 1280,
      height: 720,
      createdAt: '2026-07-22T09:52:00.000Z',
      videoReady: false,
    },
    {
      id: 'av-03',
      shotId: 'shot-03',
      version: 1,
      status: 'CANDIDATE',
      sha256Preview: 'c0de…77aa',
      mimeType: 'image/png',
      width: 1280,
      height: 720,
      createdAt: '2026-07-22T10:05:00.000Z',
      videoReady: false,
    },
  ],
  history: [
    {
      id: 'h-01',
      at: '2026-07-22T09:30:00.000Z',
      actor: 'SYSTEM',
      action: 'BOARD_COMPILED',
      detail: 'Shot list compiled from script scenes 01–05 (presentation).',
    },
    {
      id: 'h-02',
      at: '2026-07-22T09:52:00.000Z',
      actor: 'SYSTEM',
      action: 'ASSET_APPROVED',
      detail: 'S01-B AssetVersion v1 approved (presentation).',
    },
    {
      id: 'h-03',
      at: '2026-07-22T10:14:00.000Z',
      actor: 'SYSTEM',
      action: 'EXCEPTION_RAISED',
      detail: 'S02-B geography conflict escalated (presentation).',
    },
  ],
  cinematographyNotes: [
    'Maintain 16:9 cinematic framing across the sequence.',
    'Prefer motivated practicals; avoid invented neon signage.',
    'Identity lock: courier wardrobe package from S01-B.',
    'Geography lock: pier axis from scene graph node harbor.east.',
  ],
};

/** Empty operational model when no storyboard backend data exists. */
export const STORYBOARD_EMPTY_MODEL: StoryboardWorkspaceModel = {
  provenance: 'empty',
  summary: {
    storyboardId: null,
    title: 'Storyboard Engine',
    scriptTitle: null,
    sceneCount: null,
    shotCount: null,
    approvedShots: null,
    openContinuityIssues: null,
    openExceptions: null,
    assetVersions: null,
    videoReadyShots: null,
  },
  autonomy: {
    state: 'UNAVAILABLE',
    currentStage: null,
    correlationId: null,
    updatedAt: null,
    unavailableReason:
      'No persisted storyboard is available. Connect Script Writer handoff and storyboard APIs to activate autonomy.',
  },
  pipeline: [
    { id: 'interpret', label: 'Interpret', status: 'pending' },
    { id: 'decompose', label: 'Decompose', status: 'pending' },
    { id: 'cinematography', label: 'Cinematography', status: 'pending' },
    { id: 'continuity', label: 'Continuity', status: 'pending' },
    { id: 'generate', label: 'Generate', status: 'pending' },
    { id: 'evaluate', label: 'Evaluate', status: 'pending' },
    { id: 'approve', label: 'Approve', status: 'pending' },
    { id: 'version', label: 'Version', status: 'pending' },
    { id: 'handoff', label: 'Video handoff', status: 'pending' },
  ],
  shots: [],
  continuityIssues: [],
  exceptions: [],
  assets: [],
  history: [],
  cinematographyNotes: [],
};
