import type { ComponentType } from 'react';
import {
  Activity,
  AlertTriangle,
  Archive,
  Award,
  Ban,
  BarChart3,
  BookOpen,
  Boxes,
  Brain,
  Camera,
  CheckCircle2,
  Clapperboard,
  ClipboardList,
  Clock3,
  Columns3,
  Compass,
  Cpu,
  Crosshair,
  DollarSign,
  Eye,
  FileCheck2,
  FileSearch,
  FileText,
  Film,
  FlaskConical,
  Folder,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitCompare,
  Globe,
  History,
  Image as ImageIcon,
  Landmark,
  Layers3,
  LayoutTemplate,
  LineChart,
  Link2,
  ListChecks,
  Map,
  MapPin,
  MessageSquare,
  Move,
  Package,
  Play,
  RefreshCw,
  Route,
  Scan,
  ScanLine,
  Scissors,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Target,
  Users,
  Video,
  Workflow,
  Wrench,
} from 'lucide-react';
import type { LifecycleIconName } from '@/apps/web/config/lifecycle-navigation';

const ICONS: Record<LifecycleIconName, ComponentType<{ size?: number; className?: string; 'aria-hidden'?: boolean }>> = {
  compass: Compass,
  folder: Folder,
  fileText: FileText,
  layers: Layers3,
  scan: Scan,
  eye: Eye,
  alertTriangle: AlertTriangle,
  fileSearch: FileSearch,
  search: Search,
  bookOpen: BookOpen,
  clipboardList: ClipboardList,
  users: Users,
  mapPin: MapPin,
  clock: Clock3,
  globe: Globe,
  image: ImageIcon,
  shield: ShieldCheck,
  checkCircle: CheckCircle2,
  gitBranch: GitBranch,
  scissors: Scissors,
  camera: Camera,
  layout: LayoutTemplate,
  sun: Sun,
  move: Move,
  link: Link2,
  clapperboard: Clapperboard,
  listChecks: ListChecks,
  sparkles: Sparkles,
  ban: Ban,
  crosshair: Crosshair,
  cpu: Cpu,
  route: Route,
  workflow: Workflow,
  target: Target,
  dollarSign: DollarSign,
  play: Play,
  history: History,
  boxes: Boxes,
  gallery: ImageIcon,
  fileCheck: FileCheck2,
  scanLine: ScanLine,
  brain: Brain,
  activity: Activity,
  bug: AlertTriangle,
  columns: Columns3,
  award: Award,
  map: Map,
  landmark: Landmark,
  refreshCw: RefreshCw,
  wrench: Wrench,
  archive: Archive,
  package: Package,
  gitCommit: GitCommitHorizontal,
  film: Film,
  video: Video,
  send: Send,
  barChart: BarChart3,
  lineChart: LineChart,
  gauge: Gauge,
  messageSquare: MessageSquare,
  flask: FlaskConical,
  gitCompare: GitCompare,
  settings: Settings,
  scrollText: ScrollText,
};

export function LifecycleIcon({
  name,
  size = 16,
  className,
}: {
  name: LifecycleIconName;
  size?: number;
  className?: string;
}) {
  const Icon = ICONS[name] || Compass;
  return <Icon size={size} className={className} aria-hidden />;
}
