export const ideaQualificationNavigation = [
  { id: 'iq-overview', label: 'Overview', href: '/ideas' },
  { id: 'iq-intake', label: 'Intelligence Intake', href: '/ideas/intake' },
  { id: 'iq-candidate-pool', label: 'Candidate Pool', href: '/ideas/candidate-pool' },
  { id: 'iq-evidence', label: 'Evidence Sufficiency', href: '/ideas/evidence' },
  { id: 'iq-strategic-fit', label: 'Strategic Fit', href: '/ideas/strategic-fit' },
  { id: 'iq-audience-value', label: 'Audience Value', href: '/ideas/audience-value' },
  { id: 'iq-originality', label: 'Originality Analysis', href: '/ideas/originality' },
  { id: 'iq-duplicates', label: 'Duplicate Detection', href: '/ideas/duplicates' },
  { id: 'iq-feasibility', label: 'Production Feasibility', href: '/ideas/feasibility' },
  { id: 'iq-visual-potential', label: 'Visual Potential', href: '/ideas/visual-potential' },
  { id: 'iq-risk', label: 'Risk & Sensitivity', href: '/ideas/risk' },
  { id: 'iq-scoring', label: 'Qualification Scoring', href: '/ideas/scoring' },
  { id: 'iq-gates', label: 'Mandatory Gates', href: '/ideas/gates' },
  { id: 'iq-ranking', label: 'Qualified Ranking', href: '/ideas/ranking' },
  { id: 'iq-decisions', label: 'Decision Register', href: '/ideas/decisions' },
  { id: 'iq-selected', label: 'Selected Ideas', href: '/ideas/selected-ideas' },
  { id: 'iq-handoffs', label: 'Project Handoffs', href: '/ideas/handoffs' },
  { id: 'iq-failures', label: 'Failure & Recovery', href: '/ideas/failures' },
  { id: 'iq-audit', label: 'Qualification Audit', href: '/ideas/audit' },
] as const;
