export const researchEvidenceNavigation = [
  { id: 're-overview', label: 'Overview', href: '/research' },
  { id: 're-intake', label: 'Qualified Project Intake', href: '/research/intake' },
  { id: 're-brief', label: 'Research Brief', href: '/research/research-brief' },
  { id: 're-questions', label: 'Research Questions', href: '/research/questions' },
  { id: 're-discovery', label: 'Source Discovery', href: '/research/source-discovery' },
  { id: 're-library', label: 'Source Library', href: '/research/source-library' },
  { id: 're-evaluation', label: 'Source Evaluation', href: '/research/source-evaluation' },
  { id: 're-claims', label: 'Claim Register', href: '/research/claims' },
  { id: 're-evidence-map', label: 'Claim–Evidence Map', href: '/research/evidence-map' },
  { id: 're-corroboration', label: 'Corroboration', href: '/research/corroboration' },
  { id: 're-contradictions', label: 'Contradictions', href: '/research/contradictions' },
  { id: 're-fact-checking', label: 'Fact Verification', href: '/research/fact-checking' },
  { id: 're-citations', label: 'Citations & Provenance', href: '/research/citations' },
  { id: 're-rights', label: 'Rights & Licensing', href: '/research/rights' },
  {
    id: 're-regional',
    label: 'Regional Authenticity',
    href: '/research/regional-authenticity',
  },
  { id: 're-risk', label: 'Research Risk', href: '/research/risk' },
  { id: 're-dossier', label: 'Research Dossier', href: '/research/dossier' },
  { id: 're-handoffs', label: 'Script Handoffs', href: '/research/handoffs' },
  { id: 're-failures', label: 'Failure & Recovery', href: '/research/failures' },
  { id: 're-audit', label: 'Research Audit', href: '/research/audit' },
] as const;
