import type { SectionKey } from '@/lib/strategy/contracts';

export const sections: Array<{
  key: SectionKey;
  title: string;
  description: string;
  fields: string[];
}> = [
  {
    key: 'objectives',
    title: 'Strategic Objectives',
    description: 'Define measurable outcomes and strategic priorities.',
    fields: [
      'name',
      'description',
      'category',
      'desiredOutcome',
      'targetMetric',
      'baselineValue',
      'targetValue',
      'measurementPeriod',
      'startDate',
      'endDate',
      'applicableFields',
      'applicableAudiences',
      'regions',
      'channels',
      'formats',
      'dependencies',
      'constraints',
      'successCriteria',
    ],
  },
  {
    key: 'domains',
    title: 'Field & Domain Profiles',
    description: 'Control permitted knowledge fields and domain coverage.',
    fields: [
      'fieldName',
      'domainName',
      'description',
      'rationale',
      'coverageStatus',
      'allowedState',
      'countries',
      'audiences',
      'formats',
      'evidenceRequirement',
      'sensitivity',
      'seasonalRelevance',
      'frequencyLimit',
      'authorityRequirement',
      'parentDomain',
    ],
  },
  {
    key: 'taxonomy',
    title: 'Subject & Subfield Taxonomy',
    description: 'Maintain the controlled subject hierarchy.',
    fields: [
      'nodeType',
      'name',
      'parentId',
      'keywords',
      'synonyms',
      'relatedConcepts',
      'exclusions',
      'geographicVariations',
      'historicalTerms',
      'localTerminology',
      'knowledgeEntityId',
    ],
  },
  {
    key: 'geographies',
    title: 'Country & Regional Profiles',
    description: 'Configure authentic geographic and cultural direction.',
    fields: [
      'country',
      'region',
      'state',
      'supportedLanguages',
      'culturalContext',
      'historicalContext',
      'representationRules',
      'sensitiveSubjects',
      'restrictedSubjects',
      'localSourceRequirements',
      'localTerminology',
      'authenticityRules',
      'demographics',
      'eventsAndSeasons',
      'timeZone',
      'visualRepresentation',
    ],
  },
  {
    key: 'audiences',
    title: 'Audience Profiles',
    description: 'Describe primary, secondary and excluded audiences.',
    fields: [
      'name',
      'description',
      'ageRange',
      'knowledgeLevel',
      'interestGroup',
      'countryRegion',
      'languages',
      'accessibilityNeeds',
      'informationNeeds',
      'questions',
      'preferredTone',
      'formats',
      'duration',
      'channels',
      'deviceBandwidth',
      'viewingBehaviour',
      'engagementObjectives',
      'sensitivityTolerance',
      'learningOutcomes',
      'successMetrics',
    ],
  },
  {
    key: 'editorial-policy',
    title: 'Editorial & Brand Policy',
    description: 'Set voice, factuality, representation and disclosure rules.',
    fields: [
      'brandPurpose',
      'editorialMission',
      'voiceAndTone',
      'documentaryStyle',
      'narrativePrinciples',
      'factualityRules',
      'neutrality',
      'representationStandards',
      'culturalSensitivity',
      'prohibitedContent',
      'restrictedContent',
      'disclosures',
      'aiDisclosure',
      'quotationRules',
      'correctionPolicy',
      'citationStandards',
      'brandingRules',
      'reviewRequirements',
    ],
  },
  {
    key: 'formats',
    title: 'Content Format Strategy',
    description: 'Define production and accessibility requirements by format.',
    fields: [
      'format',
      'purpose',
      'minimumDuration',
      'maximumDuration',
      'narrativeStructure',
      'evidenceDepth',
      'visualRequirements',
      'audioRequirements',
      'aspectRatios',
      'captions',
      'accessibility',
      'fields',
      'audiences',
      'channels',
      'costBoundary',
      'frequency',
    ],
  },
  {
    key: 'channels',
    title: 'Channel Strategy',
    description: 'Separate strategic enablement from provider availability.',
    fields: [
      'channel',
      'enabled',
      'objective',
      'audiences',
      'formats',
      'aspectRatios',
      'durationLimits',
      'resolutionCodec',
      'metadataRequirements',
      'thumbnailRequirements',
      'captionRequirements',
      'cadence',
      'publishingWindows',
      'geographicTargeting',
      'restrictions',
      'providerAvailability',
      'automationPermissions',
      'successMetrics',
    ],
  },
  {
    key: 'localisation',
    title: 'Language & Localisation',
    description: 'Configure cultural adaptation beyond literal translation.',
    fields: [
      'primaryLanguage',
      'secondaryLanguages',
      'countryMappings',
      'translationRules',
      'transliterationRules',
      'accentPreferences',
      'pronunciationDictionary',
      'localTerminology',
      'dateNumberFormats',
      'measurementUnits',
      'captions',
      'subtitleLanguages',
      'readingLevel',
      'culturalAdaptation',
      'regionalVariants',
      'machineTranslationThreshold',
      'humanReview',
    ],
  },
  {
    key: 'source-policy',
    title: 'Evidence & Source Policy',
    description: 'Define authority, corroboration, recency and rights rules.',
    fields: [
      'sourceCategory',
      'state',
      'minimumAuthorityScore',
      'minimumCorroboration',
      'maximumAge',
      'geographicRelevance',
      'primarySourcePreference',
      'publicationDateRequired',
      'retrievalDateRequired',
      'authorRequired',
      'citationRequired',
      'rightsRequired',
      'conflictCheck',
      'correctionCheck',
      'anonymousRestrictions',
    ],
  },
  {
    key: 'risk-policy',
    title: 'Risk & Sensitivity Policy',
    description: 'Define blocking, escalation and remediation rules.',
    fields: [
      'category',
      'severity',
      'likelihood',
      'fields',
      'countries',
      'audiences',
      'formats',
      'channels',
      'detectionMethod',
      'automaticAction',
      'escalationRequired',
      'blockingThreshold',
      'reviewRequired',
      'remediation',
      'closureEvidence',
    ],
  },
  {
    key: 'selection-thresholds',
    title: 'Autonomous Selection Thresholds',
    description: 'Set absolute gates and scoped rule overrides.',
    fields: [
      'metric',
      'operator',
      'value',
      'scopeType',
      'scopeId',
      'priority',
      'mandatory',
      'effectiveFrom',
      'effectiveTo',
    ],
  },
  {
    key: 'portfolio',
    title: 'Portfolio Allocation',
    description: 'Balance coverage, diversity, capacity and budget.',
    fields: [
      'dimension',
      'dimensionValue',
      'minimumAllocation',
      'maximumAllocation',
      'targetPercentage',
      'timeWindow',
      'frequencyCap',
      'diversityRequirement',
      'repetitionLimit',
      'capacityLimit',
      'budgetLimit',
    ],
  },
];

export const getSection = (key: string) => sections.find((section) => section.key === key);
