import {closeDb,getDb,sql} from './index.js';
const email=process.env.BOOTSTRAP_ADMIN_EMAIL||'pipsengine@gmail.com';
try{
 const db=await getDb(); const base=await db.request().input('email',sql.NVarChar(320),email).query(`SELECT TOP 1 u.UserId,w.WorkspaceId FROM dbo.Users u CROSS JOIN dbo.Workspaces w WHERE u.Email=@email AND w.Slug='cacsms-cinemas'`); const row=base.recordset[0]; if(!row) throw new Error('Run Module 01 bootstrap first.');
 const project=(await db.request().input('ws',sql.UniqueIdentifier,row.WorkspaceId).query(`SELECT TOP 1 ContentProjectId,TargetAudience,TargetCountriesJson,Language,PlannedDurationSeconds,AspectRatio,CreativeDirection,Objective FROM dbo.ContentProjects WHERE WorkspaceId=@ws AND ContentCode='CAC-2026-000124'`)).recordset[0]; if(!project) throw new Error('Run Module 03 bootstrap first.');
 await db.request().input('pid',sql.UniqueIdentifier,project.ContentProjectId).input('uid',sql.UniqueIdentifier,row.UserId).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ContentBriefs WHERE ContentProjectId=@pid) INSERT dbo.ContentBriefs(ContentProjectId,CurrentVersionNumber,Status,PrimaryObjective,SecondaryObjectivesJson,AudienceSummary,AudienceAgeRange,AudienceKnowledgeLevel,AudienceInterestsJson,TargetCountriesJson,DistributionPlatformsJson,CreativeDirection,StoryApproach,VoiceStyle,VisualStyle,DesiredDurationSeconds,AspectRatio,Language,CallToAction,MonetizationObjective,ContentRestrictions,RequiredElements,AvoidElements,ReferenceCreators,ResearchFocus,SuccessDefinition,Notes,CreatedByUserId) VALUES(@pid,2,'IN_REVIEW','Educate & grow subscribers','["Increase average view duration","Build global audience trust","Create reusable short-form derivatives"]','Global English-speaking viewers curious about technology and the hidden AI systems shaping everyday life.','16–45','General audience','["AI","technology","future","everyday life"]','["Global","United States","United Kingdom","Canada"]','["YouTube","YouTube Shorts","TikTok","Instagram Reels"]','Cinematic documentary','Curiosity-led reveal','Neutral Nigerian English; calm, confident, curious, globally understandable.','Premium cinematic technology documentary, photorealistic visuals, restrained interface graphics, realistic humans.',540,'16:9','English','Subscribe for more stories about the technology quietly changing everyday life.','Maximise long-form watch time, subscriber growth and reusable cross-platform derivatives.','Do not present speculation as fact. Avoid fabricated statistics, fake quotes, unsupported claims or identifiable private information.','Strong first 20-second hook; clear factual evidence; global examples; practical takeaway; natural CTA.','Clickbait without payoff; over-American phrasing; robotic narration; cluttered on-screen text; repetitive stock-like visuals.','Vox, Veritasium, BBC Earth, National Geographic, RealLifeLore','Identify invisible AI systems already used in consumer life; verify each example with authoritative sources; surface surprising but defensible facts.','Audience should understand at least five everyday AI systems, maintain strong retention through the midpoint, and leave with a clear reason to subscribe.','Module 04 seed brief prepared for review.',@uid)`);
 const brief=(await db.request().input('pid',sql.UniqueIdentifier,project.ContentProjectId).query(`SELECT ContentBriefId FROM dbo.ContentBriefs WHERE ContentProjectId=@pid`)).recordset[0];
 const snapshot=JSON.stringify({primaryObjective:'Educate & grow subscribers',audience:'Global English-speaking viewers, 16–45',platforms:['YouTube','YouTube Shorts','TikTok','Instagram Reels'],creativeDirection:'Cinematic documentary',voiceStyle:'Neutral Nigerian English',visualStyle:'Premium cinematic technology documentary',duration:540,aspectRatio:'16:9',language:'English'});
 for(const v of [{n:1,s:'SUPERSEDED',c:'Initial strategy translated from project initiation.'},{n:2,s:'IN_REVIEW',c:'Expanded audience, platform, voice, safety and success criteria.'}]) await db.request().input('bid',sql.UniqueIdentifier,brief.ContentBriefId).input('n',sql.Int,v.n).input('s',sql.NVarChar(30),v.s).input('snap',sql.NVarChar(sql.MAX),snapshot).input('c',sql.NVarChar(1000),v.c).input('uid',sql.UniqueIdentifier,row.UserId).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ContentBriefVersions WHERE ContentBriefId=@bid AND VersionNumber=@n) INSERT dbo.ContentBriefVersions(ContentBriefId,VersionNumber,Status,SnapshotJson,ChangeSummary,CreatedByUserId) VALUES(@bid,@n,@s,@snap,@c,@uid)`);
 const segments=[['Primary global viewer','Technology-curious viewers who want clear, cinematic explanations of how AI affects daily life.','18–44','["Global","United States","United Kingdom","Canada"]','["AI","technology","future"]','["Understand complex topics simply","Learn surprising real-world examples"]',1],['Student & young adult','Younger viewers discovering AI through social platforms and explainers.','15–24','["Global","Nigeria","United Kingdom"]','["education","AI","social video"]','["Fast clarity","Visual storytelling","Shareable facts"]',2]];
 for(const s of segments) await db.request().input('bid',sql.UniqueIdentifier,brief.ContentBriefId).input('name',sql.NVarChar(150),s[0]).input('desc',sql.NVarChar(1000),s[1]).input('age',sql.NVarChar(60),s[2]).input('markets',sql.NVarChar(sql.MAX),s[3]).input('interests',sql.NVarChar(sql.MAX),s[4]).input('needs',sql.NVarChar(sql.MAX),s[5]).input('ord',sql.Int,s[6] as number).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ContentBriefAudienceSegments WHERE ContentBriefId=@bid AND SegmentName=@name) INSERT dbo.ContentBriefAudienceSegments(ContentBriefId,SegmentName,Description,AgeRange,MarketsJson,InterestsJson,NeedsJson,PriorityOrder) VALUES(@bid,@name,@desc,@age,@markets,@interests,@needs,@ord)`);
 const platforms=[['YouTube','Long Form',1,540,'16:9','Watch time + subscribers','Premium master video; chapters; strong thumbnail/title package.'],['YouTube Shorts','Short Form',0,60,'9:16','Reach new viewers','Extract strongest surprising fact with standalone hook.'],['TikTok','Short Form',0,45,'9:16','Discovery','Fast first-frame hook and native caption pacing.'],['Instagram Reels','Short Form',0,60,'9:16','Reach + saves','Visually polished derivative with concise CTA.']];
 for(const p of platforms) await db.request().input('bid',sql.UniqueIdentifier,brief.ContentBriefId).input('platform',sql.NVarChar(60),p[0]).input('format',sql.NVarChar(80),p[1]).input('primary',sql.Bit,p[2] as number).input('duration',sql.Int,p[3] as number).input('ratio',sql.NVarChar(20),p[4]).input('goal',sql.NVarChar(500),p[5]).input('notes',sql.NVarChar(1000),p[6]).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ContentBriefPlatformStrategies WHERE ContentBriefId=@bid AND Platform=@platform AND ContentFormat=@format) INSERT dbo.ContentBriefPlatformStrategies(ContentBriefId,Platform,ContentFormat,IsPrimary,TargetDurationSeconds,AspectRatio,PlatformGoal,PackagingNotes) VALUES(@bid,@platform,@format,@primary,@duration,@ratio,@goal,@notes)`);
 const metrics=[['HOOK_RETENTION','30-second retention',70,'%','Target a strong opening hold.'],['AVG_VIEW_DURATION','Average view duration',4.5,'minutes','Primary long-form quality indicator.'],['CTR','Thumbnail/title CTR',6.5,'%','Evaluate packaging effectiveness.'],['SUB_CONVERSION','Subscriber conversion',1.8,'%','Measure audience growth efficiency.']];
 for(const m of metrics) await db.request().input('bid',sql.UniqueIdentifier,brief.ContentBriefId).input('key',sql.NVarChar(80),m[0]).input('name',sql.NVarChar(150),m[1]).input('value',sql.Decimal(18,4),m[2] as number).input('unit',sql.NVarChar(50),m[3]).input('notes',sql.NVarChar(500),m[4]).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ContentBriefSuccessMetrics WHERE ContentBriefId=@bid AND MetricKey=@key) INSERT dbo.ContentBriefSuccessMetrics(ContentBriefId,MetricKey,DisplayName,TargetValue,TargetUnit,Notes) VALUES(@bid,@key,@name,@value,@unit,@notes)`);
 console.log('Module 04 strategy & content brief bootstrap complete.');
}finally{await closeDb()}
