import type { VideoAssemblyWorkspaceModel } from './types';

/**
 * PRESENTATION FIXTURES ONLY.
 * Illustrate Image-to-Video readiness layout. Not production truth.
 */
export const VIDEO_PRESENTATION_FIXTURES: VideoAssemblyWorkspaceModel = {
  provenance: 'presentation',
  summary: {
    sequenceId: 'vid-presentation-001',
    title: 'Harbor Dawn — Video Readiness',
    storyboardTitle: 'Harbor Dawn — Sequence Board',
    totalClips: 6,
    readyClips: 3,
    blockedClips: 1,
    staleFrames: 1,
    openExceptions: 1,
    estimatedDurationSec: 21,
  },
  autonomy: {
    state: 'UNAVAILABLE',
    currentStage: null,
    correlationId: null,
    updatedAt: null,
    unavailableReason:
      'Video assembly autonomy APIs are not connected. Controls will bind to Start/Pause/Resume/Stop/Emergency Stop once readiness, AssetVersion, and Scene Video Generator contracts exist.',
  },
  pipeline: [
    { id: 'ingest', label: 'Ingest frames', status: 'pending' },
    { id: 'evaluate', label: 'Readiness eval', status: 'pending' },
    { id: 'lock', label: 'Lock assets', status: 'pending' },
    { id: 'sync', label: 'Frame sync', status: 'pending' },
    { id: 'timeline', label: 'Build timeline', status: 'pending' },
    { id: 'generate', label: 'Scene video', status: 'pending' },
    { id: 'qa', label: 'Video QA', status: 'pending' },
    { id: 'deliver', label: 'Deliver', status: 'pending' },
  ],
  clips: [
    {
      id: 'clip-01',
      order: 1,
      shotCode: 'S01-A',
      sceneRef: '01',
      title: 'Establishing harbor',
      kind: 'still',
      durationSec: 4,
      readiness: 'READY',
      assetVersionId: 'av-01',
      assetShaPreview: '9f2c…a1b3',
      continuitySafe: true,
      videoReady: true,
      notes: 'Approved AssetVersion locked; ready for timeline hold.',
    },
    {
      id: 'clip-02',
      order: 2,
      shotCode: 'S01-B',
      sceneRef: '01',
      title: 'Courier silhouette',
      kind: 'still',
      durationSec: 3,
      readiness: 'READY',
      assetVersionId: 'av-02',
      assetShaPreview: '44ab…91de',
      continuitySafe: true,
      videoReady: true,
      notes: 'Continuity lock verified against wardrobe package.',
    },
    {
      id: 'clip-03',
      order: 3,
      shotCode: 'S02-A',
      sceneRef: '02',
      title: 'Dock detail insert',
      kind: 'still',
      durationSec: 2,
      readiness: 'NEEDS_REVIEW',
      assetVersionId: 'av-03',
      assetShaPreview: 'c0de…77aa',
      continuitySafe: false,
      videoReady: false,
      notes: 'Candidate only — wardrobe drift blocks video-ready flag.',
    },
    {
      id: 'clip-04',
      order: 4,
      shotCode: 'S02-B',
      sceneRef: '02',
      title: 'Crane POV',
      kind: 'still',
      durationSec: 5,
      readiness: 'BLOCKED',
      assetVersionId: null,
      assetShaPreview: null,
      continuitySafe: false,
      videoReady: false,
      notes: 'No permanent AssetVersion; geography exception open.',
    },
    {
      id: 'clip-05',
      order: 5,
      shotCode: 'S03-A',
      sceneRef: '03',
      title: 'Warehouse threshold',
      kind: 'hold',
      durationSec: 4,
      readiness: 'READY',
      assetVersionId: 'av-05',
      assetShaPreview: '11ee…90f2',
      continuitySafe: true,
      videoReady: true,
      notes: 'Ready still with extended hold for narration.',
    },
    {
      id: 'clip-06',
      order: 6,
      shotCode: 'S03-B',
      sceneRef: '03',
      title: 'Hand-off beat',
      kind: 'still',
      durationSec: 3,
      readiness: 'STALE',
      assetVersionId: 'av-06',
      assetShaPreview: '88aa…12cd',
      continuitySafe: true,
      videoReady: false,
      notes: 'Storyboard frame updated after lock — re-evaluation required.',
    },
  ],
  readinessChecks: [
    {
      id: 'rc-01',
      clipId: 'clip-01',
      code: 'ASSET_VERSION_PERMANENT',
      passed: true,
      severity: 'CRITICAL',
      detail: 'Permanent AssetVersion reference present.',
    },
    {
      id: 'rc-02',
      clipId: 'clip-01',
      code: 'CONTINUITY_SAFE',
      passed: true,
      severity: 'HIGH',
      detail: 'No open continuity violations on linked shot.',
    },
    {
      id: 'rc-03',
      clipId: 'clip-03',
      code: 'CONTINUITY_SAFE',
      passed: false,
      severity: 'HIGH',
      detail: 'Wardrobe drift unresolved on S02-A.',
    },
    {
      id: 'rc-04',
      clipId: 'clip-04',
      code: 'ASSET_VERSION_PERMANENT',
      passed: false,
      severity: 'CRITICAL',
      detail: 'Missing permanent AssetVersion reference.',
    },
    {
      id: 'rc-05',
      clipId: 'clip-06',
      code: 'FRAME_FRESHNESS',
      passed: false,
      severity: 'MEDIUM',
      detail: 'Storyboard frame update received after asset lock.',
    },
  ],
  assets: [
    {
      id: 'lar-01',
      clipId: 'clip-01',
      assetVersionId: 'av-01',
      sha256Preview: '9f2c…a1b3',
      mimeType: 'image/png',
      width: 1280,
      height: 720,
      permanent: true,
      videoReady: true,
      lockedAt: '2026-07-22T09:40:00.000Z',
    },
    {
      id: 'lar-02',
      clipId: 'clip-02',
      assetVersionId: 'av-02',
      sha256Preview: '44ab…91de',
      mimeType: 'image/png',
      width: 1280,
      height: 720,
      permanent: true,
      videoReady: true,
      lockedAt: '2026-07-22T09:52:00.000Z',
    },
    {
      id: 'lar-03',
      clipId: 'clip-05',
      assetVersionId: 'av-05',
      sha256Preview: '11ee…90f2',
      mimeType: 'image/png',
      width: 1280,
      height: 720,
      permanent: true,
      videoReady: true,
      lockedAt: '2026-07-22T10:20:00.000Z',
    },
  ],
  frameEvents: [
    {
      id: 'fe-01',
      at: '2026-07-22T10:18:00.000Z',
      type: 'STORYBOARD_FRAME_UPDATED',
      shotCode: 'S03-B',
      detail: 'Storyboard published a new frame revision for S03-B.',
      correlationId: 'corr-presentation-fe-01',
    },
    {
      id: 'fe-02',
      at: '2026-07-22T10:19:00.000Z',
      type: 'READINESS_REEVALUATED',
      shotCode: 'S03-B',
      detail: 'Clip marked STALE pending re-lock of AssetVersion.',
      correlationId: 'corr-presentation-fe-02',
    },
    {
      id: 'fe-03',
      at: '2026-07-22T09:52:00.000Z',
      type: 'ASSET_VERSION_LOCKED',
      shotCode: 'S01-B',
      detail: 'Permanent AssetVersion av-02 locked for video handoff.',
      correlationId: 'corr-presentation-fe-03',
    },
  ],
  generators: [
    {
      id: 'gen-scene',
      name: 'Scene Video Generator',
      status: 'UNAVAILABLE',
      contract: 'SceneVideoGenerator.v1',
      lastMessage: 'Contract registered in UI only — backend generator not connected.',
    },
    {
      id: 'gen-timeline',
      name: 'Timeline Assembler',
      status: 'UNAVAILABLE',
      contract: 'TimelineAssembly.v1',
      lastMessage: 'Awaiting ready clip set and duration map.',
    },
  ],
  exceptions: [
    {
      id: 'vx-01',
      clipId: 'clip-04',
      code: 'HUMAN_EXCEPTION_REQUIRED',
      status: 'OPEN',
      title: 'Blocked geography prevents video handoff',
      detail: 'S02-B has no approved AssetVersion while a critical geography continuity exception remains open.',
      raisedAt: '2026-07-22T10:14:00.000Z',
    },
  ],
  history: [
    {
      id: 'vh-01',
      at: '2026-07-22T09:55:00.000Z',
      actor: 'SYSTEM',
      action: 'READINESS_SCAN',
      detail: 'Presentation scan of linked storyboard frames (not live).',
    },
    {
      id: 'vh-02',
      at: '2026-07-22T10:14:00.000Z',
      actor: 'SYSTEM',
      action: 'EXCEPTION_RAISED',
      detail: 'S02-B blocked from video pipeline (presentation).',
    },
  ],
};

export const VIDEO_EMPTY_MODEL: VideoAssemblyWorkspaceModel = {
  provenance: 'empty',
  summary: {
    sequenceId: null,
    title: 'Image-to-Video Readiness',
    storyboardTitle: null,
    totalClips: null,
    readyClips: null,
    blockedClips: null,
    staleFrames: null,
    openExceptions: null,
    estimatedDurationSec: null,
  },
  autonomy: {
    state: 'UNAVAILABLE',
    currentStage: null,
    correlationId: null,
    updatedAt: null,
    unavailableReason:
      'No video sequence is available. Connect approved AssetVersions, storyboard frame events, and Scene Video Generator contracts to activate.',
  },
  pipeline: [
    { id: 'ingest', label: 'Ingest frames', status: 'pending' },
    { id: 'evaluate', label: 'Readiness eval', status: 'pending' },
    { id: 'lock', label: 'Lock assets', status: 'pending' },
    { id: 'sync', label: 'Frame sync', status: 'pending' },
    { id: 'timeline', label: 'Build timeline', status: 'pending' },
    { id: 'generate', label: 'Scene video', status: 'pending' },
    { id: 'qa', label: 'Video QA', status: 'pending' },
    { id: 'deliver', label: 'Deliver', status: 'pending' },
  ],
  clips: [],
  readinessChecks: [],
  assets: [],
  frameEvents: [],
  generators: [],
  exceptions: [],
  history: [],
};
