IF COL_LENGTH('dbo.Users','LastLoginAt') IS NULL ALTER TABLE dbo.Users ADD LastLoginAt DATETIME2 NULL;
GO
IF COL_LENGTH('dbo.Users','MfaEnabled') IS NULL ALTER TABLE dbo.Users ADD MfaEnabled BIT NOT NULL CONSTRAINT DF_Users_MfaEnabled DEFAULT 0;
GO
IF COL_LENGTH('dbo.WorkspaceUsers','MembershipStatus') IS NULL ALTER TABLE dbo.WorkspaceUsers ADD MembershipStatus NVARCHAR(30) NOT NULL CONSTRAINT DF_WorkspaceUsers_Status DEFAULT 'ACTIVE';
GO
IF OBJECT_ID('dbo.Permissions','U') IS NULL BEGIN
 CREATE TABLE dbo.Permissions(PermissionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Permissions PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PermissionKey NVARCHAR(120) NOT NULL UNIQUE,DisplayName NVARCHAR(180) NOT NULL,Description NVARCHAR(500) NULL,Category NVARCHAR(80) NOT NULL);
END;
GO
IF OBJECT_ID('dbo.RolePermissions','U') IS NULL BEGIN
 CREATE TABLE dbo.RolePermissions(RoleId UNIQUEIDENTIFIER NOT NULL,PermissionId UNIQUEIDENTIFIER NOT NULL,CONSTRAINT PK_RolePermissions PRIMARY KEY(RoleId,PermissionId),CONSTRAINT FK_RolePermissions_Role FOREIGN KEY(RoleId) REFERENCES dbo.Roles(RoleId),CONSTRAINT FK_RolePermissions_Permission FOREIGN KEY(PermissionId) REFERENCES dbo.Permissions(PermissionId));
END;
GO
IF OBJECT_ID('dbo.PasswordResetTokens','U') IS NULL BEGIN
 CREATE TABLE dbo.PasswordResetTokens(TokenId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_PasswordResetTokens PRIMARY KEY DEFAULT NEWSEQUENTIALID(),UserId UNIQUEIDENTIFIER NOT NULL,TokenHash NVARCHAR(200) NOT NULL UNIQUE,ExpiresAt DATETIME2 NOT NULL,UsedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Reset_Created DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_Reset_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId));
END;
GO
IF OBJECT_ID('dbo.UserSessions','U') IS NULL BEGIN
 CREATE TABLE dbo.UserSessions(SessionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_UserSessions PRIMARY KEY DEFAULT NEWSEQUENTIALID(),UserId UNIQUEIDENTIFIER NOT NULL,RefreshTokenHash NVARCHAR(300) NULL,IpAddress NVARCHAR(64) NULL,UserAgent NVARCHAR(500) NULL,ExpiresAt DATETIME2 NOT NULL,RevokedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Session_Created DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_Session_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId));
END;
GO
IF OBJECT_ID('dbo.AuditEvents','U') IS NULL BEGIN
 CREATE TABLE dbo.AuditEvents(AuditEventId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AuditEvents PRIMARY KEY,WorkspaceId UNIQUEIDENTIFIER NULL,UserId UNIQUEIDENTIFIER NULL,Action NVARCHAR(100) NOT NULL,EntityType NVARCHAR(100) NOT NULL,EntityId NVARCHAR(100) NULL,MetadataJson NVARCHAR(MAX) NULL,IpAddress NVARCHAR(64) NULL,CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Audit_Created DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_Audit_Workspace FOREIGN KEY(WorkspaceId) REFERENCES dbo.Workspaces(WorkspaceId),CONSTRAINT FK_Audit_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId));
 CREATE INDEX IX_AuditEvents_Workspace_Created ON dbo.AuditEvents(WorkspaceId,CreatedAt DESC);
END;
GO
