IF OBJECT_ID('dbo.ResearchPacks','U') IS NULL CREATE TABLE dbo.ResearchPacks(
 ResearchPackId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
 ContentProjectId UNIQUEIDENTIFIER NOT NULL UNIQUE,
 SourceOpportunityId UNIQUEIDENTIFIER NOT NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT',
 CurrentVersionNumber INT NOT NULL DEFAULT 0,
 ApprovedVersionId UNIQUEIDENTIFIER NULL,
 ResearchObjective NVARCHAR(1500) NULL,
 ResearchSummary NVARCHAR(MAX) NULL,
 ExecutiveFindings NVARCHAR(MAX) NULL,
 NarrativeAngles NVARCHAR(MAX) NULL,
 ProductionNotes NVARCHAR(MAX) NULL,
 SensitivitySummary NVARCHAR(MAX) NULL,
 ResearchProvider NVARCHAR(120) NULL,
 ResearchModel NVARCHAR(120) NULL,
 StartedAt DATETIME2 NULL, SubmittedAt DATETIME2 NULL, ApprovedAt DATETIME2 NULL,
 ApprovedByUserId UNIQUEIDENTIFIER NULL, CreatedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchPacks_Project FOREIGN KEY(ContentProjectId) REFERENCES dbo.ContentProjects(ContentProjectId),
 CONSTRAINT FK_ResearchPacks_Opportunity FOREIGN KEY(SourceOpportunityId) REFERENCES dbo.ContentOpportunities(ContentOpportunityId));
GO
IF OBJECT_ID('dbo.ResearchPackVersions','U') IS NULL CREATE TABLE dbo.ResearchPackVersions(
 ResearchPackVersionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
 ResearchPackId UNIQUEIDENTIFIER NOT NULL, VersionNumber INT NOT NULL, Status NVARCHAR(30) NOT NULL,
 SnapshotJson NVARCHAR(MAX) NOT NULL, ChangeSummary NVARCHAR(1500) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchPackVersions_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId),
 CONSTRAINT UX_ResearchPackVersions UNIQUE(ResearchPackId,VersionNumber));
GO
IF OBJECT_ID('dbo.ResearchQuestions','U') IS NULL CREATE TABLE dbo.ResearchQuestions(
 ResearchQuestionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 QuestionText NVARCHAR(1500) NOT NULL, Priority NVARCHAR(20) NOT NULL DEFAULT 'MEDIUM', Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN',
 AnswerSummary NVARCHAR(MAX) NULL, SortOrder INT NOT NULL DEFAULT 0, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchQuestions_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
IF OBJECT_ID('dbo.ResearchSources','U') IS NULL CREATE TABLE dbo.ResearchSources(
 ResearchSourceId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 SourceType NVARCHAR(60) NOT NULL, Publisher NVARCHAR(200) NULL, Title NVARCHAR(500) NOT NULL, Url NVARCHAR(1500) NULL,
 Author NVARCHAR(250) NULL, PublishedAt DATETIME2 NULL, AccessedAt DATETIME2 NULL, Market NVARCHAR(100) NULL,
 AuthorityScore DECIMAL(5,2) NOT NULL DEFAULT 0, RecencyScore DECIMAL(5,2) NOT NULL DEFAULT 0, RelevanceScore DECIMAL(5,2) NOT NULL DEFAULT 0,
 SourceQuality NVARCHAR(30) NOT NULL DEFAULT 'UNASSESSED', IsPrimarySource BIT NOT NULL DEFAULT 0, IsApproved BIT NOT NULL DEFAULT 0,
 Notes NVARCHAR(MAX) NULL, CitationLabel NVARCHAR(200) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchSources_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
IF OBJECT_ID('dbo.ResearchClaims','U') IS NULL CREATE TABLE dbo.ResearchClaims(
 ResearchClaimId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 ClaimCode NVARCHAR(40) NOT NULL, ClaimText NVARCHAR(MAX) NOT NULL, ClaimType NVARCHAR(60) NOT NULL DEFAULT 'FACT',
 VerificationStatus NVARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED', ConfidenceScore DECIMAL(5,2) NOT NULL DEFAULT 0,
 Materiality NVARCHAR(20) NOT NULL DEFAULT 'MEDIUM', ScriptUsageStatus NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
 VerificationNotes NVARCHAR(MAX) NULL, VerifiedByUserId UNIQUEIDENTIFIER NULL, VerifiedAt DATETIME2 NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchClaims_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='UX_ResearchClaims_Code') CREATE UNIQUE INDEX UX_ResearchClaims_Code ON dbo.ResearchClaims(ResearchPackId,ClaimCode);
GO
IF OBJECT_ID('dbo.ResearchClaimSources','U') IS NULL CREATE TABLE dbo.ResearchClaimSources(
 ResearchClaimSourceId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchClaimId UNIQUEIDENTIFIER NOT NULL, ResearchSourceId UNIQUEIDENTIFIER NOT NULL,
 EvidenceRole NVARCHAR(30) NOT NULL DEFAULT 'SUPPORTS', EvidenceExcerpt NVARCHAR(2000) NULL, EvidenceLocation NVARCHAR(500) NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchClaimSources_Claim FOREIGN KEY(ResearchClaimId) REFERENCES dbo.ResearchClaims(ResearchClaimId),
 CONSTRAINT FK_ResearchClaimSources_Source FOREIGN KEY(ResearchSourceId) REFERENCES dbo.ResearchSources(ResearchSourceId));
GO
IF OBJECT_ID('dbo.ResearchStatistics','U') IS NULL CREATE TABLE dbo.ResearchStatistics(
 ResearchStatisticId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 MetricName NVARCHAR(250) NOT NULL, MetricValue NVARCHAR(250) NOT NULL, PeriodLabel NVARCHAR(100) NULL, Geography NVARCHAR(120) NULL,
 ResearchSourceId UNIQUEIDENTIFIER NULL, VerificationStatus NVARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED', Notes NVARCHAR(1000) NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_ResearchStatistics_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
IF OBJECT_ID('dbo.ResearchEntities','U') IS NULL CREATE TABLE dbo.ResearchEntities(
 ResearchEntityId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 EntityType NVARCHAR(50) NOT NULL, EntityName NVARCHAR(250) NOT NULL, RoleInStory NVARCHAR(1000) NULL, KeyFacts NVARCHAR(MAX) NULL,
 SensitivityLevel NVARCHAR(20) NOT NULL DEFAULT 'LOW', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchEntities_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
IF OBJECT_ID('dbo.ResearchTimelineEvents','U') IS NULL CREATE TABLE dbo.ResearchTimelineEvents(
 ResearchTimelineEventId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 EventDate NVARCHAR(100) NOT NULL, EventTitle NVARCHAR(300) NOT NULL, EventDescription NVARCHAR(MAX) NULL, ResearchSourceId UNIQUEIDENTIFIER NULL, SortOrder INT NOT NULL DEFAULT 0,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_ResearchTimelineEvents_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
IF OBJECT_ID('dbo.ResearchContradictions','U') IS NULL CREATE TABLE dbo.ResearchContradictions(
 ResearchContradictionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 Subject NVARCHAR(300) NOT NULL, PositionA NVARCHAR(MAX) NOT NULL, PositionB NVARCHAR(MAX) NOT NULL, ResolutionStatus NVARCHAR(30) NOT NULL DEFAULT 'OPEN',
 ResolutionNotes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchContradictions_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
IF OBJECT_ID('dbo.ResearchRisks','U') IS NULL CREATE TABLE dbo.ResearchRisks(
 ResearchRiskId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ResearchPackId UNIQUEIDENTIFIER NOT NULL,
 RiskCategory NVARCHAR(80) NOT NULL, Severity NVARCHAR(20) NOT NULL, Description NVARCHAR(MAX) NOT NULL, Mitigation NVARCHAR(MAX) NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ResearchRisks_Pack FOREIGN KEY(ResearchPackId) REFERENCES dbo.ResearchPacks(ResearchPackId));
GO
