/* Module 07: Concept & Script Production */
IF OBJECT_ID('dbo.ScriptConcepts','U') IS NULL CREATE TABLE dbo.ScriptConcepts(
 ScriptConceptId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScriptConcepts PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ContentProjectId UNIQUEIDENTIFIER NOT NULL, ResearchPackVersionId UNIQUEIDENTIFIER NULL,
 ConceptCode NVARCHAR(30) NOT NULL, Title NVARCHAR(300) NOT NULL, Angle NVARCHAR(MAX) NULL, Hook NVARCHAR(MAX) NULL,
 StructureJson NVARCHAR(MAX) NULL, CreativeRationale NVARCHAR(MAX) NULL,
 OverallScore DECIMAL(5,2) NOT NULL DEFAULT 0, RetentionScore DECIMAL(5,2) NOT NULL DEFAULT 0,
 GlobalAppealScore DECIMAL(5,2) NOT NULL DEFAULT 0, VisualPotentialScore DECIMAL(5,2) NOT NULL DEFAULT 0, FactualSafetyScore DECIMAL(5,2) NOT NULL DEFAULT 0,
 Status NVARCHAR(30) NOT NULL DEFAULT 'GENERATED', SelectedAt DATETIME2 NULL, SelectedByUserId UNIQUEIDENTIFIER NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ScriptConcept_Project FOREIGN KEY(ContentProjectId) REFERENCES dbo.ContentProjects(ContentProjectId),
 CONSTRAINT CK_ScriptConcept_Status CHECK(Status IN('GENERATED','SHORTLISTED','SELECTED','REJECTED','APPROVED')),
 CONSTRAINT UQ_ScriptConcept_ProjectCode UNIQUE(ContentProjectId,ConceptCode)
);
GO
IF OBJECT_ID('dbo.ScriptDocuments','U') IS NULL CREATE TABLE dbo.ScriptDocuments(
 ScriptDocumentId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScriptDocuments PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ContentProjectId UNIQUEIDENTIFIER NOT NULL, ScriptConceptId UNIQUEIDENTIFIER NOT NULL, ApprovedResearchPackVersionId UNIQUEIDENTIFIER NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT', CurrentVersionNumber INT NOT NULL DEFAULT 0, ApprovedVersionId UNIQUEIDENTIFIER NULL,
 TargetDurationSeconds INT NULL, ActualDurationSeconds INT NULL, TotalWords INT NOT NULL DEFAULT 0, Language NVARCHAR(50) NOT NULL DEFAULT 'English',
 VoiceMode NVARCHAR(30) NOT NULL DEFAULT 'NARRATION', Tone NVARCHAR(120) NULL, GlobalClarityScore DECIMAL(5,2) NOT NULL DEFAULT 0,
 RetentionScore DECIMAL(5,2) NOT NULL DEFAULT 0, ResearchComplianceScore DECIMAL(5,2) NOT NULL DEFAULT 0,
 SubmittedAt DATETIME2 NULL, ApprovedAt DATETIME2 NULL, ApprovedByUserId UNIQUEIDENTIFIER NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ScriptDoc_Project FOREIGN KEY(ContentProjectId) REFERENCES dbo.ContentProjects(ContentProjectId),
 CONSTRAINT FK_ScriptDoc_Concept FOREIGN KEY(ScriptConceptId) REFERENCES dbo.ScriptConcepts(ScriptConceptId),
 CONSTRAINT UQ_ScriptDoc_Project UNIQUE(ContentProjectId)
);
GO
IF OBJECT_ID('dbo.ScriptVersions','U') IS NULL CREATE TABLE dbo.ScriptVersions(
 ScriptVersionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScriptVersions PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ScriptDocumentId UNIQUEIDENTIFIER NOT NULL, VersionNumber INT NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT',
 SnapshotJson NVARCHAR(MAX) NOT NULL, ChangeSummary NVARCHAR(1500) NULL, WordCount INT NOT NULL DEFAULT 0, DurationSeconds INT NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL, ReviewedByUserId UNIQUEIDENTIFIER NULL, ReviewComment NVARCHAR(MAX) NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), ReviewedAt DATETIME2 NULL,
 CONSTRAINT FK_ScriptVersion_Document FOREIGN KEY(ScriptDocumentId) REFERENCES dbo.ScriptDocuments(ScriptDocumentId),
 CONSTRAINT UQ_ScriptVersion_Number UNIQUE(ScriptDocumentId,VersionNumber)
);
GO
IF OBJECT_ID('dbo.ScriptSections','U') IS NULL CREATE TABLE dbo.ScriptSections(
 ScriptSectionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScriptSections PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ScriptDocumentId UNIQUEIDENTIFIER NOT NULL, SectionOrder INT NOT NULL, SectionType NVARCHAR(30) NOT NULL, Title NVARCHAR(250) NOT NULL,
 StartSecond INT NULL, EndSecond INT NULL, Body NVARCHAR(MAX) NOT NULL, WordCount INT NOT NULL DEFAULT 0,
 SectionPurpose NVARCHAR(1000) NULL, RetentionScore DECIMAL(5,2) NOT NULL DEFAULT 0, Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT',
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ScriptSection_Document FOREIGN KEY(ScriptDocumentId) REFERENCES dbo.ScriptDocuments(ScriptDocumentId),
 CONSTRAINT UQ_ScriptSection_Order UNIQUE(ScriptDocumentId,SectionOrder)
);
GO
IF OBJECT_ID('dbo.ScriptClaimLinks','U') IS NULL CREATE TABLE dbo.ScriptClaimLinks(
 ScriptClaimLinkId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScriptClaimLinks PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ScriptDocumentId UNIQUEIDENTIFIER NOT NULL, ScriptSectionId UNIQUEIDENTIFIER NULL, ResearchClaimId UNIQUEIDENTIFIER NOT NULL,
 ScriptExcerpt NVARCHAR(2000) NOT NULL, LinkStatus NVARCHAR(30) NOT NULL DEFAULT 'LINKED', IsMaterial BIT NOT NULL DEFAULT 1,
 CreatedByUserId UNIQUEIDENTIFIER NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ScriptClaim_Doc FOREIGN KEY(ScriptDocumentId) REFERENCES dbo.ScriptDocuments(ScriptDocumentId),
 CONSTRAINT FK_ScriptClaim_Section FOREIGN KEY(ScriptSectionId) REFERENCES dbo.ScriptSections(ScriptSectionId),
 CONSTRAINT FK_ScriptClaim_ResearchClaim FOREIGN KEY(ResearchClaimId) REFERENCES dbo.ResearchClaims(ResearchClaimId)
);
GO
IF OBJECT_ID('dbo.ScriptRetentionChecks','U') IS NULL CREATE TABLE dbo.ScriptRetentionChecks(
 ScriptRetentionCheckId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScriptRetentionChecks PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ScriptDocumentId UNIQUEIDENTIFIER NOT NULL, ScriptSectionId UNIQUEIDENTIFIER NULL, CheckType NVARCHAR(80) NOT NULL,
 StartSecond INT NULL, EndSecond INT NULL, Score DECIMAL(5,2) NOT NULL DEFAULT 0, Status NVARCHAR(30) NOT NULL DEFAULT 'PASS',
 Finding NVARCHAR(MAX) NULL, Recommendation NVARCHAR(MAX) NULL, IsBlocking BIT NOT NULL DEFAULT 0, ResolvedAt DATETIME2 NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ScriptRetention_Doc FOREIGN KEY(ScriptDocumentId) REFERENCES dbo.ScriptDocuments(ScriptDocumentId),
 CONSTRAINT FK_ScriptRetention_Section FOREIGN KEY(ScriptSectionId) REFERENCES dbo.ScriptSections(ScriptSectionId)
);
GO
IF OBJECT_ID('dbo.ScriptReviews','U') IS NULL CREATE TABLE dbo.ScriptReviews(
 ScriptReviewId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScriptReviews PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
 ScriptDocumentId UNIQUEIDENTIFIER NOT NULL, ScriptVersionId UNIQUEIDENTIFIER NULL, ReviewType NVARCHAR(50) NOT NULL DEFAULT 'HUMAN',
 Decision NVARCHAR(30) NOT NULL, Comment NVARCHAR(MAX) NULL, ReviewerUserId UNIQUEIDENTIFIER NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_ScriptReview_Doc FOREIGN KEY(ScriptDocumentId) REFERENCES dbo.ScriptDocuments(ScriptDocumentId)
);
GO
CREATE INDEX IX_ScriptConcepts_Project_Status ON dbo.ScriptConcepts(ContentProjectId,Status);
CREATE INDEX IX_ScriptSections_Document_Order ON dbo.ScriptSections(ScriptDocumentId,SectionOrder);
CREATE INDEX IX_ScriptClaimLinks_Document ON dbo.ScriptClaimLinks(ScriptDocumentId);
GO
