/* Module 08 — Character, Scene & Storyboard Studio */
IF OBJECT_ID('dbo.CharacterBibles') IS NULL CREATE TABLE dbo.CharacterBibles(
 CharacterBibleId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
 ContentProjectId UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.ContentProjects(ContentProjectId),
 ApprovedScriptVersionId UNIQUEIDENTIFIER NULL REFERENCES dbo.ScriptVersions(ScriptVersionId),
 Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT', CurrentVersionNumber INT NOT NULL DEFAULT 0,
 ApprovedVersionId UNIQUEIDENTIFIER NULL, CreatedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId),
 ApprovedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId), ApprovedAt DATETIME2 NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('dbo.Characters') IS NULL CREATE TABLE dbo.Characters(
 CharacterId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
 CharacterBibleId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.CharacterBibles(CharacterBibleId), CharacterCode NVARCHAR(30) NOT NULL,
 CharacterName NVARCHAR(150) NOT NULL, CharacterRole NVARCHAR(100) NULL, AgeRange NVARCHAR(50) NULL, Gender NVARCHAR(50) NULL,
 Nationality NVARCHAR(100) NULL, SkinTone NVARCHAR(100) NULL, FaceDescription NVARCHAR(1000) NULL, HairDescription NVARCHAR(1000) NULL,
 BuildDescription NVARCHAR(1000) NULL, HeightDescription NVARCHAR(300) NULL, DefaultWardrobe NVARCHAR(2000) NULL,
 Accessories NVARCHAR(1500) NULL, Personality NVARCHAR(2000) NULL, VoiceProfile NVARCHAR(1500) NULL,
 MasterPrompt NVARCHAR(MAX) NULL, NegativePrompt NVARCHAR(MAX) NULL, ReferenceAssetId UNIQUEIDENTIFIER NULL,
 IsLocked BIT NOT NULL DEFAULT 0, LockReason NVARCHAR(1000) NULL, SortOrder INT NOT NULL DEFAULT 0,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT UQ_Characters_Code UNIQUE(CharacterBibleId,CharacterCode));
GO
IF OBJECT_ID('dbo.CharacterWardrobeStates') IS NULL CREATE TABLE dbo.CharacterWardrobeStates(
 WardrobeStateId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, CharacterId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Characters(CharacterId),
 WardrobeCode NVARCHAR(30) NOT NULL, Name NVARCHAR(150) NOT NULL, Description NVARCHAR(2000) NOT NULL, HairState NVARCHAR(1000) NULL,
 AccessoriesState NVARCHAR(1000) NULL, ContinuityNotes NVARCHAR(2000) NULL, ReferenceAssetId UNIQUEIDENTIFIER NULL, IsLocked BIT NOT NULL DEFAULT 0,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_Wardrobe_Code UNIQUE(CharacterId,WardrobeCode));
GO
IF OBJECT_ID('dbo.ProductionLocations') IS NULL CREATE TABLE dbo.ProductionLocations(
 LocationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ContentProjectId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.ContentProjects(ContentProjectId),
 LocationCode NVARCHAR(30) NOT NULL, Name NVARCHAR(200) NOT NULL, LocationType NVARCHAR(100) NULL, Geography NVARCHAR(200) NULL,
 Description NVARCHAR(MAX) NULL, VisualIdentity NVARCHAR(MAX) NULL, LightingBaseline NVARCHAR(1500) NULL, MasterPrompt NVARCHAR(MAX) NULL,
 NegativePrompt NVARCHAR(MAX) NULL, ReferenceAssetId UNIQUEIDENTIFIER NULL, IsLocked BIT NOT NULL DEFAULT 0,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT UQ_ProductionLocations_Code UNIQUE(ContentProjectId,LocationCode));
GO
IF OBJECT_ID('dbo.ScenePackages') IS NULL CREATE TABLE dbo.ScenePackages(
 ScenePackageId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ContentProjectId UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES dbo.ContentProjects(ContentProjectId),
 ApprovedScriptVersionId UNIQUEIDENTIFIER NULL REFERENCES dbo.ScriptVersions(ScriptVersionId), CharacterBibleId UNIQUEIDENTIFIER NULL REFERENCES dbo.CharacterBibles(CharacterBibleId),
 Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT', CurrentVersionNumber INT NOT NULL DEFAULT 0, ApprovedVersionId UNIQUEIDENTIFIER NULL,
 TotalScenes INT NOT NULL DEFAULT 0, TotalDurationSeconds INT NOT NULL DEFAULT 0, ContinuityScore DECIMAL(5,2) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId), ApprovedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId),
 ApprovedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('dbo.Scenes') IS NULL CREATE TABLE dbo.Scenes(
 SceneId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ScenePackageId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.ScenePackages(ScenePackageId),
 SceneNumber INT NOT NULL, SceneCode NVARCHAR(30) NOT NULL, Chapter NVARCHAR(200) NULL, Title NVARCHAR(250) NOT NULL,
 StartSecond INT NOT NULL DEFAULT 0, EndSecond INT NOT NULL DEFAULT 0, DurationSeconds AS (EndSecond-StartSecond) PERSISTED,
 ScriptSectionId UNIQUEIDENTIFIER NULL REFERENCES dbo.ScriptSections(ScriptSectionId), LocationId UNIQUEIDENTIFIER NULL REFERENCES dbo.ProductionLocations(LocationId),
 Dialogue NVARCHAR(MAX) NULL, Voiceover NVARCHAR(MAX) NULL, VisualDescription NVARCHAR(MAX) NULL, ShotType NVARCHAR(100) NULL,
 CameraMovement NVARCHAR(200) NULL, Lens NVARCHAR(100) NULL, Framing NVARCHAR(300) NULL, Lighting NVARCHAR(1000) NULL,
 Mood NVARCHAR(1000) NULL, ImagePrompt NVARCHAR(MAX) NULL, NegativePrompt NVARCHAR(MAX) NULL, AnimationPrompt NVARCHAR(MAX) NULL,
 SfxCue NVARCHAR(1500) NULL, MusicCue NVARCHAR(1500) NULL, TransitionIn NVARCHAR(500) NULL, TransitionOut NVARCHAR(500) NULL,
 GenerationStatus NVARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED', ApprovalStatus NVARCHAR(30) NOT NULL DEFAULT 'DRAFT',
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT UQ_Scenes_Number UNIQUE(ScenePackageId,SceneNumber), CONSTRAINT UQ_Scenes_Code UNIQUE(ScenePackageId,SceneCode));
GO
IF OBJECT_ID('dbo.SceneCharacters') IS NULL CREATE TABLE dbo.SceneCharacters(
 SceneCharacterId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, SceneId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Scenes(SceneId),
 CharacterId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Characters(CharacterId), WardrobeStateId UNIQUEIDENTIFIER NULL REFERENCES dbo.CharacterWardrobeStates(WardrobeStateId),
 ScreenPosition NVARCHAR(100) NULL, ActionDirection NVARCHAR(1500) NULL, Emotion NVARCHAR(500) NULL, ContinuityNotes NVARCHAR(1500) NULL,
 CONSTRAINT UQ_SceneCharacters UNIQUE(SceneId,CharacterId));
GO
IF OBJECT_ID('dbo.StoryboardFrames') IS NULL CREATE TABLE dbo.StoryboardFrames(
 StoryboardFrameId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, SceneId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Scenes(SceneId),
 FrameOrder INT NOT NULL DEFAULT 1, FrameType NVARCHAR(50) NOT NULL DEFAULT 'KEYFRAME', Caption NVARCHAR(1000) NULL, VisualPrompt NVARCHAR(MAX) NULL,
 ReferenceAssetId UNIQUEIDENTIFIER NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT UQ_StoryboardFrames UNIQUE(SceneId,FrameOrder));
GO
IF OBJECT_ID('dbo.ContinuityChecks') IS NULL CREATE TABLE dbo.ContinuityChecks(
 ContinuityCheckId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ScenePackageId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.ScenePackages(ScenePackageId),
 SceneId UNIQUEIDENTIFIER NULL REFERENCES dbo.Scenes(SceneId), CheckType NVARCHAR(80) NOT NULL, Severity NVARCHAR(30) NOT NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN', Description NVARCHAR(2000) NOT NULL, Recommendation NVARCHAR(2000) NULL,
 ResolvedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId), ResolvedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('dbo.ScenePackageVersions') IS NULL CREATE TABLE dbo.ScenePackageVersions(
 ScenePackageVersionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, ScenePackageId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.ScenePackages(ScenePackageId),
 VersionNumber INT NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'IN_REVIEW', SnapshotJson NVARCHAR(MAX) NOT NULL, ChangeSummary NVARCHAR(1500) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId), ReviewedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId),
 ReviewedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_ScenePackageVersions UNIQUE(ScenePackageId,VersionNumber));
GO
IF OBJECT_ID('dbo.CharacterBibleVersions') IS NULL CREATE TABLE dbo.CharacterBibleVersions(
 CharacterBibleVersionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, CharacterBibleId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.CharacterBibles(CharacterBibleId),
 VersionNumber INT NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'IN_REVIEW', SnapshotJson NVARCHAR(MAX) NOT NULL, ChangeSummary NVARCHAR(1500) NULL,
 CreatedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId), ReviewedByUserId UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(UserId),
 ReviewedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_CharacterBibleVersions UNIQUE(CharacterBibleId,VersionNumber));
GO
CREATE INDEX IX_Scenes_Package ON dbo.Scenes(ScenePackageId,SceneNumber);
CREATE INDEX IX_ContinuityChecks_Package ON dbo.ContinuityChecks(ScenePackageId,Status,Severity);
GO
