SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.AgentDefinitions','U') IS NULL CREATE TABLE dbo.AgentDefinitions(
 AgentDefinitionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 AgentKey NVARCHAR(100) NOT NULL, Name NVARCHAR(160) NOT NULL, Capability NVARCHAR(80) NOT NULL, ExecutionMode NVARCHAR(40) NOT NULL DEFAULT 'HUMAN_GATED',
 ProviderKey NVARCHAR(100) NULL, ModelName NVARCHAR(160) NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'ONLINE', MaxConcurrency INT NOT NULL DEFAULT 1,
 MaxRetries INT NOT NULL DEFAULT 3, MonthlyBudget DECIMAL(18,2) NULL, ConfigurationJson NVARCHAR(MAX) NULL, IsEnabled BIT NOT NULL DEFAULT 1,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_AgentDefinitions UNIQUE(WorkspaceId,AgentKey));

IF OBJECT_ID('dbo.WorkflowConfigurations','U') IS NULL CREATE TABLE dbo.WorkflowConfigurations(
 WorkflowConfigurationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 VersionNo INT NOT NULL, Name NVARCHAR(160) NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT', ConfigurationJson NVARCHAR(MAX) NULL,
 PublishedByUserId UNIQUEIDENTIFIER NULL, PublishedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_WorkflowConfig UNIQUE(WorkspaceId,VersionNo));

IF OBJECT_ID('dbo.ProviderIntegrations','U') IS NULL CREATE TABLE dbo.ProviderIntegrations(
 ProviderIntegrationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 ProviderKey NVARCHAR(100) NOT NULL, DisplayName NVARCHAR(180) NOT NULL, ProviderGroup NVARCHAR(40) NOT NULL, Capability NVARCHAR(500) NULL,
 ConnectionStatus NVARCHAR(30) NOT NULL DEFAULT 'NOT_CONNECTED', HealthStatus NVARCHAR(30) NOT NULL DEFAULT 'UNKNOWN', AuthType NVARCHAR(60) NULL,
 SecretReference NVARCHAR(400) NULL, BaseUrl NVARCHAR(500) NULL, ScopeJson NVARCHAR(MAX) NULL, LastHealthCheckAt DATETIME2 NULL,
 LastHealthMessage NVARCHAR(1000) NULL, IsEnabled BIT NOT NULL DEFAULT 1, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_ProviderIntegrations UNIQUE(WorkspaceId,ProviderKey));

IF OBJECT_ID('dbo.ProviderBudgets','U') IS NULL CREATE TABLE dbo.ProviderBudgets(
 ProviderBudgetId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 ProviderKey NVARCHAR(100) NOT NULL, PeriodType NVARCHAR(20) NOT NULL DEFAULT 'MONTHLY', BudgetAmount DECIMAL(18,2) NOT NULL,
 WarningPercent DECIMAL(5,2) NOT NULL DEFAULT 80, HardStopPercent DECIMAL(5,2) NOT NULL DEFAULT 100, CurrencyCode CHAR(3) NOT NULL DEFAULT 'USD',
 IsHardStopEnabled BIT NOT NULL DEFAULT 0, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_ProviderBudgets UNIQUE(WorkspaceId,ProviderKey,PeriodType));

IF OBJECT_ID('dbo.AssetCatalog','U') IS NULL CREATE TABLE dbo.AssetCatalog(
 AssetCatalogId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL, ContentProjectId UNIQUEIDENTIFIER NULL,
 AssetKey NVARCHAR(120) NOT NULL, FileName NVARCHAR(500) NOT NULL, AssetType NVARCHAR(50) NOT NULL, MimeType NVARCHAR(120) NULL, StorageUri NVARCHAR(1000) NULL,
 ByteSize BIGINT NULL, ChecksumSha256 NVARCHAR(128) NULL, LifecycleStatus NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE', IsMaster BIT NOT NULL DEFAULT 0,
 SourceEntityType NVARCHAR(100) NULL, SourceEntityId UNIQUEIDENTIFIER NULL, MetadataJson NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_AssetCatalog UNIQUE(WorkspaceId,AssetKey));

IF OBJECT_ID('dbo.NotificationPolicies','U') IS NULL CREATE TABLE dbo.NotificationPolicies(
 NotificationPolicyId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 PolicyKey NVARCHAR(120) NOT NULL, Name NVARCHAR(180) NOT NULL, TriggerEvent NVARCHAR(120) NOT NULL, Severity NVARCHAR(30) NOT NULL,
 Channels NVARCHAR(300) NOT NULL, RecipientRule NVARCHAR(600) NOT NULL, EscalationMinutes INT NULL, IsEnabled BIT NOT NULL DEFAULT 1,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_NotificationPolicies UNIQUE(WorkspaceId,PolicyKey));

IF OBJECT_ID('dbo.SystemSettings','U') IS NULL CREATE TABLE dbo.SystemSettings(
 SystemSettingId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 SettingKey NVARCHAR(160) NOT NULL, SettingValue NVARCHAR(MAX) NULL, ValueType NVARCHAR(30) NOT NULL DEFAULT 'STRING', IsSecret BIT NOT NULL DEFAULT 0,
 UpdatedByUserId UNIQUEIDENTIFIER NULL, UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_SystemSettings UNIQUE(WorkspaceId,SettingKey));

IF OBJECT_ID('dbo.BackupRuns','U') IS NULL CREATE TABLE dbo.BackupRuns(
 BackupRunId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 BackupType NVARCHAR(40) NOT NULL, TargetName NVARCHAR(160) NOT NULL, StorageLocation NVARCHAR(1000) NULL, Status NVARCHAR(30) NOT NULL,
 StartedAt DATETIME2 NOT NULL, CompletedAt DATETIME2 NULL, ByteSize BIGINT NULL, IsVerified BIT NOT NULL DEFAULT 0, VerificationAt DATETIME2 NULL,
 ErrorMessage NVARCHAR(2000) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('dbo.ServiceHealthChecks','U') IS NULL CREATE TABLE dbo.ServiceHealthChecks(
 ServiceHealthCheckId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY, WorkspaceId UNIQUEIDENTIFIER NOT NULL,
 ServiceKey NVARCHAR(120) NOT NULL, Status NVARCHAR(30) NOT NULL, LatencyMs INT NULL, Detail NVARCHAR(1000) NULL, CheckedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

CREATE INDEX IX_AgentDefinitions_Workspace_Status ON dbo.AgentDefinitions(WorkspaceId,Status);
CREATE INDEX IX_ProviderIntegrations_Workspace_Group ON dbo.ProviderIntegrations(WorkspaceId,ProviderGroup);
CREATE INDEX IX_AssetCatalog_Project_Type ON dbo.AssetCatalog(ContentProjectId,AssetType);
CREATE INDEX IX_BackupRuns_Workspace_Started ON dbo.BackupRuns(WorkspaceId,StartedAt DESC);
CREATE INDEX IX_ServiceHealthChecks_Workspace_Checked ON dbo.ServiceHealthChecks(WorkspaceId,CheckedAt DESC);
COMMIT TRANSACTION;
