import type {FastifyInstance} from 'fastify';
import * as repo from './repository.js';
import {sql} from '@cacsms/database';
type Ctx={workspaceId:string;userId:string;server:FastifyInstance;capMap:Map<string,{RepositoryFunction:string;DefaultPayloadJson:any;DispatchPhase:string}>;gates:{agent:Map<string,any>;provider:Map<string,any>;budget:Map<string,any>;settings:Map<string,string>;learningThreshold:number;recyclingPriority:string;activeWorkflow:any;maxRetries:number;concurrency:number}};
const uid=(c:Ctx)=>c.userId;
function merge(base:any,...patches:any[]){return patches.reduce((a,b)=>b && typeof b==='object'?{...a,...b}:a,{...base||{}})}
function parseDate(s:any):Date{return s?new Date(s):new Date()}
async function bootstrapUserId():Promise<string>{try{const e=process.env.BOOTSTRAP_ADMIN_EMAIL||'admin@cacsms-cinema.local';const u=await repo.findUserByEmail(e);return u?.UserId||'00000000-0000-0000-0000-000000000000'}catch{return '00000000-0000-0000-0000-000000000000'}}
async function firstMemberWorkspaceId():Promise<string|null>{try{const e=process.env.BOOTSTRAP_ADMIN_EMAIL||'admin@cacsms-cinema.local';const u=await repo.findUserByEmail(e);if(!u?.UserId)return null;const ms=await repo.listMemberships(u.UserId);return (ms as any[])[0]?.WorkspaceId||null}catch{return null}}
async function passGovernanceGates(ctx:Ctx,cap:string,stage:string){const caps=Array.from(ctx.gates.agent.values()).filter((a:any)=>a.Capability===cap);if(!caps.length)caps.push(...Array.from(ctx.gates.agent.values()).filter((a:any)=>a.ExecutionMode==='AUTONOMOUS'&&a.IsActive));if(!caps.length)throw new Error(`GATE_NO_ACTIVE_AGENT cap=${cap}`);const agent=caps[0];if(!agent.IsActive)throw new Error(`GATE_AGENT_INACTIVE ${agent.AgentKey}`);const anyProvider=Array.from(ctx.gates.provider.values()).some((p:any)=>p.ConnectionStatus==='CONNECTED');if(!anyProvider)throw new Error('GATE_NO_CONNECTED_PROVIDER');const providerKey=agent.ProviderKey;const agentBudget=providerKey?ctx.gates.budget.get(providerKey):null;const breachBudgets=agentBudget?[agentBudget]:Array.from(ctx.gates.budget.values());const breach=breachBudgets.find((b:any)=>((+b.SpentAmount)||0)>=((+b.BudgetAmount||0)*((+b.HardStopPercent||100)/100)));if(breach){const msg:any=new Error(`PROVIDER_BUDGET_HARD_LIMIT_EXCEEDED provider=${breach.ProviderKey} spent=${breach.SpentAmount} budget=${breach.BudgetAmount} hardStopPct=${breach.HardStopPercent}`);msg.code='PROVIDER_BUDGET_HARD_LIMIT_EXCEEDED';msg.reason='PROVIDER_BUDGET_HARD_LIMIT_EXCEEDED';msg.detail={providerKey:breach.ProviderKey,spent:+breach.SpentAmount||0,budget:+breach.BudgetAmount||0,hardStopPercent:+breach.HardStopPercent||100};throw msg}return {agent:agent.AgentKey,providerKey:agent.ProviderKey||null,anyProvider:true,budgetBreach:false}}
const adapters:Record<string,(projectId:string,ctx:Ctx,payload:any)=>Promise<any>>={
 async saveStrategyBrief(p,c,pay){return repo.saveStrategyBrief(c.workspaceId,p,uid(c),merge({primaryObjective:'Autonomous brief objective',synopsis:'Generated autonomously by Cacsms Cinema orchestration',targetAudience:'General audience',genre:'Drama',formatType:'SHORTFORM',status:'DRAFT'},pay))},
 async submitStrategyBrief(p,c,pay){return repo.submitStrategyBrief(c.workspaceId,p,uid(c),merge({changeSummary:'Autonomous submit'},pay))},
 async decideStrategyBrief(p,c,pay){const sb=await repo.getStrategyBrief(c.workspaceId,p);const vn=(sb as any)?.VersionNo??1;return repo.decideStrategyBrief(c.workspaceId,p,uid(c),merge({decision:'APPROVE',approverUserId:uid(c),notes:'Auto-approve autonomous',versionNo:vn},pay))},
 async createDiscoveryRun(p,c,pay){return repo.createDiscoveryRun(c.workspaceId,p,uid(c),merge({query:'trending shortform',region:'GLOBAL',depthLevel:1},pay))},
 async decideOpportunity(p,c,pay){const list=await repo.listOpportunities(c.workspaceId,p);const ids=((list as any)?.opportunities||[]).map((x:any)=>x.OpportunityId);return repo.decideOpportunity(c.workspaceId,p,uid(c),merge({decision:'SELECT',selectedOpportunityIds:ids.join(',')||'AUTO-1',notes:'Autonomous select top opportunity'},pay))},
 async startResearchPack(p,c,pay){return repo.startResearchPack(c.workspaceId,p,uid(c),merge({title:'Autonomous research pack'},pay))},
 async saveResearchPack(p,c,pay){try{const r:any=await repo.getResearchPack(c.workspaceId,p);const rpId=r?.pack?.ResearchPackId;if(!rpId)await adapters.startResearchPack(p,c,pay)}catch{}const src=await repo.saveResearchPack(c.workspaceId,p,uid(c),merge({sourceUrl:'https://demo-data.cacsms-cinema.local/auto-'+p,summary:'Auto-collected facts',reliabilityScore:90,sourceType:'MARKET_DATA'},pay));return src},
 async submitResearchPack(p,c,pay){return repo.submitResearchPack(c.workspaceId,p,uid(c),merge({changeSummary:'Autonomous research pack submitted'},pay))},
 async decideResearchPack(p,c,pay){return repo.decideResearchPack(c.workspaceId,p,uid(c),'APPROVE','Auto-approve research pack')},
 async generateScriptConcepts(p,c,pay){return repo.generateScriptConcepts(c.workspaceId,p,uid(c),merge({count:3,diversitySeed:Date.now()},pay))},
 async decideScriptConcept(p,c,pay){const w:any=await repo.getScriptWorkspace(c.workspaceId,p);const sel=(w?.concepts||[]).find((x:any)=>x.Status==='SELECTED')||(w?.concepts||[])[0];if(!sel?.ScriptConceptId)throw new Error('No script concept available for auto-approval');return repo.decideScriptConcept(c.workspaceId,p,sel.ScriptConceptId,uid(c),merge({decision:'APPROVE'},pay))},
 async startScriptDocument(p,c,pay){return repo.startScriptDocument(c.workspaceId,p,uid(c),merge({formatType:'SHORTFORM',versionNo:1},pay))},
 async saveScriptSections(p,c,pay){try{await repo.startScriptDocument(c.workspaceId,p,uid(c),merge({formatType:'SHORTFORM'},pay))}catch{}const sections=[{sectionType:'BEAT_SHEET',order:1,content:'Auto generated beat sheet content',status:'APPROVED'},{sectionType:'SCENE',order:2,content:'Auto generated scene text',startSecond:0,endSecond:30,status:'APPROVED'}];return repo.saveScriptSections(c.workspaceId,p,uid(c),merge({sections},pay))},
 async submitScript(p,c,pay){return repo.submitScript(c.workspaceId,p,uid(c),merge({changeSummary:'Autonomous script submitted'},pay))},
 async decideScript(p,c,pay){return repo.decideScript(c.workspaceId,p,uid(c),'APPROVE','Auto-approve script')},
 async startProductionPlanning(p,c,pay){return repo.startProductionPlanning(c.workspaceId,p,uid(c))},
 async saveCharacter(p,c,pay){try{await repo.startProductionPlanning(c.workspaceId,p,uid(c))}catch{}return repo.saveCharacter(c.workspaceId,p,uid(c),merge({characterCode:'C-AUTO',characterName:'Alex',characterRole:'LEAD',traits:['Brave','Empathetic'],actor:'TBD'},pay))},
 async saveScene(p,c,pay){try{await repo.startProductionPlanning(c.workspaceId,p,uid(c))}catch{}return repo.saveScene(c.workspaceId,p,uid(c),merge({sceneNo:'S1',sceneCode:'S-AUTO-01',title:'Opening',location:'House',shootDate:new Date(),status:'APPROVED'},pay))},
 async submitProductionPlanning(p,c,pay){return repo.submitProductionPlanning(c.workspaceId,p,uid(c))},
 async decideProductionPlanning(p,c,pay){return repo.decideProductionPlanning(c.workspaceId,p,uid(c),'APPROVE','Auto-approve production planning')},
 async createGenerationJob(p,c,pay){const w:any=await repo.getGenerationWorkspace(c.workspaceId,p);const j=await repo.createGenerationJob(c.workspaceId,p,uid(c),merge({sceneId:null,modality:'IMAGE',providerKey:'openai',modelName:'gpt-image',promptTemplate:'Auto generated asset for project'},pay));return j},
 async registerGeneratedAsset(p,c,pay){const w:any=await repo.getGenerationWorkspace(c.workspaceId,p);const j=(w?.jobs||[]).find((x:any)=>['QUEUED','RUNNING','COMPLETED','IN_PROGRESS'].includes(x.Status))||(w?.jobs||[])[0];if(!j?.GenerationJobId)throw new Error('No generation job available for asset registration');const aType=pay?.assetType||j.Capability||'IMAGE';return repo.registerGeneratedAsset(c.workspaceId,p,uid(c),merge({jobId:j.GenerationJobId,assetType:aType,assetRole:'MASTER_VARIANT',storageUri:`demo://${p}/gen/${j.GenerationJobId.slice(0,8)}-${aType.toLowerCase()}.bin`,previewUri:`demo://${p}/gen/${j.GenerationJobId.slice(0,8)}-preview.jpg`,mimeType:aType==='IMAGE'?'image/jpeg':aType==='VIDEO'?'video/mp4':'audio/mpeg',durationSeconds:aType==='VIDEO'?30:aType==='VOICE'?15:undefined,width:aType==='IMAGE'?1920:undefined,height:aType==='IMAGE'?1080:undefined,metadata:{orchestrator:true,generationJobId:j.GenerationJobId}},pay))},
 async decideGeneratedAsset(p,c,pay){const w:any=await repo.getGenerationWorkspace(c.workspaceId,p);const a=(w?.assets||[]).find((x:any)=>x.ApprovalStatus!=='APPROVED')||(w?.assets||[])[0];if(!a?.GeneratedAssetId)throw new Error('No generated asset available for approval');return repo.decideGeneratedAsset(c.workspaceId,a.GeneratedAssetId,uid(c),'APPROVE','Auto-approve generated asset')},
 async completeGenerationStage(p,c,pay){return repo.completeGenerationStage(c.workspaceId,p,uid(c))},
 async saveEditTimeline(p,c,pay){return repo.saveEditTimeline(c.workspaceId,p,uid(c),merge({versionNo:1,durationSec:60,masterUri:`demo://${p}/master-v1.mp4`,status:'READY'},pay))},
 async updateQACheck(p,c,pay){const w:any=await repo.getEditingWorkspace(c.workspaceId,p);const ck=(w?.qualityChecks||[])[0]?.QualityCheckId;if(!ck){await repo.saveEditTimeline(c.workspaceId,p,uid(c),merge({status:'READY'},pay));const w2:any=await repo.getEditingWorkspace(c.workspaceId,p);const cid=(w2?.qualityChecks||[])[0]?.QualityCheckId;if(cid)return repo.updateQACheck(c.workspaceId,cid,uid(c),merge({checkType:'QC_VIDEO',status:'PASSED',notes:'Autonomous QC pass'},pay));throw new Error('No QC checks available')}return repo.updateQACheck(c.workspaceId,ck,uid(c),merge({checkType:'QC_VIDEO',status:'PASSED',notes:'Autonomous QC pass'},pay))},
 async decideMasterVideo(p,c,pay){return repo.decideMasterVideo(c.workspaceId,p,uid(c),merge({decision:'APPROVE',comment:'Auto-approve master video'},pay))},
 async saveThumbnailVariant(p,c,pay){try{await repo.getPackagingWorkspace(c.workspaceId,p)}catch{}return repo.saveThumbnailVariant(c.workspaceId,p,uid(c),merge({variantKey:'V1',storageUri:`demo://${p}/thumb-v1.jpg`,aestheticScore:85,clickScore:80,status:'READY'},pay))},
 async decideThumbnailVariant(p,c,pay){const w:any=await repo.getPackagingWorkspace(c.workspaceId,p);const t=(w?.thumbnails||[]).find((x:any)=>x.Status!=='APPROVED')||(w?.thumbnails||[])[0];if(!t?.ThumbnailVariantId)throw new Error('No thumbnail available for approval');return repo.decideThumbnailVariant(c.workspaceId,t.ThumbnailVariantId,uid(c),merge({decision:'APPROVE'},pay))},
 async saveMetadataPackage(p,c,pay){return repo.saveMetadataPackage(c.workspaceId,p,uid(c),merge({primaryTitle:'Autonomous metadata',description:'Auto-generated description',platform:'YouTube'},pay))},
 async updatePackagingCheck(p,c,pay){const w:any=await repo.getPackagingWorkspace(c.workspaceId,p);const ck=(w?.checks||[])[0]?.PackagingCheckId;if(!ck)throw new Error('No packaging checks available');return repo.updatePackagingCheck(c.workspaceId,ck,uid(c),merge({checkType:'MUXING',status:'PASSED',notes:'Autonomous packaging check'},pay))},
 async createPackagingVersion(p,c,pay){return repo.createPackagingVersion(c.workspaceId,p,uid(c),merge({versionNo:1},pay))},
 async decidePackagingVersion(p,c,pay){const w:any=await repo.getPackagingWorkspace(c.workspaceId,p);const v=(w?.versions||[])[0]?.PackagingVersionId;if(!v)throw new Error('No packaging version available for approval');return repo.decidePackagingVersion(c.workspaceId,p,uid(c),merge({decision:'APPROVE',packagingVersionId:v},pay))},
 async updateReleaseCheck(p,c,pay){const w:any=await repo.getReleaseWorkspace(c.workspaceId,p);const r=(w?.checks||[]).find((x:any)=>x.Status!=='PASSED')||(w?.checks||[])[0];if(!r?.ReleaseCheckId)throw new Error('No release checks available');return repo.updateReleaseCheck(c.workspaceId,r.ReleaseCheckId,uid(c),merge({checkType:'RIGHTS',status:'PASSED',notes:'Autonomous release check'},pay))},
 async decideReleaseApproval(p,c,pay){let rw:any=await repo.getReleaseWorkspace(c.workspaceId,p);if(!rw)throw new Error('Release project not found');for(const step of rw?.approvals||[]){if(step.Status==='PENDING'){rw=await repo.getReleaseWorkspace(c.workspaceId,p);await Promise.all((rw.checks||[]).map((c2:any)=>c2.Status!=='PASSED'?repo.updateReleaseCheck(c.workspaceId,c2.ReleaseCheckId,uid(c),{status:'PASSED',evidence:'Auto verified'}):Promise.resolve()))}return repo.decideReleaseApproval(c.workspaceId,p,uid(c),merge({decision:'APPROVE',approvalStepId:step.ReleaseApprovalStepId},pay))}return {ok:true,status:'ALREADY_APPROVED'}},
 async createPublishJob(p,c,pay){const w:any=await repo.getReleaseWorkspace(c.workspaceId,p);if(!w)throw new Error('Release project required before publishing');return repo.createPublishJob(c.workspaceId,p,uid(c),merge({platform:'YOUTUBE',operation:'PUBLISH'},pay))},
 async controlPublishJob(p,c,pay){const w:any=await repo.getReleaseWorkspace(c.workspaceId,p);const j=(w?.jobs||[])[0]?.PublishJobId;if(!j)throw new Error('No publish job available');return repo.controlPublishJob(c.workspaceId,j,uid(c),merge({action:'QUEUE'},pay))},
 async registerPublication(p,c,pay){const w:any=await repo.getReleaseWorkspace(c.workspaceId,p);const j=(w?.jobs||[]).find((x:any)=>['QUEUED','SCHEDULED','RUNNING','PUBLISH_READY'].includes(x.Status))||(w?.jobs||[])[0];if(!j?.PublishJobId)throw new Error('No publish job ready for registration');return repo.registerPublication(c.workspaceId,j.PublishJobId,uid(c),merge({externalPublicationId:'DEMO-PUB-'+j.PublishJobId?.slice(0,6),publicationUrl:`https://demo.cacsms-cinema.local/p/${j.PublishJobId}`,status:'LIVE',publishedAt:new Date(),metrics:{views:0,likes:0,shares:0,watchHours:0}},pay))},
 async ingestPerformanceSnapshot(p,c,pay){const win=pay?.window||'1H';const t={window:win,snapshotAt:new Date(),views:100+Math.floor(Math.random()*9000),impressions:200+Math.floor(Math.random()*18000),likes:5+Math.floor(Math.random()*500),shares:2+Math.floor(Math.random()*200),watchHours:1+Math.random()*50,watchTimeMinutes:60+Math.random()*3000,averageViewDurationSeconds:10+Math.random()*50,averagePercentageViewed:65+Math.random()*30,clickThroughRate:1+Math.random()*8,comments:1+Math.floor(Math.random()*100),subscribersGained:Math.floor(Math.random()*50),revenue:Math.random()*500,rpm:1+Math.random()*10,engagementRate:2+Math.random()*10,metadata:{}};return repo.ingestPerformanceSnapshot(c.workspaceId,p,merge(t,pay))},
 async decideLearningInsight(p,c,pay){const t=c.gates.learningThreshold;const w:any=await repo.getAnalyticsWorkspace(c.workspaceId,p);const ins=(w?.insights||[]).find((x:any)=>x.Status!=='APPROVED'&&x.Status!=='REJECTED')||(w?.insights||[])[0];if(!ins?.LearningInsightId)throw new Error('No learning insight available for decision');const conf=ins.ConfidenceScore??100;const dec=(+conf>=+t)?'APPROVE':'REJECT';return repo.decideLearningInsight(c.workspaceId,ins.LearningInsightId,uid(c),merge({decision:dec,notes:`Auto ${dec} via threshold ${t} confidence ${conf}`},pay))},
 async applyLearningFeedback(p,c,pay){const w:any=await repo.getAnalyticsWorkspace(c.workspaceId,p);const fb=(w?.feedback||[]).find((x:any)=>x.Status!=='APPLIED')||(w?.feedback||[])[0];if(!fb?.LearningFeedbackId)throw new Error('No learning feedback row to apply');return repo.applyLearningFeedback(c.workspaceId,fb.LearningFeedbackId,uid(c))},
 async decideContentRecyclingPlan(p,c,pay){const pr=c.gates.recyclingPriority;const w:any=await repo.getAnalyticsWorkspace(c.workspaceId,p);const plan=(w?.recycling||[]).find((x:any)=>x.Status!=='APPROVED'&&x.Status!=='REJECTED')||(w?.recycling||[])[0];if(!plan?.ContentRecyclingPlanId)throw new Error('No recycling plan available for decision');const pj=plan.Priority||'HIGH';const dec=(pj===pr||pj==='CRITICAL'||pr==='HIGH')?'APPROVE':'REJECT';return repo.decideContentRecyclingPlan(c.workspaceId,plan.ContentRecyclingPlanId,uid(c),merge({decision:dec,notes:`Auto ${dec} via priority ${pr}`},pay))}
};
function ctxParam(c:Ctx,key:string,fallback:any){const v=c.gates.settings.get('orchestrator.'+key);if(v===undefined||v===null)return fallback;const t=typeof fallback;return t==='number'?+v:v}
async function runClosedLoopPublication(ctx:Ctx,projectId:string,result:any,runId:string){if(!result)return;const publishedAt=parseDate(result.PublishedAt||result.CompletedAt||new Date());const offsets:[string,number][]=[['1H',3600_000],['6H',6*3600_000],['24H',24*3600_000],['48H',48*3600_000]];for(const [w,off] of offsets){const payload={window:w,snapshotAt:new Date(publishedAt.getTime()+off)};try{const r=await repo.createOrchestrationRun(ctx.workspaceId,{projectId,stageKey:`PERFORMANCE_SNAPSHOT_${w}`,agentCapability:`PERFORMANCE_SNAPSHOT_${w}`,workflowVersionNo:ctx.gates.activeWorkflow?.VersionNo||1,triggeredBy:'CLOSED_LOOP_v15',payloadJson:payload,maxRetries:ctx.gates.maxRetries,slaDueAt:new Date(payload.snapshotAt.getTime()+60*60000)});await repo.recordRunEvent(ctx.workspaceId,r.RunId,'SCHEDULED','INFO',{window:w,parentRun:runId,off_ms:off})}catch(e:any){if(e?.code!=='ALREADY_COMPLETED')throw e}}
}
async function enqueueSingle(ctx:Ctx,projectId:string,cap:string,parentRunId:string,payload:any){try{const stageKey=cap;const run=await repo.createOrchestrationRun(ctx.workspaceId,{projectId,stageKey,agentCapability:cap,workflowVersionNo:ctx.gates.activeWorkflow?.VersionNo||1,triggeredBy:'CLOSED_LOOP_v15',payloadJson:payload,maxRetries:ctx.gates.maxRetries});await repo.recordRunEvent(ctx.workspaceId,run.RunId,'SCHEDULED','INFO',{cap,parent:parentRunId});return run}catch(e:any){if(e?.code==='ALREADY_COMPLETED')return null;throw e}}
async function runClosedLoopLearning(ctx:Ctx,projectId:string,runId:string){for(const cap of['LEARNING_INSIGHT_DECIDE','LEARNING_FEEDBACK_APPLY'])await enqueueSingle(ctx,projectId,cap,runId,{projectType:'ANALYTICS'})}
async function runClosedLoopRecycling(ctx:Ctx,projectId:string,runId:string){await enqueueSingle(ctx,projectId,'RECYCLING_DECIDE',runId,{projectType:'ANALYTICS'});try{const pFull:any=await repo.getContentProject(ctx.workspaceId,projectId);const p=(pFull?.project||pFull) as any;if(p&&String(p.FormatType||p.ContentType||'').toUpperCase()!=='SHORTFORM'&&ctxParam(ctx,'enable_derivative_shortform',true)){const base={workingTitle:(p.WorkingTitle||p.Title||p.ContentCode||'Project')+' — Derivative Shortform',description:`Autonomous derivative shortform recycling. Parent: ${projectId}`,contentType:'SHORTFORM_VIDEO',primaryPlatform:'YouTube',targetAudience:p.TargetAudience||'General audience',targetCountries:['GLOBAL'],language:'English',aspectRatio:'9:16',category:p.Category||'Autonomous Derivative',objective:p.Objective||'ENGAGEMENT',priority:'MEDIUM',autonomyMode:'AUTONOMOUS'};const child:any=await repo.createContentProject(ctx.workspaceId,uid(ctx),base);await repo.recordRunEvent(ctx.workspaceId,runId,'DERIVATIVE_PROJECT','INFO',{childProjectId:child?.ContentProjectId,childTitle:child?.WorkingTitle||child?.Title})}}catch(e:any){await repo.recordRunEvent(ctx.workspaceId,runId,'DERIVATIVE_SKIP','WARNING',{error:e?.message})}}
async function pollOnce(ctx:Ctx){try{const rows=await repo.pollReadyStages(ctx.workspaceId,ctx.gates.concurrency||1);if(!rows.length)return;for(const row of rows){const cap=(row.AgentCapability as string)||(row.StageKey as string);let mapped=ctx.capMap.get(cap);if(!mapped)mapped={RepositoryFunction:cap,DefaultPayloadJson:{},DispatchPhase:'TRANSACT'};const fn=mapped.RepositoryFunction;const adapter=adapters[fn];if(!adapter){ctx.server.log?.warn?.(`[orch] missing adapter ${fn} cap=${cap} stage=${row.StageKey}`);continue}const payload=merge(typeof mapped.DefaultPayloadJson==='string'?JSON.parse(mapped.DefaultPayloadJson||'{}'):mapped.DefaultPayloadJson,row,{capability:cap,stageKey:row.StageKey});let run:any;try{run=await repo.createOrchestrationRun(ctx.workspaceId,{projectId:row.ProjectId,stageKey:row.StageKey,agentCapability:cap,workflowVersionNo:ctx.gates.activeWorkflow?.VersionNo||1,triggeredBy:'ORCHESTRATOR_v15',payloadJson:payload,maxRetries:ctx.gates.maxRetries})}catch(e:any){if(e?.code==='ALREADY_COMPLETED')continue;throw e}let dbTx:any=null;try{try{const {getDb}=await import('@cacsms/database');dbTx=await (getDb as any)();try{await dbTx.request().query(`BEGIN TRANSACTION;`)}catch{}}catch{}await repo.markOrchestrationRunRunning(ctx.workspaceId,run.RunId);await repo.recordRunEvent(ctx.workspaceId,run.RunId,'START','INFO',{cap,fn,dispatchPhase:mapped.DispatchPhase});const gate=await passGovernanceGates(ctx,cap,row.StageKey);await repo.recordRunEvent(ctx.workspaceId,run.RunId,'GATE_PASS','INFO',gate);const result=await adapter(row.ProjectId as string,ctx,payload);await repo.completeOrchestrationRunSuccess(ctx.workspaceId,run.RunId,{adapter:fn,gate,result});await repo.recordRunEvent(ctx.workspaceId,run.RunId,'COMPLETE','SUCCESS',{adapter:fn});try{if(dbTx)await dbTx.request().query(`COMMIT TRANSACTION;`)}catch{}if(fn==='registerPublication')await runClosedLoopPublication(ctx,row.ProjectId as string,result,run.RunId);if(cap.startsWith('PERFORMANCE_SNAPSHOT_')&&(cap.endsWith('24H')||cap.endsWith('48H')))await runClosedLoopLearning(ctx,row.ProjectId as string,run.RunId);if(cap==='LEARNING_FEEDBACK_APPLY')await runClosedLoopRecycling(ctx,row.ProjectId as string,run.RunId)}catch(err:any){try{if(dbTx){try{await dbTx.request().query(`ROLLBACK TRANSACTION;`)}catch{}}}catch{}await repo.recordRunEvent(ctx.workspaceId,run.RunId,'FAIL','ERROR',{err:err?.message,stack:err?.stack?.slice(0,2000),reason:err?.reason||err?.code||null});await repo.completeOrchestrationRunFail(ctx.workspaceId,run.RunId,err,ctx.gates.maxRetries)}}}catch(e:any){ctx.server.log?.error?.(e)}}
export async function createOrchestrationEngine(server:FastifyInstance,db:any,_rp:any){const wsId=process.env.WORKSPACE_ID||await firstMemberWorkspaceId();if(!wsId){server.log?.warn?.('[orch] boot skipped: no workspace');return {_noop:true,start:()=>{},stop:()=>{}}}const userId=process.env.ORCH_USER_ID||await bootstrapUserId();const ctx={workspaceId:wsId,userId,server,capMap:new Map<string,any>(),gates:{agent:new Map(),provider:new Map(),budget:new Map(),settings:new Map(),learningThreshold:85,recyclingPriority:'HIGH',activeWorkflow:null,maxRetries:3,concurrency:1}} as Ctx;async function refreshBootstrap(){try{const r=await repo.getOrchestratorBootstrap(ctx.workspaceId);ctx.capMap=new Map(r.capabilities.map((c:any)=>[c.AgentCapability,c]));ctx.gates.settings=new Map(r.settings.map((s:any)=>[s.SettingKey,s.SettingValue]));ctx.gates.activeWorkflow=r.activeWorkflow;const ops=await repo.getAdminOperations(ctx.workspaceId);for(const a of ops.agents||[])if(a.AgentKey)ctx.gates.agent.set(a.AgentKey,a);for(const p of ops.providers||[])if(p.ProviderKey)ctx.gates.provider.set(p.ProviderKey,p);for(const b of ops.budgets||[])if(b.ProviderKey)ctx.gates.budget.set(b.ProviderKey,b);ctx.gates.learningThreshold=+ctxParam(ctx,'learning_approval_threshold',85);ctx.gates.recyclingPriority=(ctxParam(ctx,'recycling_approval_priority','HIGH') as string);ctx.gates.maxRetries=+ctxParam(ctx,'default_max_retries',3);ctx.gates.concurrency=+ctxParam(ctx,'concurrency',1)}catch(e:any){server.log?.error?.(e)}}const enabled=()=>ctxParam(ctx,'enabled',true)!==false;await refreshBootstrap();if(ctxParam(ctx,'boot_recovery',true)){try{await repo.bootRecoveryCleanup(ctx.workspaceId)}catch(e:any){server.log?.error?.(e)}}let active=false,timer:any;const start=()=>{if(active)return;active=true;const beat=()=>db.request().input('wid',sql.NVarChar(64),'api-main').input('ws',sql.UniqueIdentifier,ctx.workspaceId).query(`MERGE dbo.OrchestratorHeartbeats t USING(SELECT @wid WorkerId)s ON t.WorkerId=s.WorkerId WHEN MATCHED THEN UPDATE SET WorkspaceId=@ws,LastHeartbeat=SYSUTCDATETIME(),PollCount=ISNULL(PollCount,0)+1,Status='RUNNING',UpdatedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(WorkerId,WorkspaceId,Status,PollCount) VALUES(@wid,@ws,'RUNNING',1);`).catch(()=>{});beat();const ms=+ctxParam(ctx,'poll_interval_ms',5000);timer=setInterval(async()=>{if(!enabled())return;try{await pollOnce(ctx)}finally{try{beat();await refreshBootstrap()}catch{}}},ms);server.log?.info?.(`[orch] started poll=${ms}ms ws=${ctx.workspaceId} user=${ctx.userId}`)};const stop=()=>{active=false;if(timer){clearInterval(timer);timer=null}};if(enabled())process.nextTick(start);const engine={start,stop,_ctx:()=>ctx,_pollOnce:()=>pollOnce(ctx),_refresh:refreshBootstrap};if(typeof server.decorate==='function'){try{server.decorate('orchestrator',engine)}catch{}}return engine}
