import Fastify from 'fastify'; import cors from '@fastify/cors'; import cookie from '@fastify/cookie'; import {z} from 'zod';
import {findUserByEmail,listMemberships,listRoles,listUsers,touchLogin,writeAudit,getCommandCenter,listProjectStages,controlProject,listMyWork,updateWorkItem,listNotifications,markNotification,listContentProjects,createContentProject,getContentProject,updateContentProject,listProjectAssets,listProjectVersions,listProjectApprovals,listProjectActivities,listProjectHandoffs,archiveContentProject,listStrategyBriefs,getStrategyBrief,saveStrategyBrief,submitStrategyBrief,decideStrategyBrief,listOpportunityProjects,listOpportunities,getOpportunity,createDiscoveryRun,decideOpportunity,listResearchProjects,getResearchPack,startResearchPack,saveResearchPack,addResearchSource,updateResearchClaim,submitResearchPack,decideResearchPack,listScriptProjects,getScriptWorkspace,generateScriptConcepts,decideScriptConcept,startScriptDocument,saveScriptSections,submitScript,decideScript,listScenePlanningProjects,getProductionPlanning,startProductionPlanning,saveCharacter,saveScene,submitProductionPlanning,decideProductionPlanning,listGenerationProjects,getGenerationWorkspace,createGenerationJob,updateGenerationJob,registerGeneratedAsset,decideGeneratedAsset,completeGenerationStage,listEditingProjects,getEditingWorkspace,updateQACheck,decideMasterVideo,saveEditTimeline,addEditInstruction,createMasterVideoVersion,listPackagingProjects,getPackagingWorkspace,saveMetadataPackage,saveThumbnailVariant,decideThumbnailVariant,updatePackagingCheck,createPackagingVersion,decidePackagingVersion,queueThumbnailGeneration,saveCaptionTrack,replaceChapters,savePlatformPackage,listReleaseProjects,getReleaseWorkspace,updateReleaseCheck,decideReleaseApproval,savePublishingConnection,createPublishJob,controlPublishJob,registerPublication,listAnalyticsProjects,getAnalyticsWorkspace,ingestPerformanceSnapshot,updateAnalyticsAnomaly,decideLearningInsight,applyLearningFeedback,decideContentRecyclingPlan,getAdminOperations,saveAgentDefinition,publishWorkflowConfiguration,saveProviderIntegration,saveProviderBudget,saveNotificationPolicy,saveSystemSettings,listAdminAudit,registerAdminAsset,recordBackupRun,recordServiceHealth,getOrchestratorBootstrap,pollReadyStages,createOrchestrationRun,markOrchestrationRunRunning,completeOrchestrationRunSuccess,completeOrchestrationRunFail,recordRunEvent,listOrchestrationOverview,listProjectOrchestrationRuns,getOrchestrationRunDetail,rescueOrchestrationDeadLetter,bootRecoveryCleanup} from './repository.js'; import {requireSession,signSession,verifyPassword} from './auth.js'; import {getDb,sql} from '@cacsms/database'; import {createOrchestrationEngine} from './orchestrator.js';
const app=Fastify({logger:true}); await app.register(cors,{origin:process.env.APP_URL||'http://localhost:3000',credentials:true}); await app.register(cookie);
app.setErrorHandler((err:any,req,reply)=>{const code=err.statusCode||400;req.log.error(err);reply.code(code).send({error:code>=500?'Internal server error':err.message})});
app.get('/health',async()=>({status:'ok',service:'cacsms-cinema-api',version:'0.15.0',module01:'ready',module02:'ready',module03:'ready',module04:'ready',module05:'ready',module06:'ready',module07:'ready',module08:'ready',module09:'ready',module10:'ready',module11:'ready',module12:'ready',module13:'ready',module14:'ready',module15:'ready'}));
app.post('/api/auth/login',async(req,reply)=>{const body=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body);const user=await findUserByEmail(body.email);if(!user||!user.IsActive||!user.PasswordHash||!(await verifyPassword(body.password,user.PasswordHash))) return reply.code(401).send({error:'Invalid email or password'});const memberships=await listMemberships(user.UserId);await touchLogin(user.UserId);await writeAudit(user.UserId,null,'AUTH_LOGIN','User',JSON.stringify({email:user.Email}));const token=signSession({sub:user.UserId,email:user.Email});reply.setCookie('cacsms_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:60*60*8});return {user:{id:user.UserId,email:user.Email,name:user.DisplayName,mfaEnabled:user.MfaEnabled},workspaces:memberships}});
app.post('/api/auth/logout',async(req,reply)=>{reply.clearCookie('cacsms_session',{path:'/'});return {ok:true}});
app.get('/api/auth/me',async(req)=>{const session=requireSession(req);const user=await findUserByEmail(session.email);if(!user) throw Object.assign(new Error('User not found'),{statusCode:404});return {id:user.UserId,email:user.Email,name:user.DisplayName,mfaEnabled:user.MfaEnabled,lastLoginAt:user.LastLoginAt}});
app.get('/api/workspaces',async(req)=>{const s=requireSession(req);return {items:await listMemberships(s.sub)}});
app.post('/api/workspaces/select',async(req,reply)=>{const s=requireSession(req);const body=z.object({workspaceId:z.string().uuid()}).parse(req.body);const memberships=await listMemberships(s.sub);const m=memberships.find((x:any)=>x.WorkspaceId===body.workspaceId);if(!m) throw Object.assign(new Error('Workspace access denied'),{statusCode:403});const token=signSession({...s,workspaceId:m.WorkspaceId,role:m.RoleName});reply.setCookie('cacsms_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:60*60*8});await writeAudit(s.sub,m.WorkspaceId,'WORKSPACE_SELECTED','Workspace',JSON.stringify({role:m.RoleName}));return {ok:true,workspace:m}});
app.get('/api/admin/users',async(req)=>{const s=requireSession(req);if(!s.workspaceId) throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listUsers(s.workspaceId)}});
app.get('/api/admin/roles',async(req)=>{requireSession(req);return {items:await listRoles()}});
app.post('/api/auth/forgot-password',async(req)=>{z.object({email:z.string().email()}).parse(req.body);return {ok:true,message:'If an active account exists, recovery instructions will be issued.'}});
app.post('/api/auth/reset-password',async(req)=>{z.object({token:z.string().min(16),password:z.string().min(12)}).parse(req.body);return {ok:true,message:'Reset token accepted by contract; persistence hook is ready for email provider integration.'}});

app.get('/api/command-center',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return await getCommandCenter(s.workspaceId,s.sub)});
app.get('/api/command-center/projects/:projectId/stages',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectStages(s.workspaceId,p.projectId)}});
app.post('/api/command-center/projects/:projectId/control',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({action:z.enum(['START','PAUSE','RESUME','STOP','RESTART']),reason:z.string().max(1000).optional()}).parse(req.body);const result=await controlProject(s.workspaceId,p.projectId,s.sub,body.action,body.reason);await writeAudit(s.sub,s.workspaceId,`PROJECT_${body.action}`,'ContentProject',JSON.stringify({projectId:p.projectId,reason:body.reason||null}));return result});
app.get('/api/my-work',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listMyWork(s.workspaceId,s.sub)}});
app.patch('/api/my-work/:workItemId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({workItemId:z.string().uuid()}).parse(req.params);const body=z.object({status:z.enum(['OPEN','IN_PROGRESS','WAITING','COMPLETED','CANCELLED'])}).parse(req.body);const item=await updateWorkItem(s.workspaceId,s.sub,p.workItemId,body.status);if(!item)throw Object.assign(new Error('Work item not found'),{statusCode:404});return item});
app.get('/api/notifications',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listNotifications(s.workspaceId,s.sub)}});
app.patch('/api/notifications/:notificationId',async(req)=>{const s=requireSession(req);const p=z.object({notificationId:z.string().uuid()}).parse(req.params);const body=z.object({read:z.boolean()}).parse(req.body);const item=await markNotification(s.sub,p.notificationId,body.read);if(!item)throw Object.assign(new Error('Notification not found'),{statusCode:404});return item});


const projectInput=z.object({workingTitle:z.string().min(3).max(250),description:z.string().max(1500).optional(),contentType:z.string().min(2).max(50),primaryPlatform:z.string().min(2).max(50),targetAudience:z.string().min(3).max(500),targetCountries:z.array(z.string().max(100)).min(1),language:z.string().min(2).max(50),plannedDurationSeconds:z.number().int().positive().max(21600).optional(),aspectRatio:z.string().min(2).max(20),category:z.string().min(2).max(100),objective:z.string().min(2).max(100),priority:z.enum(['LOW','MEDIUM','HIGH','URGENT']),deadlineAt:z.string().datetime().optional(),budgetLimit:z.number().nonnegative().max(1000000).optional(),creativeDirection:z.string().max(100).optional(),autonomyMode:z.enum(['MANUAL','AI_ASSISTED','SEMI_AUTONOMOUS','AUTONOMOUS']),distributionTargets:z.array(z.object({platform:z.string().min(2).max(50),contentFormat:z.string().min(2).max(50),isPrimary:z.boolean().optional(),aspectRatio:z.string().max(20).optional(),targetDurationSeconds:z.number().int().positive().optional()})).max(12).optional()});
app.get('/api/projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const q=z.object({search:z.string().max(200).optional(),status:z.string().max(30).optional(),platform:z.string().max(50).optional(),priority:z.string().max(20).optional(),limit:z.coerce.number().int().min(1).max(200).optional(),offset:z.coerce.number().int().min(0).optional()}).parse(req.query);return await listContentProjects(s.workspaceId,q)});
app.post('/api/projects',async(req,reply)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=projectInput.parse(req.body);const project=await createContentProject(s.workspaceId,s.sub,body);await writeAudit(s.sub,s.workspaceId,'PROJECT_CREATED','ContentProject',JSON.stringify({projectId:project.ContentProjectId,contentCode:project.ContentCode}));reply.code(201);return project});
app.get('/api/projects/:projectId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const result=await getContentProject(s.workspaceId,p.projectId);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});return result});
app.patch('/api/projects/:projectId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=projectInput.partial().parse(req.body);const result=await updateContentProject(s.workspaceId,p.projectId,s.sub,body);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});await writeAudit(s.sub,s.workspaceId,'PROJECT_UPDATED','ContentProject',JSON.stringify({projectId:p.projectId}));return result});
app.get('/api/projects/:projectId/assets',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectAssets(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/versions',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectVersions(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/approvals',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectApprovals(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/activity',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectActivities(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/handoffs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectHandoffs(s.workspaceId,p.projectId)}});
app.delete('/api/projects/:projectId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const result=await archiveContentProject(s.workspaceId,p.projectId,s.sub);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});await writeAudit(s.sub,s.workspaceId,'PROJECT_ARCHIVED','ContentProject',JSON.stringify({projectId:p.projectId}));return {ok:true,...result}});


const briefInput=z.object({primaryObjective:z.string().max(120).optional(),secondaryObjectives:z.array(z.string().max(200)).max(12).optional(),audienceSummary:z.string().max(1200).optional(),audienceAgeRange:z.string().max(60).optional(),audienceKnowledgeLevel:z.string().max(80).optional(),audienceInterests:z.array(z.string().max(120)).max(30).optional(),targetCountries:z.array(z.string().max(100)).max(30).optional(),distributionPlatforms:z.array(z.string().max(60)).max(20).optional(),creativeDirection:z.string().max(120).optional(),storyApproach:z.string().max(120).optional(),voiceStyle:z.string().max(250).optional(),visualStyle:z.string().max(500).optional(),desiredDurationSeconds:z.number().int().positive().max(21600).optional(),aspectRatio:z.string().max(20).optional(),language:z.string().max(50).optional(),callToAction:z.string().max(1000).optional(),monetizationObjective:z.string().max(500).optional(),contentRestrictions:z.string().max(2000).optional(),requiredElements:z.string().max(2000).optional(),avoidElements:z.string().max(2000).optional(),referenceCreators:z.string().max(1000).optional(),researchFocus:z.string().max(2000).optional(),successDefinition:z.string().max(2000).optional(),notes:z.string().max(2000).optional(),changeSummary:z.string().max(1000).optional(),audienceSegments:z.array(z.object({segmentName:z.string().min(2).max(150),description:z.string().max(1000).optional(),ageRange:z.string().max(60).optional(),markets:z.array(z.string().max(100)).optional(),interests:z.array(z.string().max(120)).optional(),needs:z.array(z.string().max(250)).optional(),priorityOrder:z.number().int().positive().optional()})).max(12).optional(),platformStrategies:z.array(z.object({platform:z.string().min(2).max(60),contentFormat:z.string().min(2).max(80),isPrimary:z.boolean().optional(),targetDurationSeconds:z.number().int().positive().max(21600).optional(),aspectRatio:z.string().max(20).optional(),platformGoal:z.string().max(500).optional(),packagingNotes:z.string().max(1000).optional()})).max(20).optional(),references:z.array(z.object({referenceType:z.string().min(2).max(50),title:z.string().min(2).max(250),url:z.string().url().optional(),notes:z.string().max(1000).optional(),isRequired:z.boolean().optional()})).max(30).optional(),successMetrics:z.array(z.object({metricKey:z.string().min(2).max(80),displayName:z.string().min(2).max(150),targetValue:z.number().nonnegative().optional(),targetUnit:z.string().max(50).optional(),priorityOrder:z.number().int().positive().optional(),notes:z.string().max(500).optional()})).max(20).optional()});
app.get('/api/strategy-briefs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listStrategyBriefs(s.workspaceId)}});
app.get('/api/projects/:projectId/strategy-brief',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const result=await getStrategyBrief(s.workspaceId,p.projectId);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});return result});
app.put('/api/projects/:projectId/strategy-brief',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=briefInput.parse(req.body);const result=await saveStrategyBrief(s.workspaceId,p.projectId,s.sub,body);await writeAudit(s.sub,s.workspaceId,'CONTENT_BRIEF_SAVED','ContentBrief',JSON.stringify({projectId:p.projectId}));return result});
app.post('/api/projects/:projectId/strategy-brief/submit',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({changeSummary:z.string().max(1000).optional()}).parse(req.body||{});const result=await submitStrategyBrief(s.workspaceId,p.projectId,s.sub,body.changeSummary);await writeAudit(s.sub,s.workspaceId,'CONTENT_BRIEF_SUBMITTED','ContentBrief',JSON.stringify({projectId:p.projectId}));return result});
app.post('/api/projects/:projectId/strategy-brief/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(2000).optional()}).parse(req.body);const result=await decideStrategyBrief(s.workspaceId,p.projectId,s.sub,body.decision,body.comment);await writeAudit(s.sub,s.workspaceId,`CONTENT_BRIEF_${body.decision}`,'ContentBrief',JSON.stringify({projectId:p.projectId,comment:body.comment||null}));return result});


app.get('/api/opportunity-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listOpportunityProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/opportunities',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const q=z.object({status:z.string().max(30).optional(),search:z.string().max(200).optional()}).parse(req.query);return {items:await listOpportunities(s.workspaceId,p.projectId,q)}});
app.post('/api/projects/:projectId/opportunity-discovery/run',async(req,reply)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({searchScope:z.string().max(100).optional(),searchQueries:z.array(z.string().max(250)).max(20).optional(),targetMarkets:z.array(z.string().max(100)).max(20).optional(),agentProvider:z.string().max(100).optional(),agentModel:z.string().max(100).optional()}).parse(req.body||{});reply.code(201);return await createDiscoveryRun(s.workspaceId,p.projectId,s.sub,body)});
app.get('/api/opportunities/:opportunityId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({opportunityId:z.string().uuid()}).parse(req.params);const x=await getOpportunity(s.workspaceId,p.opportunityId);if(!x)throw Object.assign(new Error('Opportunity not found'),{statusCode:404});return x});
app.post('/api/opportunities/:opportunityId/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({opportunityId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['SHORTLIST','SELECT','REJECT','RESTORE']),note:z.string().max(2000).optional()}).parse(req.body);const x=await decideOpportunity(s.workspaceId,p.opportunityId,s.sub,body.decision,body.note);await writeAudit(s.sub,s.workspaceId,`OPPORTUNITY_${body.decision}`,'ContentOpportunity',JSON.stringify({opportunityId:p.opportunityId,note:body.note||null}));return x});


const researchSaveInput=z.object({researchObjective:z.string().max(1500).optional(),researchSummary:z.string().max(20000).optional(),executiveFindings:z.string().max(20000).optional(),narrativeAngles:z.string().max(20000).optional(),productionNotes:z.string().max(20000).optional(),sensitivitySummary:z.string().max(20000).optional()});
app.get('/api/research-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listResearchProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/research',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const x=await getResearchPack(s.workspaceId,p.projectId);if(!x)throw Object.assign(new Error('Project not found'),{statusCode:404});return x});
app.post('/api/projects/:projectId/research/start',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({researchObjective:z.string().max(1500).optional(),provider:z.string().max(120).optional(),model:z.string().max(120).optional()}).parse(req.body||{});return await startResearchPack(s.workspaceId,p.projectId,s.sub,b)});
app.put('/api/projects/:projectId/research',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=researchSaveInput.parse(req.body);return await saveResearchPack(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/projects/:projectId/research/sources',async(req,reply)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({sourceType:z.string().min(2).max(60),publisher:z.string().max(200).optional(),title:z.string().min(3).max(500),url:z.string().max(1500).optional(),author:z.string().max(250).optional(),sourceQuality:z.string().max(30).optional(),authorityScore:z.number().min(0).max(100).optional(),recencyScore:z.number().min(0).max(100).optional(),relevanceScore:z.number().min(0).max(100).optional(),isPrimarySource:z.boolean().optional(),notes:z.string().max(5000).optional()}).parse(req.body);reply.code(201);return await addResearchSource(s.workspaceId,p.projectId,s.sub,b)});
app.patch('/api/research/claims/:claimId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({claimId:z.string().uuid()}).parse(req.params);const b=z.object({verificationStatus:z.enum(['VERIFIED','UNVERIFIED','CONFLICTING','NEEDS_REVIEW']),confidenceScore:z.number().min(0).max(100),scriptUsageStatus:z.enum(['APPROVED','HOLD','PENDING','DO_NOT_USE']),verificationNotes:z.string().max(5000).optional()}).parse(req.body);const x=await updateResearchClaim(s.workspaceId,p.claimId,s.sub,b);if(!x)throw Object.assign(new Error('Claim not found'),{statusCode:404});return x});
app.post('/api/projects/:projectId/research/submit',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({changeSummary:z.string().max(1500).optional()}).parse(req.body||{});return await submitResearchPack(s.workspaceId,p.projectId,s.sub,b.changeSummary)});
app.post('/api/projects/:projectId/research/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(2000).optional()}).parse(req.body);const x=await decideResearchPack(s.workspaceId,p.projectId,s.sub,b.decision,b.comment);await writeAudit(s.sub,s.workspaceId,`RESEARCH_${b.decision}`,'ResearchPack',JSON.stringify({projectId:p.projectId,comment:b.comment||null}));return x});



/* Module 07 — Concept & Script Production */
app.get('/api/script-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listScriptProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/script',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const result=await getScriptWorkspace(s.workspaceId,p.projectId);if(!result)throw Object.assign(new Error('Approved Research Pack is required'),{statusCode:409});return result});
app.post('/api/projects/:projectId/script/concepts/generate',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({concepts:z.array(z.object({title:z.string().min(3),angle:z.string().optional(),hook:z.string().optional(),structure:z.array(z.string()).optional(),score:z.number().min(0).max(100).optional()})).max(10).optional()}).parse(req.body||{});return await generateScriptConcepts(s.workspaceId,p.projectId,s.sub,body)});
app.post('/api/projects/:projectId/script/concepts/:conceptId/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid(),conceptId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['SHORTLIST','SELECT','REJECT','APPROVE'])}).parse(req.body);return await decideScriptConcept(s.workspaceId,p.projectId,p.conceptId,s.sub,body.decision)});
app.post('/api/projects/:projectId/script/start',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({targetDurationSeconds:z.number().int().positive().max(21600).optional(),language:z.string().max(50).optional(),voiceMode:z.enum(['NARRATION','DIALOGUE','HYBRID']).optional(),tone:z.string().max(120).optional()}).parse(req.body||{});return await startScriptDocument(s.workspaceId,p.projectId,s.sub,body)});
app.put('/api/projects/:projectId/script/sections',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({sections:z.array(z.object({order:z.number().int().positive(),type:z.string().max(30),title:z.string().min(1).max(250),startSecond:z.number().int().nonnegative().nullable().optional(),endSecond:z.number().int().nonnegative().nullable().optional(),body:z.string(),purpose:z.string().max(1000).optional()})).min(1).max(100)}).parse(req.body);return await saveScriptSections(s.workspaceId,p.projectId,s.sub,body)});
app.post('/api/projects/:projectId/script/submit',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({changeSummary:z.string().max(1500).optional()}).parse(req.body||{});return await submitScript(s.workspaceId,p.projectId,s.sub,body.changeSummary)});
app.post('/api/projects/:projectId/script/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(5000).optional()}).parse(req.body);return await decideScript(s.workspaceId,p.projectId,s.sub,body.decision,body.comment)});

/* Module 08 — Character, Scene & Storyboard Studio */
app.get('/api/scene-planning-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listScenePlanningProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/production-planning',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const x=await getProductionPlanning(s.workspaceId,p.projectId);if(!x)throw Object.assign(new Error('Approved Script Package is required'),{statusCode:409});return x});
app.post('/api/projects/:projectId/production-planning/start',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return await startProductionPlanning(s.workspaceId,p.projectId,s.sub)});
app.post('/api/projects/:projectId/production-planning/characters',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({characterCode:z.string().min(2).max(30),characterName:z.string().min(1).max(150),characterRole:z.string().max(100).optional(),ageRange:z.string().max(50).optional(),gender:z.string().max(50).optional(),nationality:z.string().max(100).optional(),skinTone:z.string().max(100).optional(),faceDescription:z.string().max(1000).optional(),hairDescription:z.string().max(1000).optional(),buildDescription:z.string().max(1000).optional(),defaultWardrobe:z.string().max(2000).optional(),voiceProfile:z.string().max(1500).optional(),masterPrompt:z.string().max(20000).optional(),negativePrompt:z.string().max(20000).optional()}).parse(req.body);return await saveCharacter(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/projects/:projectId/production-planning/scenes',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({sceneNumber:z.number().int().positive(),sceneCode:z.string().min(2).max(30),title:z.string().min(1).max(250),chapter:z.string().max(200).optional(),startSecond:z.number().int().nonnegative(),endSecond:z.number().int().positive(),dialogue:z.string().max(20000).optional(),voiceover:z.string().max(20000).optional(),visualDescription:z.string().max(20000).optional(),shotType:z.string().max(100).optional(),cameraMovement:z.string().max(200).optional(),lens:z.string().max(100).optional(),lighting:z.string().max(1000).optional(),mood:z.string().max(1000).optional(),imagePrompt:z.string().max(30000).optional(),negativePrompt:z.string().max(30000).optional(),animationPrompt:z.string().max(30000).optional(),sfxCue:z.string().max(1500).optional(),musicCue:z.string().max(1500).optional()}).refine(x=>x.endSecond>x.startSecond,'Scene end must be after start').parse(req.body);return await saveScene(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/projects/:projectId/production-planning/submit',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return await submitProductionPlanning(s.workspaceId,p.projectId,s.sub)});
app.post('/api/projects/:projectId/production-planning/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(5000).optional()}).parse(req.body);const x=await decideProductionPlanning(s.workspaceId,p.projectId,s.sub,b.decision,b.comment);await writeAudit(s.sub,s.workspaceId,`PRODUCTION_PLANNING_${b.decision}`,'ScenePackage',JSON.stringify({projectId:p.projectId,comment:b.comment||null}));return x});


/* Module 09 — AI Generation Studio */
app.get('/api/generation-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listGenerationProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/generation',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const x=await getGenerationWorkspace(s.workspaceId,p.projectId);if(!x)throw Object.assign(new Error('Approved Character Bible and Scene Package are required'),{statusCode:409});return x});
app.post('/api/projects/:projectId/generation/jobs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({sceneId:z.string().uuid(),capability:z.enum(['IMAGE','VIDEO','VOICE','AUDIO']),providerKey:z.string().min(2).max(80),model:z.string().max(120).optional(),promptText:z.string().max(40000).optional(),negativePrompt:z.string().max(40000).optional(),fallbackProviderKey:z.string().max(80).optional(),estimatedCost:z.number().nonnegative().optional(),references:z.array(z.any()).optional(),settings:z.record(z.any()).optional()}).parse(req.body);const x=await createGenerationJob(s.workspaceId,p.projectId,s.sub,b);await writeAudit(s.sub,s.workspaceId,'GENERATION_JOB_CREATED','GenerationJob',JSON.stringify({projectId:p.projectId,jobId:x.GenerationJobId,capability:b.capability}));return x});
app.patch('/api/generation/jobs/:jobId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({jobId:z.string().uuid()}).parse(req.params);const b=z.object({status:z.enum(['QUEUED','RUNNING','IN_PROGRESS','COMPLETED','FAILED','CANCELLED']),progressPercent:z.number().min(0).max(100).optional(),externalJobId:z.string().max(250).optional(),actualCost:z.number().nonnegative().optional(),lastError:z.string().max(10000).optional()}).parse(req.body);const x=await updateGenerationJob(s.workspaceId,p.jobId,b);if(!x)throw Object.assign(new Error('Generation job not found'),{statusCode:404});return x});
app.post('/api/projects/:projectId/generation/assets',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({jobId:z.string().uuid(),assetType:z.enum(['IMAGE','VIDEO','VOICE','AUDIO']).optional(),assetRole:z.string().max(80).optional(),storageUri:z.string().min(3).max(1000),previewUri:z.string().max(1000).optional(),mimeType:z.string().max(120).optional(),durationSeconds:z.number().nonnegative().optional(),width:z.number().int().positive().optional(),height:z.number().int().positive().optional(),metadata:z.record(z.any()).optional()}).parse(req.body);return await registerGeneratedAsset(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/generation/assets/:assetId/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({assetId:z.string().uuid()}).parse(req.params);const b=z.object({decision:z.enum(['APPROVE','REJECT']),comment:z.string().max(3000).optional()}).parse(req.body);const x=await decideGeneratedAsset(s.workspaceId,p.assetId,s.sub,b.decision,b.comment);if(!x)throw Object.assign(new Error('Generated asset not found'),{statusCode:404});await writeAudit(s.sub,s.workspaceId,`GENERATED_ASSET_${b.decision}`,'GeneratedAsset',JSON.stringify({assetId:p.assetId,comment:b.comment||null}));return x});
app.post('/api/projects/:projectId/generation/complete',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return await completeGenerationStage(s.workspaceId,p.projectId,s.sub)});
app.get('/api/editing-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listEditingProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/editing',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const x=await getEditingWorkspace(s.workspaceId,p.projectId);if(!x)throw Object.assign(new Error('Editing workspace not found'),{statusCode:404});return x});
app.patch('/api/editing/qa/:checkId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({checkId:z.string().uuid()}).parse(req.params);const body=z.object({status:z.enum(['PASSED','FAILED','NEEDS_REVIEW']),evidence:z.string().max(5000).optional()}).parse(req.body);return await updateQACheck(s.workspaceId,p.checkId,s.sub,body)});
app.post('/api/projects/:projectId/editing/master-decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({masterVideoVersionId:z.string().uuid(),decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(3000).optional()}).parse(req.body);return await decideMasterVideo(s.workspaceId,p.projectId,s.sub,body)});
app.post('/api/projects/:projectId/editing/timelines',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({durationSeconds:z.number().positive().optional(),settings:z.record(z.any()).optional()}).parse(req.body);return await saveEditTimeline(s.workspaceId,p.projectId,s.sub,body)});
app.post('/api/projects/:projectId/editing/instructions',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({sceneId:z.string().uuid().optional(),timecodeSeconds:z.number().nonnegative().optional(),instructionType:z.enum(['PICTURE','AUDIO','CAPTION','GRAPHICS','TRANSITION','COLOR','OTHER']),instructionText:z.string().min(3).max(10000),ownerType:z.string().max(60).optional(),priority:z.enum(['LOW','MEDIUM','HIGH','URGENT']).optional()}).parse(req.body);return await addEditInstruction(s.workspaceId,p.projectId,s.sub,body)});
app.post('/api/projects/:projectId/editing/master-versions',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({storageUri:z.string().max(1000).optional(),reviewUri:z.string().max(1000).optional(),durationSeconds:z.number().positive().optional(),resolution:z.string().max(40).optional(),frameRate:z.number().positive().optional(),changeSummary:z.string().max(2000).optional()}).parse(req.body);return await createMasterVideoVersion(s.workspaceId,p.projectId,s.sub,body)});



/* Module 11 — Thumbnail, SEO & Platform Packaging */
app.get('/api/packaging-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listPackagingProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/packaging',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const x=await getPackagingWorkspace(s.workspaceId,p.projectId);if(!x)throw Object.assign(new Error('Approved master video required before packaging can start'),{statusCode:409});return x});
app.post('/api/projects/:projectId/packaging/metadata',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({platform:z.string().max(60).optional(),primaryTitle:z.string().min(3).max(500),description:z.string().max(20000).optional(),keywords:z.array(z.string().max(120)).max(100).optional(),tags:z.array(z.string().max(120)).max(100).optional(),hashtags:z.array(z.string().max(120)).max(30).optional(),category:z.string().max(120).optional(),language:z.string().max(80).optional(),audienceSetting:z.string().max(120).optional(),playlistName:z.string().max(250).optional(),licenseSetting:z.string().max(120).optional(),qualityScore:z.number().min(0).max(100).optional()}).parse(req.body);return await saveMetadataPackage(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/projects/:projectId/packaging/thumbnails',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({label:z.string().max(250).optional(),headline:z.string().max(150).optional(),concept:z.string().max(5000).optional(),promptText:z.string().max(20000).optional(),provider:z.string().max(120).optional(),model:z.string().max(120).optional(),assetUri:z.string().max(1000).optional(),previewUri:z.string().max(1000).optional(),overallScore:z.number().min(0).max(100).optional()}).parse(req.body);return await saveThumbnailVariant(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/packaging/thumbnails/:thumbnailId/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({thumbnailId:z.string().uuid()}).parse(req.params);const b=z.object({decision:z.enum(['APPROVE','SHORTLIST','REJECT'])}).parse(req.body);const x=await decideThumbnailVariant(s.workspaceId,p.thumbnailId,s.sub,b.decision);if(!x)throw Object.assign(new Error('Thumbnail not found'),{statusCode:404});return x});
app.patch('/api/packaging/checks/:checkId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({checkId:z.string().uuid()}).parse(req.params);const b=z.object({status:z.enum(['PASSED','FAILED','NEEDS_REVIEW']),evidence:z.string().max(5000).optional()}).parse(req.body);const x=await updatePackagingCheck(s.workspaceId,p.checkId,s.sub,b);if(!x)throw Object.assign(new Error('Packaging check not found'),{statusCode:404});return x});
app.post('/api/projects/:projectId/packaging/versions',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({platform:z.string().max(60).optional(),changeSummary:z.string().max(2000).optional()}).parse(req.body);return await createPackagingVersion(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/projects/:projectId/packaging/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({packagingVersionId:z.string().uuid(),decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(5000).optional()}).parse(req.body);const x=await decidePackagingVersion(s.workspaceId,p.projectId,s.sub,b);await writeAudit(s.sub,s.workspaceId,`PACKAGING_${b.decision}`,'PackagingVersion',JSON.stringify({projectId:p.projectId,packagingVersionId:b.packagingVersionId,comment:b.comment||null}));return x});

app.post('/api/projects/:projectId/packaging/thumbnail-jobs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({providerKey:z.string().min(2).max(80),model:z.string().max(120).optional(),promptText:z.string().min(3).max(20000),negativePrompt:z.string().max(20000).optional(),estimatedCost:z.number().nonnegative().optional(),settings:z.record(z.any()).optional()}).parse(req.body);return await queueThumbnailGeneration(s.workspaceId,p.projectId,s.sub,b)});
app.put('/api/projects/:projectId/packaging/captions',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({languageCode:z.string().min(2).max(20),languageName:z.string().min(2).max(80),trackType:z.enum(['FULL_CAPTIONS','CLEAN_TRANSCRIPT','TRANSLATED_CAPTIONS']),status:z.enum(['NOT_STARTED','DRAFT','IN_REVIEW','APPROVED','RETURNED']).optional(),coveragePercent:z.number().min(0).max(100).optional(),sourceVersion:z.string().max(120).optional(),storageUri:z.string().max(1000).optional(),format:z.string().max(50).optional()}).parse(req.body);return await saveCaptionTrack(s.workspaceId,p.projectId,s.sub,b)});
app.put('/api/projects/:projectId/packaging/chapters',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({items:z.array(z.object({startSecond:z.number().int().nonnegative(),title:z.string().min(1).max(250),sceneId:z.string().uuid().optional()})).max(100)}).parse(req.body);return await replaceChapters(s.workspaceId,p.projectId,s.sub,body.items)});
app.put('/api/projects/:projectId/packaging/platforms',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({platform:z.enum(['YouTube','YouTube Shorts','TikTok','Instagram','Facebook','X']),contentFormat:z.string().min(2).max(60),aspectRatio:z.string().max(20).optional(),durationSeconds:z.number().int().positive().optional(),title:z.string().max(500).optional(),description:z.string().max(20000).optional(),thumbnailVariantId:z.string().uuid().optional(),captionTrackId:z.string().uuid().optional(),derivativeAssetUri:z.string().max(1000).optional(),settings:z.record(z.any()).optional(),status:z.enum(['PLANNED','DRAFT','IN_REVIEW','READY','RETURNED']).optional(),packagingScore:z.number().min(0).max(100).optional()}).parse(req.body);return await savePlatformPackage(s.workspaceId,p.projectId,s.sub,b)});


/* Module 12 — Approval & Publishing */
app.get('/api/release-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listReleaseProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/release',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const x=await getReleaseWorkspace(s.workspaceId,p.projectId);if(!x)throw Object.assign(new Error('Approved packaging version required before final approval'),{statusCode:409});return x});
app.patch('/api/release/checks/:checkId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({checkId:z.string().uuid()}).parse(req.params);const b=z.object({status:z.enum(['PASSED','FAILED','NEEDS_REVIEW']),evidence:z.string().max(5000).optional()}).parse(req.body);const x=await updateReleaseCheck(s.workspaceId,p.checkId,s.sub,b);if(!x)throw Object.assign(new Error('Release check not found'),{statusCode:404});return x});
app.post('/api/projects/:projectId/release/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({approvalStepId:z.string().uuid().optional(),decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(5000).optional()}).parse(req.body);const x=await decideReleaseApproval(s.workspaceId,p.projectId,s.sub,b);await writeAudit(s.sub,s.workspaceId,`RELEASE_${b.decision}`,'ReleaseProject',JSON.stringify({projectId:p.projectId,approvalStepId:b.approvalStepId||null,comment:b.comment||null}));return x});
app.put('/api/publishing/connections',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const b=z.object({platform:z.string().min(2).max(60),connectionName:z.string().min(2).max(200),accountLabel:z.string().max(250).optional(),externalAccountId:z.string().max(250).optional(),status:z.enum(['CONNECTED','NOT_CONNECTED','DEGRADED','ERROR']).optional(),scopes:z.array(z.string().max(120)).max(30).optional(),credentialReference:z.string().max(500).optional()}).parse(req.body);return await savePublishingConnection(s.workspaceId,b)});
app.post('/api/projects/:projectId/publish-jobs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({platform:z.string().min(2).max(60),publishingConnectionId:z.string().uuid().optional(),operation:z.enum(['PUBLISH','UPDATE_METADATA','DELETE']).optional(),scheduledFor:z.string().datetime().optional(),manifest:z.record(z.any()).optional()}).parse(req.body);return await createPublishJob(s.workspaceId,p.projectId,s.sub,b)});
app.post('/api/publish-jobs/:jobId/control',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({jobId:z.string().uuid()}).parse(req.params);const b=z.object({action:z.enum(['QUEUE','RETRY','CANCEL'])}).parse(req.body);const x=await controlPublishJob(s.workspaceId,p.jobId,s.sub,b);if(!x)throw Object.assign(new Error('Publish job not found'),{statusCode:404});return x});
app.post('/api/publish-jobs/:jobId/publication',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({jobId:z.string().uuid()}).parse(req.params);const b=z.object({externalPublicationId:z.string().min(1).max(500),publicationUrl:z.string().url().optional(),publishedTitle:z.string().max(500).optional(),publishedAt:z.string().datetime().optional(),visibility:z.string().max(40).optional(),metadata:z.record(z.any()).optional()}).parse(req.body);const x=await registerPublication(s.workspaceId,p.jobId,s.sub,b);await writeAudit(s.sub,s.workspaceId,'CONTENT_PUBLISHED','Publication',JSON.stringify({jobId:p.jobId,externalPublicationId:b.externalPublicationId,platformPublicationUrl:b.publicationUrl||null}));return x});

/* Module 13 — Analytics & AI Learning */
app.get('/api/analytics-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listAnalyticsProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/analytics',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const x=await getAnalyticsWorkspace(s.workspaceId,p.projectId);if(!x)throw Object.assign(new Error('Published content required before analytics can start'),{statusCode:409});return x});
app.post('/api/projects/:projectId/analytics/snapshots',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const b=z.object({capturedAt:z.string().datetime().optional(),windowLabel:z.string().max(50).optional(),impressions:z.number().nonnegative().optional(),views:z.number().nonnegative().optional(),watchTimeMinutes:z.number().nonnegative().optional(),averageViewDurationSeconds:z.number().nonnegative().optional(),averagePercentageViewed:z.number().min(0).max(100).optional(),clickThroughRate:z.number().min(0).max(100).optional(),likes:z.number().nonnegative().optional(),comments:z.number().nonnegative().optional(),shares:z.number().nonnegative().optional(),subscribersGained:z.number().optional(),revenue:z.number().optional(),rpm:z.number().optional(),engagementRate:z.number().min(0).max(100).optional(),metadata:z.record(z.any()).optional()}).parse(req.body);return await ingestPerformanceSnapshot(s.workspaceId,p.projectId,b)});
app.patch('/api/analytics/anomalies/:anomalyId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({anomalyId:z.string().uuid()}).parse(req.params);const b=z.object({status:z.enum(['OPEN','ACKNOWLEDGED','RESOLVED']),resolution:z.string().max(3000).optional()}).parse(req.body);const x=await updateAnalyticsAnomaly(s.workspaceId,p.anomalyId,b);if(!x)throw Object.assign(new Error('Anomaly not found'),{statusCode:404});return x});
app.post('/api/analytics/insights/:insightId/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({insightId:z.string().uuid()}).parse(req.params);const b=z.object({decision:z.enum(['APPROVE','REJECT'])}).parse(req.body);const x=await decideLearningInsight(s.workspaceId,p.insightId,s.sub,b);if(!x)throw Object.assign(new Error('Insight not found'),{statusCode:404});await writeAudit(s.sub,s.workspaceId,`LEARNING_${b.decision}`,'LearningInsight',JSON.stringify({insightId:p.insightId}));return x});
app.post('/api/analytics/feedback/:feedbackId/apply',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({feedbackId:z.string().uuid()}).parse(req.params);const x=await applyLearningFeedback(s.workspaceId,p.feedbackId,s.sub);if(!x)throw Object.assign(new Error('Feedback not found'),{statusCode:404});return x});

app.post('/api/analytics/recycling/:planId/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({planId:z.string().uuid()}).parse(req.params);const b=z.object({decision:z.enum(['APPROVE','REJECT'])}).parse(req.body);const x=await decideContentRecyclingPlan(s.workspaceId,p.planId,s.sub,b);if(!x)throw Object.assign(new Error('Recycling plan not found'),{statusCode:404});return x});

/* Module 14 — Platform Administration & AI Infrastructure */
app.get('/api/admin/operations',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return await getAdminOperations(s.workspaceId)});
app.put('/api/admin/agents/:agentKey',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({agentKey:z.string().min(2).max(100)}).parse(req.params);const body=z.object({name:z.string().min(2).max(160),capability:z.string().min(2).max(80),executionMode:z.string().min(2).max(40),providerKey:z.string().max(100).optional(),modelName:z.string().max(160).optional(),status:z.string().max(30).optional(),maxConcurrency:z.number().int().min(1).max(100).optional(),maxRetries:z.number().int().min(0).max(20).optional(),monthlyBudget:z.number().nonnegative().optional(),configuration:z.record(z.any()).optional(),isEnabled:z.boolean().optional()}).parse(req.body);const result=await saveAgentDefinition(s.workspaceId,{agentKey:p.agentKey,...body});await writeAudit(s.sub,s.workspaceId,'AGENT_CONFIGURATION_UPDATED','AgentDefinition',JSON.stringify({agentKey:p.agentKey}));return result});
app.post('/api/admin/workflows/publish',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=z.object({name:z.string().max(160).optional(),configuration:z.record(z.any())}).parse(req.body);const result=await publishWorkflowConfiguration(s.workspaceId,s.sub,body);await writeAudit(s.sub,s.workspaceId,'WORKFLOW_CONFIGURATION_PUBLISHED','WorkflowConfiguration',JSON.stringify({version:result.VersionNo}));return result});
app.put('/api/admin/integrations/:providerKey',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({providerKey:z.string().min(2).max(100)}).parse(req.params);const body=z.object({displayName:z.string().min(2).max(180),providerGroup:z.enum(['AI','SOCIAL','STORAGE','OTHER']),capability:z.string().max(500).optional(),connectionStatus:z.string().max(30).optional(),healthStatus:z.string().max(30).optional(),authType:z.string().max(60).optional(),secretReference:z.string().max(400).optional(),baseUrl:z.string().url().optional(),scopes:z.array(z.string()).optional()}).parse(req.body);const result=await saveProviderIntegration(s.workspaceId,{providerKey:p.providerKey,...body});await writeAudit(s.sub,s.workspaceId,'PROVIDER_INTEGRATION_UPDATED','ProviderIntegration',JSON.stringify({providerKey:p.providerKey}));return result});
app.put('/api/admin/budgets/:providerKey',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({providerKey:z.string().min(2).max(100)}).parse(req.params);const body=z.object({budgetAmount:z.number().nonnegative(),warningPercent:z.number().min(1).max(100).optional(),hardStopPercent:z.number().min(1).max(200).optional(),currencyCode:z.string().length(3).optional(),isHardStopEnabled:z.boolean().optional()}).parse(req.body);return await saveProviderBudget(s.workspaceId,{providerKey:p.providerKey,...body})});
app.put('/api/admin/notification-policies/:policyKey',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({policyKey:z.string().min(2).max(120)}).parse(req.params);const body=z.object({name:z.string().min(2).max(180),triggerEvent:z.string().min(2).max(120),severity:z.enum(['INFO','WARNING','CRITICAL']),channels:z.string().min(2).max(300),recipientRule:z.string().min(2).max(600),escalationMinutes:z.number().int().nonnegative().optional(),isEnabled:z.boolean().optional()}).parse(req.body);return await saveNotificationPolicy(s.workspaceId,{policyKey:p.policyKey,...body})});
app.put('/api/admin/settings',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=z.object({items:z.array(z.object({key:z.string().min(2).max(160),value:z.any(),valueType:z.string().max(30).optional(),isSecret:z.boolean().optional()})).max(200)}).parse(req.body);const result=await saveSystemSettings(s.workspaceId,s.sub,body.items);await writeAudit(s.sub,s.workspaceId,'SYSTEM_SETTINGS_UPDATED','SystemSettings',JSON.stringify({count:body.items.length}));return result});
app.get('/api/admin/audit',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const q=z.object({limit:z.coerce.number().int().min(1).max(1000).optional()}).parse(req.query);return {items:await listAdminAudit(s.workspaceId,q.limit||200)}});
app.post('/api/admin/assets',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=z.object({assetKey:z.string().max(120).optional(),contentProjectId:z.string().uuid().optional(),fileName:z.string().min(1).max(500),assetType:z.string().min(2).max(50),mimeType:z.string().max(120).optional(),storageUri:z.string().max(1000).optional(),byteSize:z.number().int().nonnegative().optional(),isMaster:z.boolean().optional(),metadata:z.record(z.any()).optional()}).parse(req.body);return await registerAdminAsset(s.workspaceId,body)});
app.post('/api/admin/backups',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=z.object({backupType:z.enum(['FULL','DIFFERENTIAL','TRANSACTION_LOG','CONFIGURATION','METADATA']),targetName:z.string().max(160).optional(),storageLocation:z.string().max(1000).optional(),status:z.string().max(30).optional(),startedAt:z.string().datetime().optional(),completedAt:z.string().datetime().optional(),byteSize:z.number().int().nonnegative().optional(),isVerified:z.boolean().optional()}).parse(req.body);return await recordBackupRun(s.workspaceId,body)});
app.post('/api/admin/health-checks',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=z.object({serviceKey:z.string().min(2).max(120),status:z.enum(['HEALTHY','DEGRADED','DOWN','UNKNOWN']),latencyMs:z.number().int().nonnegative().optional(),detail:z.string().max(1000).optional()}).parse(req.body);return await recordServiceHealth(s.workspaceId,body)});

/* Module 15 — Autonomous End-to-End Production Orchestration */
app.get('/api/orchestration/overview',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return await listOrchestrationOverview(s.workspaceId)});
app.get('/api/orchestration/projects/:projectId/runs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectOrchestrationRuns(s.workspaceId,p.projectId)}});
app.get('/api/orchestration/runs/:runId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({runId:z.string().uuid()}).parse(req.params);const d=await getOrchestrationRunDetail(s.workspaceId,p.runId);if(!d?.run)throw Object.assign(new Error('Run not found'),{statusCode:404});return d});
app.post('/api/orchestration/runs/:runId/retry',async(req,reply)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({runId:z.string().uuid()}).parse(req.params);const res=await rescueOrchestrationDeadLetter(s.workspaceId,p.runId,s.sub);await writeAudit(s.sub,s.workspaceId,'ORCH_RUN_RESCUED','OrchestrationRun',JSON.stringify({runId:p.runId}));reply.code(202);return res});
app.post('/api/orchestration/seed',async(req,reply)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=z.object({projectId:z.string().uuid().optional(),capability:z.string().min(2).max(80).optional(),stageKey:z.string().min(2).max(64).optional()}).parse(req.body||{});const wf=(await getOrchestratorBootstrap(s.workspaceId)).activeWorkflow;const seedStageKey=body.stageKey||'STRATEGY_BRIEF';const seedCapability=body.capability||seedStageKey;let pid=body.projectId;if(!pid){const demo=await createContentProject(s.workspaceId,s.sub,{workingTitle:`Autonomous demo ${new Date().toISOString().slice(0,16)}`,contentType:'SHORTFORM_VIDEO',primaryPlatform:'YouTube',targetAudience:'Adults 25-34',targetCountries:['GLOBAL'],language:'English',aspectRatio:'16:9',category:'Autonomous Demo',objective:'ENGAGEMENT',priority:'MEDIUM',autonomyMode:'AUTONOMOUS'});pid=(demo as any).ContentProjectId;await writeAudit(s.sub,s.workspaceId,'PROJECT_AUTO_CREATED','ContentProject',JSON.stringify({projectId:pid,orchestrator:true}))}const run=await createOrchestrationRun(s.workspaceId,{projectId:pid,stageKey:seedStageKey,agentCapability:seedCapability,workflowVersionNo:wf?.VersionNo||1,triggeredBy:'ADMIN_SEED_v15',payloadJson:{body}});reply.code(202);return {projectId:pid,run}});

const port=Number(process.env.API_PORT??4000);app.listen({port,host:'0.0.0.0'}).then(async address=>{const db=await getDb();try{await createOrchestrationEngine(app,db,{})}catch(e:any){app.log.warn({err:e?.message},'orchestration engine boot warning (continuing API)')}app.log.info(`engine bound ${address}`)}).catch(e=>{app.log.error(e);process.exit(1)});
