import Fastify from 'fastify'; import cors from '@fastify/cors'; import cookie from '@fastify/cookie'; import {z} from 'zod';
import {findUserByEmail,listMemberships,listRoles,listUsers,touchLogin,writeAudit,getCommandCenter,listProjectStages,controlProject,listMyWork,updateWorkItem,listNotifications,markNotification,listContentProjects,createContentProject,getContentProject,updateContentProject,listProjectAssets,listProjectVersions,listProjectApprovals,listProjectActivities,listProjectHandoffs,archiveContentProject,listStrategyBriefs,getStrategyBrief,saveStrategyBrief,submitStrategyBrief,decideStrategyBrief,listOpportunityProjects,listOpportunities,getOpportunity,createDiscoveryRun,decideOpportunity} from './repository.js'; import {requireSession,signSession,verifyPassword} from './auth.js';
const app=Fastify({logger:true}); await app.register(cors,{origin:process.env.APP_URL||'http://localhost:3000',credentials:true}); await app.register(cookie);
app.setErrorHandler((err:any,req,reply)=>{const code=(err as any).statusCode||400;req.log.error(err);reply.code(code).send({error:code>=500?'Internal server error':err.message})});
app.get('/health',async()=>({status:'ok',service:'cacsms-cinemas-api',version:'0.5.0',module01:'ready',module02:'ready',module03:'ready',module04:'ready',module05:'ready'}));
app.post('/api/auth/login',async(req,reply)=>{const body=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body);const user=await findUserByEmail(body.email);if(!user||!user.IsActive||!user.PasswordHash||!(await verifyPassword(body.password,user.PasswordHash))) return reply.code(401).send({error:'Invalid email or password'});const memberships=await listMemberships(user.UserId);await touchLogin(user.UserId);await writeAudit(user.UserId,null,'AUTH_LOGIN','User',JSON.stringify({email:user.Email}));const token=signSession({sub:user.UserId,email:user.Email});reply.setCookie('cacsms_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:60*60*8});return {user:{id:user.UserId,email:user.Email,name:user.DisplayName,mfaEnabled:user.MfaEnabled},workspaces:memberships}});
app.post('/api/auth/logout',async(req,reply)=>{reply.clearCookie('cacsms_session',{path:'/'});return {ok:true}});
app.get('/api/auth/me',async(req)=>{const session=requireSession(req);const user=await findUserByEmail(session.email);if(!user) throw Object.assign(new Error('User not found'),{statusCode:404});return {id:user.UserId,email:user.Email,name:user.DisplayName,mfaEnabled:user.MfaEnabled,lastLoginAt:user.LastLoginAt}});
app.get('/api/workspaces',async(req)=>{const s=requireSession(req);return {items:await listMemberships(s.sub)}});
app.post('/api/workspaces/select',async(req,reply)=>{const s=requireSession(req);const body=z.object({workspaceId:z.string().uuid()}).parse(req.body);const memberships=await listMemberships(s.sub);const m=memberships.find((x:any)=>x.WorkspaceId===body.workspaceId);if(!m) throw Object.assign(new Error('Workspace access denied'),{statusCode:403});const token=signSession({...s,workspaceId:m.WorkspaceId,role:m.RoleName});reply.setCookie('cacsms_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:60*60*8});await writeAudit(s.sub,m.WorkspaceId,'WORKSPACE_SELECTED','Workspace',JSON.stringify({role:m.RoleName}));return {ok:true,workspace:m}});
app.get('/api/admin/users',async(req)=>{const s=requireSession(req);if(!s.workspaceId) throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listUsers(s.workspaceId)}});
app.get('/api/admin/roles',async(req)=>{requireSession(req);return {items:await listRoles()}});
app.post('/api/auth/forgot-password',async(req)=>{z.object({email:z.string().email()}).parse(req.body);return {ok:true,message:'If an active account exists, recovery instructions will be issued.'}});
app.post('/api/auth/reset-password',async(req)=>{z.object({token:z.string().min(16),password:z.string().min(12)}).parse(req.body);return {ok:true,message:'Reset token accepted by contract; persistence hook is ready for email provider integration.'}});

app.get('/api/command-center',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return await getCommandCenter(s.workspaceId,s.sub)});
app.get('/api/command-center/projects/:projectId/stages',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectStages(s.workspaceId,p.projectId)}});
app.post('/api/command-center/projects/:projectId/control',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({action:z.enum(['START','PAUSE','RESUME','STOP','RESTART']),reason:z.string().max(1000).optional()}).parse(req.body);const result=await controlProject(s.workspaceId,p.projectId,s.sub,body.action,body.reason);await writeAudit(s.sub,s.workspaceId,`PROJECT_${body.action}`,'ContentProject',JSON.stringify({projectId:p.projectId,reason:body.reason||null}));return result});
app.get('/api/my-work',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listMyWork(s.workspaceId,s.sub)}});
app.patch('/api/my-work/:workItemId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({workItemId:z.string().uuid()}).parse(req.params);const body=z.object({status:z.enum(['OPEN','IN_PROGRESS','WAITING','COMPLETED','CANCELLED'])}).parse(req.body);const item=await updateWorkItem(s.workspaceId,s.sub,p.workItemId,body.status);if(!item)throw Object.assign(new Error('Work item not found'),{statusCode:404});return item});
app.get('/api/notifications',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listNotifications(s.workspaceId,s.sub)}});
app.patch('/api/notifications/:notificationId',async(req)=>{const s=requireSession(req);const p=z.object({notificationId:z.string().uuid()}).parse(req.params);const body=z.object({read:z.boolean()}).parse(req.body);const item=await markNotification(s.sub,p.notificationId,body.read);if(!item)throw Object.assign(new Error('Notification not found'),{statusCode:404});return item});


const projectInput=z.object({workingTitle:z.string().min(3).max(250),description:z.string().max(1500).optional(),contentType:z.string().min(2).max(50),primaryPlatform:z.string().min(2).max(50),targetAudience:z.string().min(3).max(500),targetCountries:z.array(z.string().max(100)).min(1),language:z.string().min(2).max(50),plannedDurationSeconds:z.number().int().positive().max(21600).optional(),aspectRatio:z.string().min(2).max(20),category:z.string().min(2).max(100),objective:z.string().min(2).max(100),priority:z.enum(['LOW','MEDIUM','HIGH','URGENT']),deadlineAt:z.string().datetime().optional(),budgetLimit:z.number().nonnegative().max(1000000).optional(),creativeDirection:z.string().max(100).optional(),autonomyMode:z.enum(['MANUAL','AI_ASSISTED','SEMI_AUTONOMOUS','AUTONOMOUS']),distributionTargets:z.array(z.object({platform:z.string().min(2).max(50),contentFormat:z.string().min(2).max(50),isPrimary:z.boolean().optional(),aspectRatio:z.string().max(20).optional(),targetDurationSeconds:z.number().int().positive().optional()})).max(12).optional()});
app.get('/api/projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const q=z.object({search:z.string().max(200).optional(),status:z.string().max(30).optional(),platform:z.string().max(50).optional(),priority:z.string().max(20).optional(),limit:z.coerce.number().int().min(1).max(200).optional(),offset:z.coerce.number().int().min(0).optional()}).parse(req.query);return await listContentProjects(s.workspaceId,q)});
app.post('/api/projects',async(req,reply)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const body=projectInput.parse(req.body);const project=await createContentProject(s.workspaceId,s.sub,body);await writeAudit(s.sub,s.workspaceId,'PROJECT_CREATED','ContentProject',JSON.stringify({projectId:project.ContentProjectId,contentCode:project.ContentCode}));reply.code(201);return project});
app.get('/api/projects/:projectId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const result=await getContentProject(s.workspaceId,p.projectId);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});return result});
app.patch('/api/projects/:projectId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=projectInput.partial().parse(req.body);const result=await updateContentProject(s.workspaceId,p.projectId,s.sub,body);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});await writeAudit(s.sub,s.workspaceId,'PROJECT_UPDATED','ContentProject',JSON.stringify({projectId:p.projectId}));return result});
app.get('/api/projects/:projectId/assets',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectAssets(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/versions',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectVersions(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/approvals',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectApprovals(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/activity',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectActivities(s.workspaceId,p.projectId)}});
app.get('/api/projects/:projectId/handoffs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);return {items:await listProjectHandoffs(s.workspaceId,p.projectId)}});
app.delete('/api/projects/:projectId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const result=await archiveContentProject(s.workspaceId,p.projectId,s.sub);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});await writeAudit(s.sub,s.workspaceId,'PROJECT_ARCHIVED','ContentProject',JSON.stringify({projectId:p.projectId}));return {ok:true,...result}});


const briefInput=z.object({primaryObjective:z.string().max(120).optional(),secondaryObjectives:z.array(z.string().max(200)).max(12).optional(),audienceSummary:z.string().max(1200).optional(),audienceAgeRange:z.string().max(60).optional(),audienceKnowledgeLevel:z.string().max(80).optional(),audienceInterests:z.array(z.string().max(120)).max(30).optional(),targetCountries:z.array(z.string().max(100)).max(30).optional(),distributionPlatforms:z.array(z.string().max(60)).max(20).optional(),creativeDirection:z.string().max(120).optional(),storyApproach:z.string().max(120).optional(),voiceStyle:z.string().max(250).optional(),visualStyle:z.string().max(500).optional(),desiredDurationSeconds:z.number().int().positive().max(21600).optional(),aspectRatio:z.string().max(20).optional(),language:z.string().max(50).optional(),callToAction:z.string().max(1000).optional(),monetizationObjective:z.string().max(500).optional(),contentRestrictions:z.string().max(2000).optional(),requiredElements:z.string().max(2000).optional(),avoidElements:z.string().max(2000).optional(),referenceCreators:z.string().max(1000).optional(),researchFocus:z.string().max(2000).optional(),successDefinition:z.string().max(2000).optional(),notes:z.string().max(2000).optional(),changeSummary:z.string().max(1000).optional(),audienceSegments:z.array(z.object({segmentName:z.string().min(2).max(150),description:z.string().max(1000).optional(),ageRange:z.string().max(60).optional(),markets:z.array(z.string().max(100)).optional(),interests:z.array(z.string().max(120)).optional(),needs:z.array(z.string().max(250)).optional(),priorityOrder:z.number().int().positive().optional()})).max(12).optional(),platformStrategies:z.array(z.object({platform:z.string().min(2).max(60),contentFormat:z.string().min(2).max(80),isPrimary:z.boolean().optional(),targetDurationSeconds:z.number().int().positive().max(21600).optional(),aspectRatio:z.string().max(20).optional(),platformGoal:z.string().max(500).optional(),packagingNotes:z.string().max(1000).optional()})).max(20).optional(),references:z.array(z.object({referenceType:z.string().min(2).max(50),title:z.string().min(2).max(250),url:z.string().url().optional(),notes:z.string().max(1000).optional(),isRequired:z.boolean().optional()})).max(30).optional(),successMetrics:z.array(z.object({metricKey:z.string().min(2).max(80),displayName:z.string().min(2).max(150),targetValue:z.number().nonnegative().optional(),targetUnit:z.string().max(50).optional(),priorityOrder:z.number().int().positive().optional(),notes:z.string().max(500).optional()})).max(20).optional()});
app.get('/api/strategy-briefs',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listStrategyBriefs(s.workspaceId)}});
app.get('/api/projects/:projectId/strategy-brief',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const result=await getStrategyBrief(s.workspaceId,p.projectId);if(!result)throw Object.assign(new Error('Project not found'),{statusCode:404});return result});
app.put('/api/projects/:projectId/strategy-brief',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=briefInput.parse(req.body);const result=await saveStrategyBrief(s.workspaceId,p.projectId,s.sub,body);await writeAudit(s.sub,s.workspaceId,'CONTENT_BRIEF_SAVED','ContentBrief',JSON.stringify({projectId:p.projectId}));return result});
app.post('/api/projects/:projectId/strategy-brief/submit',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({changeSummary:z.string().max(1000).optional()}).parse(req.body||{});const result=await submitStrategyBrief(s.workspaceId,p.projectId,s.sub,body.changeSummary);await writeAudit(s.sub,s.workspaceId,'CONTENT_BRIEF_SUBMITTED','ContentBrief',JSON.stringify({projectId:p.projectId}));return result});
app.post('/api/projects/:projectId/strategy-brief/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['APPROVE','RETURN']),comment:z.string().max(2000).optional()}).parse(req.body);const result=await decideStrategyBrief(s.workspaceId,p.projectId,s.sub,body.decision,body.comment);await writeAudit(s.sub,s.workspaceId,`CONTENT_BRIEF_${body.decision}`,'ContentBrief',JSON.stringify({projectId:p.projectId,comment:body.comment||null}));return result});


app.get('/api/opportunity-projects',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});return {items:await listOpportunityProjects(s.workspaceId)}});
app.get('/api/projects/:projectId/opportunities',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const q=z.object({status:z.string().max(30).optional(),search:z.string().max(200).optional()}).parse(req.query);return {items:await listOpportunities(s.workspaceId,p.projectId,q)}});
app.post('/api/projects/:projectId/opportunity-discovery/run',async(req,reply)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({projectId:z.string().uuid()}).parse(req.params);const body=z.object({searchScope:z.string().max(100).optional(),searchQueries:z.array(z.string().max(250)).max(20).optional(),targetMarkets:z.array(z.string().max(100)).max(20).optional(),agentProvider:z.string().max(100).optional(),agentModel:z.string().max(100).optional()}).parse(req.body||{});reply.code(201);return await createDiscoveryRun(s.workspaceId,p.projectId,s.sub,body)});
app.get('/api/opportunities/:opportunityId',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({opportunityId:z.string().uuid()}).parse(req.params);const x=await getOpportunity(s.workspaceId,p.opportunityId);if(!x)throw Object.assign(new Error('Opportunity not found'),{statusCode:404});return x});
app.post('/api/opportunities/:opportunityId/decision',async(req)=>{const s=requireSession(req);if(!s.workspaceId)throw Object.assign(new Error('Select a workspace first'),{statusCode:409});const p=z.object({opportunityId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['SHORTLIST','SELECT','REJECT','RESTORE']),note:z.string().max(2000).optional()}).parse(req.body);const x=await decideOpportunity(s.workspaceId,p.opportunityId,s.sub,body.decision,body.note);await writeAudit(s.sub,s.workspaceId,`OPPORTUNITY_${body.decision}`,'ContentOpportunity',JSON.stringify({opportunityId:p.opportunityId,note:body.note||null}));return x});
const port=Number(process.env.API_PORT??4000);app.listen({port,host:'0.0.0.0'}).catch(e=>{app.log.error(e);process.exit(1)});
