'use client';
import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {AppShell} from '@/components/app-shell';
import {Status} from '@/components/ui';
import {apiFetch} from '@/lib/api';
import {dashboardProjects,demoAgents,demoNotifications,demoTasks,schedule,stages,type DemoProject,type ProjectStatus} from '@/lib/module02-data';
const statusLabel:Record<ProjectStatus,string>={NOT_STARTED:'Not Started',IN_PROGRESS:'In Progress',COMPLETED:'Completed',AWAITING_APPROVAL:'Awaiting Approval',PAUSED:'Paused',BLOCKED:'Blocked',FAILED:'Failed'};
const tone=(s:string)=>s==='COMPLETED'?'green':s==='IN_PROGRESS'?'amber':s==='AWAITING_APPROVAL'?'blue':s==='BLOCKED'||s==='FAILED'?'red':s==='PAUSED'?'purple':'gray';
export default function CommandCenter(){
 const [projects,setProjects]=useState(dashboardProjects); const [selected,setSelected]=useState<DemoProject|null>(null); const [view,setView]=useState<'pipeline'|'list'>('pipeline');
 useEffect(()=>{apiFetch<any>('/api/command-center').then(d=>{if(!Array.isArray(d.projects)||!d.projects.length)return;setProjects(d.projects.map((r:any)=>{const fallback=dashboardProjects.find(x=>x.code===r.ContentCode);return {id:r.ContentProjectId,code:r.ContentCode,title:r.WorkingTitle,status:r.Status,mode:String(r.AutonomyMode||'AI_ASSISTED').replaceAll('_',' '),progress:Number(r.ProgressPercent||0),completed:Number(r.CompletedStages||0),total:Number(r.TotalStages||22),stage:r.CurrentStageName||fallback?.stage||'Waiting to start',updated:'just now',owner:fallback?.owner||'Workspace team',platform:fallback?.platform||'Multi-platform',deadline:fallback?.deadline||'—'} as DemoProject}))}).catch(()=>{})},[]);
 const summary=useMemo(()=>({total:projects.length,active:projects.filter(p=>['IN_PROGRESS','AWAITING_APPROVAL','PAUSED'].includes(p.status)).length,approval:projects.filter(p=>p.status==='AWAITING_APPROVAL').length,exceptions:projects.filter(p=>['BLOCKED','FAILED'].includes(p.status)).length}),[projects]);
 const control=(id:string,action:'START'|'PAUSE'|'RESUME'|'STOP')=>{setProjects(ps=>ps.map(p=>{if(p.id!==id)return p;const status:ProjectStatus=action==='PAUSE'?'PAUSED':action==='STOP'?'NOT_STARTED':'IN_PROGRESS';const updated={...p,status,stage:action==='STOP'?'Stopped — ready to restart':p.stage,updated:'just now'};if(selected?.id===id)setSelected(updated);return updated}));apiFetch(`/api/command-center/projects/${id}/control`,{method:'POST',body:JSON.stringify({action})}).catch(()=>{})};
 return <AppShell eyebrow="COMMAND" title="Command Center" actions={<><button className="btn secondary">Export snapshot</button><button className="btn primary">＋ Create content</button></>}>
  <div className="command-title-row"><p className="page-subtitle">Your live operating view across production, approvals, agents, publishing and exceptions.</p><div className="live-indicator"><i/> LIVE · Updated now</div></div>
  <section className="command-kpis">
   <Kpi icon="▤" label="Content projects" value={summary.total} meta="5 visible in workspace" trend="+2 this week"/>
   <Kpi icon="▶" label="Active production" value={summary.active} meta="Across 3 stages" trend="2 AI agents running"/>
   <Kpi icon="✓" label="Awaiting approval" value={summary.approval} meta="Human action required" alert={summary.approval>0}/>
   <Kpi icon="!" label="Exceptions" value={summary.exceptions} meta="Blocked or failed" alert={summary.exceptions>0}/>
   <Kpi icon="✦" label="Generations today" value="86" meta="Images 64 · Video 22" trend="$18.42 est. usage"/>
   <Kpi icon="▣" label="Scheduled" value="3" meta="Next: 06 Sep · 18:00" trend="2 YouTube · 1 Short"/>
  </section>
  <div className="command-grid wide-left">
   <section className="command-card production-board"><CardHead title="Production pipeline" subtitle="Human-controlled lifecycle across every active content project" action={<div className="segmented"><button className={view==='pipeline'?'active':''} onClick={()=>setView('pipeline')}>Pipeline</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>List</button></div>}/>
    <div className="status-legend"><span><i className="dot gray"/>Not Started</span><span><i className="dot amber"/>In Progress</span><span><i className="dot green"/>Completed</span><span><i className="dot blue"/>Approval</span><span><i className="dot red"/>Blocked / Failed</span></div>
    <div className="project-stack">{projects.map(p=><ProjectRow key={p.id} p={p} onOpen={()=>setSelected(p)} onControl={control}/>)}</div>
    <button className="card-footer-link">View all content projects →</button>
   </section>
   <section className="command-card"><CardHead title="My work" subtitle="Tasks and decisions requiring your attention" action={<button className="text-action">View all →</button>}/><div className="task-list">{demoTasks.slice(0,4).map(t=><div className="task-row" key={t.id}><span className={`priority-mark ${t.priority.toLowerCase()}`}/><div className="task-main"><b>{t.title}</b><span>{t.project} · {t.stage}</span></div><Status tone={t.priority==='URGENT'?'red':t.priority==='HIGH'?'amber':'gray'}>{t.priority}</Status><small>{t.due}</small></div>)}</div></section>
  </div>
  <div className="command-grid thirds">
   <section className="command-card"><CardHead title="AI agent activity" subtitle="Current autonomous and assisted operations" action={<span className="micro-badge purple">2 running</span>}/><div className="agent-list">{demoAgents.map(a=><div className="agent-row" key={a.key}><div className="agent-orb">AI</div><div><b>{a.name}</b><span>{a.project} · {a.stage}</span></div><div className="agent-status"><Status tone={a.status==='RUNNING'?'purple':a.status==='FAILED'?'red':a.status==='WAITING'?'amber':'green'}>{a.status}</Status>{a.status==='RUNNING'&&<small>{a.progress}%</small>}</div></div>)}</div><button className="card-footer-link">Open Agent Control Center →</button></section>
   <section className="command-card"><CardHead title="Notifications" subtitle="System events and workflow alerts" action={<span className="micro-badge red">3 unread</span>}/><div className="notification-mini-list">{demoNotifications.slice(0,4).map(n=><div className={`notification-mini ${!n.read?'unread':''}`} key={n.id}><span className={`notification-symbol ${n.severity.toLowerCase()}`}>{n.severity==='CRITICAL'?'!':n.severity==='SUCCESS'?'✓':'i'}</span><div><b>{n.title}</b><p>{n.message}</p><small>{n.time}</small></div></div>)}</div><button className="card-footer-link">Open notification center →</button></section>
   <section className="command-card"><CardHead title="Publishing schedule" subtitle="Next approved and planned releases"/><div className="schedule-list">{schedule.map(s=><div className="schedule-row" key={s.code}><div className="date-tile"><b>{s.time.split(' · ')[0]}</b><span>{s.time.split(' · ')[1]}</span></div><div><span className="platform-tag">{s.platform}</span><b>{s.title}</b><small>{s.code}</small></div><Status tone={s.status==='At risk'?'red':s.status==='In production'?'amber':'blue'}>{s.status}</Status></div>)}</div><button className="card-footer-link">Open content calendar →</button></section>
  </div>
  <section className="command-card health-strip"><CardHead title="System & production health" subtitle="Operational safeguards for live production"/><div className="health-items"><Health label="API services" value="Operational" tone="green"/><Health label="MSSQL" value="Connected" tone="green"/><Health label="Generation queue" value="7 jobs" tone="purple"/><Health label="Human approvals" value="1 waiting" tone="blue"/><Health label="Budget usage" value="31% monthly" tone="green"/><Health label="Failed jobs" value="1 attention" tone="red"/></div></section>
  {selected&&<ProjectDrawer project={selected} onClose={()=>setSelected(null)} onControl={control}/>} 
 </AppShell>
}
function Kpi({icon,label,value,meta,trend,alert}:{icon:string,label:string,value:string|number,meta:string,trend?:string,alert?:boolean}){return <article className={`command-kpi ${alert?'attention':''}`}><div className="kpi-top"><span className="kpi-icon">{icon}</span>{alert&&<span className="alert-dot"/>}</div><strong>{value}</strong><b>{label}</b><span>{meta}</span>{trend&&<small>{trend}</small>}</article>}
function CardHead({title,subtitle,action}:{title:string,subtitle?:string,action?:ReactNode}){return <div className="command-card-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function ProjectRow({p,onOpen,onControl}:{p:DemoProject,onOpen:()=>void,onControl:(id:string,a:any)=>void}){return <article className="project-row"><button className="project-main-click" onClick={onOpen}><div className="project-id-line"><b>{p.code}</b><span>{p.platform}</span><span>{p.mode}</span></div><h3>{p.title}</h3><div className="project-progress-line"><div className="progress-track"><i style={{width:`${p.progress}%`}}/></div><b>{p.progress}%</b><span>{p.completed}/{p.total} stages</span></div></button><div className="project-stage"><span>Current stage</span><b>{p.stage}</b><small>Updated {p.updated}</small></div><div className="project-state"><Status tone={tone(p.status) as any}>{statusLabel[p.status]}</Status><div className="project-controls">{p.status==='NOT_STARTED'&&<button onClick={()=>onControl(p.id,'START')} title="Start">▶</button>}{p.status==='IN_PROGRESS'&&<button onClick={()=>onControl(p.id,'PAUSE')} title="Pause">Ⅱ</button>}{p.status==='PAUSED'&&<button onClick={()=>onControl(p.id,'RESUME')} title="Resume">▶</button>}{['IN_PROGRESS','PAUSED','AWAITING_APPROVAL'].includes(p.status)&&<button className="danger" onClick={()=>onControl(p.id,'STOP')} title="Stop">■</button>}<button onClick={onOpen} title="Open workflow">›</button></div></div></article>}
function ProjectDrawer({project,onClose,onControl}:{project:DemoProject,onClose:()=>void,onControl:(id:string,a:any)=>void}){const completed=Math.floor(project.progress/100*22);return <div className="modal-backdrop" onClick={onClose}><aside className="project-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">{project.code}</div><h2>{project.title}</h2><p>{project.platform} · {project.mode} · Owner: {project.owner}</p></div><button className="close" onClick={onClose}>×</button></div><div className="project-drawer-summary"><div><span>Overall progress</span><strong>{project.progress}%</strong></div><div className="progress-track large"><i style={{width:`${project.progress}%`}}/></div><div className="drawer-meta"><span><b>{project.completed}</b> completed</span><span><b>{22-project.completed}</b> remaining</span><span><b>{project.deadline}</b> deadline</span></div></div><div className="drawer-control-bar"><Status tone={tone(project.status) as any}>{statusLabel[project.status]}</Status><div>{project.status==='NOT_STARTED'&&<button className="btn primary small" onClick={()=>onControl(project.id,'START')}>▶ Start</button>}{project.status==='IN_PROGRESS'&&<button className="btn secondary small" onClick={()=>onControl(project.id,'PAUSE')}>Ⅱ Pause</button>}{project.status==='PAUSED'&&<button className="btn primary small" onClick={()=>onControl(project.id,'RESUME')}>▶ Resume</button>}{['IN_PROGRESS','PAUSED','AWAITING_APPROVAL'].includes(project.status)&&<button className="btn danger-btn small" onClick={()=>onControl(project.id,'STOP')}>■ Stop</button>}</div></div><div className="drawer-section-title"><b>22-stage production lifecycle</b><span>Output from each completed stage becomes the next stage input.</span></div><div className="stage-timeline">{stages.map((s,i)=>{const st=i<project.completed?'COMPLETED':i===project.completed&&project.status!=='COMPLETED'?project.status:'NOT_STARTED';return <div className={`stage-line ${st.toLowerCase()}`} key={s}><span className="stage-number">{String(i+1).padStart(2,'0')}</span><div><b>{s}</b><small>{i<project.completed?'Output saved & handed off':i===project.completed?'Current working stage':'Waiting for upstream output'}</small></div><Status tone={tone(st) as any}>{statusLabel[st as ProjectStatus]||st.replaceAll('_',' ')}</Status></div>})}</div></aside></div>}
function Health({label,value,tone}:{label:string,value:string,tone:string}){return <div className="health-item"><span><i className={`dot ${tone}`}/>{label}</span><b>{value}</b></div>}
