import {closeDb,getDb,sql} from './index.js';
const email=process.env.BOOTSTRAP_ADMIN_EMAIL||'pipsengine@gmail.com';
try{const db=await getDb();const base=(await db.request().input('email',sql.NVarChar(320),email).query(`SELECT TOP 1 u.UserId,w.WorkspaceId FROM dbo.Users u CROSS JOIN dbo.Workspaces w WHERE u.Email=@email AND w.Slug='cacsms-cinema'`)).recordset[0];if(!base)throw new Error('Run Module 01 bootstrap first.');
const p=(await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).query(`SELECT TOP 1 p.ContentProjectId,p.PlannedDurationSeconds FROM dbo.ContentProjects p WHERE p.WorkspaceId=@ws AND EXISTS(SELECT 1 FROM dbo.GenerationJobs g WHERE g.ContentProjectId=p.ContentProjectId) ORDER BY p.UpdatedAt DESC`)).recordset[0];if(!p)throw new Error('Run Module 09 bootstrap first.'); await db.request().input('pid',sql.UniqueIdentifier,p.ContentProjectId).input('uid',sql.UniqueIdentifier,base.UserId).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ProjectHandoffs WHERE ContentProjectId=@pid AND ToStageKey='EDIT_ASSEMBLY') INSERT dbo.ProjectHandoffs(ContentProjectId,FromStageKey,ToStageKey,OutputType,OutputReference,PayloadJson,Status,CreatedByUserId) VALUES(@pid,'VIDEO_GENERATION','EDIT_ASSEMBLY','Approved AI Generation Package',CAST(@pid AS NVARCHAR(36)),JSON_OBJECT('projectId',CAST(@pid AS NVARCHAR(36)),'bootstrapPreview',CAST(1 AS bit)),'READY',@uid)`);
let ep=(await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).input('pid',sql.UniqueIdentifier,p.ContentProjectId).query(`SELECT TOP 1 * FROM dbo.EditProjects WHERE ContentProjectId=@pid AND WorkspaceId=@ws`)).recordset[0];if(!ep){ep=(await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).input('pid',sql.UniqueIdentifier,p.ContentProjectId).input('dur',sql.Int,p.PlannedDurationSeconds||525).query(`INSERT dbo.EditProjects(WorkspaceId,ContentProjectId,Status,TargetDurationSeconds,CurrentDurationSeconds,ProgressPercent) OUTPUT INSERTED.* VALUES(@ws,@pid,'IN_PROGRESS',@dur,519,72)`)).recordset[0];}
let tl=(await db.request().input('eid',sql.UniqueIdentifier,ep.EditProjectId).query(`SELECT TOP 1 * FROM dbo.EditTimelines WHERE EditProjectId=@eid ORDER BY VersionNumber DESC`)).recordset[0];if(!tl)tl=(await db.request().input('eid',sql.UniqueIdentifier,ep.EditProjectId).input('uid',sql.UniqueIdentifier,base.UserId).query(`INSERT dbo.EditTimelines(EditProjectId,VersionNumber,Status,DurationSeconds,SettingsJson,CreatedByUserId) OUTPUT INSERTED.* VALUES(@eid,2,'IN_REVIEW',519,'{"resolution":"3840x2160","fps":24,"audioSampleRate":48000}',@uid)`)).recordset[0];
const checks=[['ASSET_COMPLETENESS','Completeness','All required scene masters present','BLOCKING','PASSED',1,'8/8 scenes have approved masters.'],['DURATION','Duration','Final duration within brief tolerance','HIGH','PASSED',0,'08:39 actual vs planned duration.'],['CAPTIONS','Captions','Caption timing and spelling','HIGH','FAILED',1,'SC-003 caption leads voiceover by 180 ms.'],['CONTINUITY','Continuity','Character / wardrobe / location continuity','BLOCKING','PASSED',1,'Approved continuity locks maintained.'],['AUDIO_LEVELS','Audio','Dialogue intelligibility and loudness','HIGH','PASSED',0,'Dialogue clear; peaks below -1 dBTP.'],['MASTER_FORMAT','Format','Master format and frame-rate consistency','BLOCKING','PASSED',1,'3840x2160 at 24 fps.'],['FACT_LINEAGE','Facts','On-screen factual claims trace to research','BLOCKING','PASSED',1,'No unsupported claims detected.'],['COPYRIGHT_METADATA','Copyright','Rights metadata complete','BLOCKING','NEEDS_REVIEW',1,'One SFX licence record requires attachment.']];
for(const c of checks)await db.request().input('eid',sql.UniqueIdentifier,ep.EditProjectId).input('key',sql.NVarChar(100),c[0]).input('cat',sql.NVarChar(60),c[1]).input('name',sql.NVarChar(250),c[2]).input('sev',sql.NVarChar(30),c[3]).input('st',sql.NVarChar(30),c[4]).input('block',sql.Bit,c[5]).input('ev',sql.NVarChar(sql.MAX),c[6]).query(`IF NOT EXISTS(SELECT 1 FROM dbo.QAChecks WHERE EditProjectId=@eid AND CheckKey=@key) INSERT dbo.QAChecks(EditProjectId,CheckKey,Category,CheckName,Severity,Status,IsBlocking,Evidence) VALUES(@eid,@key,@cat,@name,@sev,@st,@block,@ev)`);
if(!(await db.request().input('eid',sql.UniqueIdentifier,ep.EditProjectId).query(`SELECT TOP 1 1 x FROM dbo.MasterVideoVersions WHERE EditProjectId=@eid`)).recordset[0]){await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).input('pid',sql.UniqueIdentifier,p.ContentProjectId).input('eid',sql.UniqueIdentifier,ep.EditProjectId).input('tid',sql.UniqueIdentifier,tl.EditTimelineId).input('uid',sql.UniqueIdentifier,base.UserId).query(`INSERT dbo.MasterVideoVersions(WorkspaceId,ContentProjectId,EditProjectId,EditTimelineId,VersionNumber,Status,DurationSeconds,Resolution,FrameRate,ChangeSummary,CreatedByUserId) VALUES(@ws,@pid,@eid,@tid,1,'RETURNED',527,'3840x2160',24,'Initial assembly returned for caption and pacing changes.',@uid),(@ws,@pid,@eid,@tid,2,'IN_REVIEW',519,'3840x2160',24,'Pacing revised and audio balanced; QA exceptions remain.',@uid)`);}
await db.request().input('pid',sql.UniqueIdentifier,p.ContentProjectId).query(`UPDATE dbo.ProjectStageExecutions SET Status='IN_PROGRESS',ProgressPercent=72,StartedAt=COALESCE(StartedAt,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE ContentProjectId=@pid AND WorkflowStageDefinitionId IN(SELECT WorkflowStageDefinitionId FROM dbo.WorkflowStageDefinitions WHERE StageKey='EDIT_ASSEMBLY');UPDATE dbo.ProjectStageExecutions SET Status='IN_PROGRESS',ProgressPercent=75,StartedAt=COALESCE(StartedAt,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE ContentProjectId=@pid AND WorkflowStageDefinitionId IN(SELECT WorkflowStageDefinitionId FROM dbo.WorkflowStageDefinitions WHERE StageKey='QUALITY_ASSURANCE')`);
console.log('Module 10 Assembly, Editing & Quality Control bootstrap complete.');}finally{await closeDb()}
