import {closeDb,getDb,sql} from './index.js';
const email=process.env.BOOTSTRAP_ADMIN_EMAIL||'pipsengine@gmail.com';
try{const db=await getDb();const base=(await db.request().input('email',sql.NVarChar(320),email).query(`SELECT TOP 1 u.UserId,w.WorkspaceId FROM dbo.Users u CROSS JOIN dbo.Workspaces w WHERE u.Email=@email AND w.Slug='cacsms-cinema'`)).recordset[0];if(!base)throw new Error('Run Module 01 bootstrap first.');
const master=(await db.request().input('pid',sql.UniqueIdentifier,'11111111-1111-1111-1111-111111111124').query(`SELECT TOP 1 MasterVideoVersionId FROM dbo.MasterVideoVersions WHERE ContentProjectId=@pid AND Status='APPROVED' ORDER BY VersionNumber DESC`)).recordset[0];if(!master){console.log('Module 11 bootstrap skipped: approved master not found');await closeDb();process.exit(0)}
let pkg=(await db.request().input('pid',sql.UniqueIdentifier,'11111111-1111-1111-1111-111111111124').query(`SELECT TOP 1 * FROM dbo.PackagingProjects WHERE ContentProjectId=@pid`)).recordset[0];if(!pkg){pkg=(await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).input('pid',sql.UniqueIdentifier,'11111111-1111-1111-1111-111111111124').input('mv',sql.UniqueIdentifier,master.MasterVideoVersionId).query(`INSERT dbo.PackagingProjects(WorkspaceId,ContentProjectId,MasterVideoVersionId,Status,ProgressPercent) OUTPUT INSERTED.* VALUES(@ws,@pid,@mv,'IN_PROGRESS',88)`)).recordset[0]}
const pkgid=pkg.PackagingProjectId;
await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ThumbnailVariants WHERE PackagingProjectId=@pkg) BEGIN INSERT dbo.ThumbnailVariants(PackagingProjectId,VariantCode,Label,Headline,Concept,Provider,Status,IsPrimary,OverallScore,ClarityScore,EmotionScore,CuriosityScore,MobileScore,ContrastScore,ClickScore) VALUES(@pkg,'TH-201','Curiosity Face + Hidden AI','AI IS ALREADY CHOOSING','Human face with subtle AI decision layer.','Image Agent','SHORTLISTED',0,91,94,88,95,92,89,91),(@pkg,'TH-202','Everyday Life Split Screen','YOU NEVER NOTICED THIS','Everyday routine with invisible algorithm decisions.','Image Agent','APPROVED',1,94,96,90,96,95,94,95),(@pkg,'TH-203','Phone + Invisible Decisions','WHO REALLY DECIDES?','Phone close-up with branching decisions.','Image Agent','REJECTED',0,78,84,71,82,75,86,76) END`);
let meta=(await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`SELECT TOP 1 * FROM dbo.MetadataPackages WHERE PackagingProjectId=@pkg ORDER BY VersionNumber DESC`)).recordset[0];if(!meta){meta=(await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`INSERT dbo.MetadataPackages(PackagingProjectId,VersionNumber,Platform,Status,PrimaryTitle,Description,KeywordsJson,TagsJson,HashtagsJson,Category,Language,AudienceSetting,PlaylistName,LicenseSetting,QualityScore) OUTPUT INSERTED.* VALUES(@pkg,2,'YouTube','IN_REVIEW','The Hidden AI Already Running Your Everyday Life','Artificial intelligence is already shaping what we watch, buy, read and which routes we take — often without us noticing.','["artificial intelligence","AI everyday life","recommendation algorithms"]','["AI","machine learning","technology"]','["#ArtificialIntelligence","#AI","#Technology"]','Science & Technology','English','Not made for kids','AI & The Future','Standard YouTube License',94)`)).recordset[0]}
await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`IF NOT EXISTS(SELECT 1 FROM dbo.CaptionTracks WHERE PackagingProjectId=@pkg) INSERT dbo.CaptionTracks(PackagingProjectId,LanguageCode,LanguageName,TrackType,Status,CoveragePercent,SourceVersion,Format) VALUES(@pkg,'en','English','FULL_CAPTIONS','APPROVED',100,'Master transcript v2','SRT + VTT'),(@pkg,'en','English','CLEAN_TRANSCRIPT','APPROVED',100,'Master transcript v2','TXT'),(@pkg,'fr','French','TRANSLATED_CAPTIONS','NOT_STARTED',0,'Pending translation','SRT'),(@pkg,'es','Spanish','TRANSLATED_CAPTIONS','NOT_STARTED',0,'Pending translation','SRT')`);
await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ContentChapters WHERE PackagingProjectId=@pkg) INSERT dbo.ContentChapters(PackagingProjectId,ChapterOrder,StartSecond,Title,Status) VALUES(@pkg,1,0,'The AI You Never See','READY'),(@pkg,2,42,'Invisible Ranking','READY'),(@pkg,3,91,'Your Morning Commute','READY'),(@pkg,4,144,'AI at Work','READY'),(@pkg,5,195,'The Recommendation Loop','READY'),(@pkg,6,246,'The Pattern Revealed','READY'),(@pkg,7,302,'Where Human Choice Begins','READY'),(@pkg,8,370,'What Comes Next','READY')`);
await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`IF NOT EXISTS(SELECT 1 FROM dbo.PackagingChecks WHERE PackagingProjectId=@pkg) INSERT dbo.PackagingChecks(PackagingProjectId,CheckKey,CheckName,Severity,IsBlocking,Status,Evidence) VALUES(@pkg,'MASTER_LINK','Approved master video linked','BLOCKING',1,'PASSED','Approved master linked.'),(@pkg,'PRIMARY_THUMBNAIL','Primary thumbnail approved','BLOCKING',1,'PASSED','TH-202 approved.'),(@pkg,'TITLE_LIMIT','Title within platform limits','HIGH',0,'PASSED','Primary title within limits.'),(@pkg,'CAPTION_COVERAGE','Captions cover full master','BLOCKING',1,'PASSED','English coverage 100%.'),(@pkg,'PLATFORM_SETTINGS','Platform audience/category settings complete','BLOCKING',1,'NEEDS_REVIEW','Facebook and X require final audience settings.'),(@pkg,'CLAIM_GOVERNANCE','No unsupported factual claim added','BLOCKING',1,'PASSED','Metadata remains within approved claim scope.')`);

const primaryThumb=(await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`SELECT TOP 1 ThumbnailVariantId FROM dbo.ThumbnailVariants WHERE PackagingProjectId=@pkg AND IsPrimary=1`)).recordset[0];
const enCap=(await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`SELECT TOP 1 CaptionTrackId FROM dbo.CaptionTracks WHERE PackagingProjectId=@pkg AND LanguageCode='en' AND TrackType='FULL_CAPTIONS'`)).recordset[0];
await db.request().input('pkg',sql.UniqueIdentifier,pkgid).input('th',sql.UniqueIdentifier,primaryThumb?.ThumbnailVariantId||null).input('cap',sql.UniqueIdentifier,enCap?.CaptionTrackId||null).query(`IF NOT EXISTS(SELECT 1 FROM dbo.PlatformPackages WHERE PackagingProjectId=@pkg) INSERT dbo.PlatformPackages(PackagingProjectId,Platform,ContentFormat,AspectRatio,DurationSeconds,Title,ThumbnailVariantId,CaptionTrackId,Status,PackagingScore,SettingsJson) VALUES(@pkg,'YouTube','Long Form','16:9',519,'The Hidden AI Already Running Your Everyday Life',@th,@cap,'READY',96,'{}'),(@pkg,'YouTube Shorts','Short','9:16',59,'AI Is Already Making These Decisions for You',NULL,NULL,'DRAFT',88,'{}'),(@pkg,'TikTok','Short','9:16',46,'You Use AI Before Breakfast Without Knowing It',NULL,NULL,'DRAFT',86,'{}'),(@pkg,'Instagram','Reel','9:16',60,'The Invisible AI in Your Everyday Life',NULL,NULL,'DRAFT',87,'{}'),(@pkg,'Facebook','Video','16:9',190,'How Invisible AI Shapes Everyday Choices',@th,@cap,'PLANNED',82,'{}'),(@pkg,'X','Video','16:9',132,'The AI decisions happening around you every day',@th,NULL,'PLANNED',80,'{}')`);

const thumb=(await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`SELECT TOP 1 ThumbnailVariantId FROM dbo.ThumbnailVariants WHERE PackagingProjectId=@pkg AND IsPrimary=1`)).recordset[0];if(!((await db.request().input('pkg',sql.UniqueIdentifier,pkgid).query(`SELECT COUNT(*) C FROM dbo.PackagingVersions WHERE PackagingProjectId=@pkg`)).recordset[0].C)){await db.request().input('pkg',sql.UniqueIdentifier,pkgid).input('th',sql.UniqueIdentifier,thumb?.ThumbnailVariantId||null).input('md',sql.UniqueIdentifier,meta.MetadataPackageId).query(`INSERT dbo.PackagingVersions(PackagingProjectId,VersionNumber,Status,PrimaryThumbnailVariantId,MetadataPackageId,ManifestJson,ChangeSummary) VALUES(@pkg,1,'RETURNED',@th,@md,'{}','Initial package returned for title/thumbnail changes.'),(@pkg,2,'IN_REVIEW',@th,@md,'{}','Claims corrected and primary YouTube package ready; platform settings remain.')`)}
console.log('Module 11 packaging bootstrap complete');await closeDb();process.exit(0)}catch(e){console.error(e);process.exit(1)}
