import {loadRootEnv} from './load-env.js';
import {closeDb,getDb,sql} from './index.js';
loadRootEnv({override:true});
const email=process.env.BOOTSTRAP_ADMIN_EMAIL||'cacsms@cacsms.com';
try{
 const db=await getDb();
 const ids=await db.request().input('email',sql.NVarChar(320),email).query(`SELECT u.UserId,w.WorkspaceId FROM dbo.Users u CROSS JOIN dbo.Workspaces w WHERE u.Email=@email AND w.Slug='cacsms-cinema'`);
 const row=ids.recordset[0]; if(!row) throw new Error('Run Module 01 bootstrap first.'); const uid=row.UserId,ws=row.WorkspaceId;
 const projects=[
  ['CAC-2026-000124','The Hidden AI Already Running Your Everyday Life','IN_PROGRESS','AI_ASSISTED'],
  ['CAC-2026-000123','What Happens When AI Becomes Your Boss?','AWAITING_APPROVAL','SEMI_AUTONOMOUS'],
  ['CAC-2026-000122','The Robot Waiter That Changed a Restaurant','PAUSED','AI_ASSISTED'],
  ['CAC-2026-000121','7 Things Your Smartphone Knows About You','BLOCKED','AI_ASSISTED'],
  ['CAC-2026-000120','Why One Day on Venus Is Longer Than Its Year','COMPLETED','SEMI_AUTONOMOUS']
 ];
 for(const [code,title,status,mode] of projects){await db.request().input('ws',sql.UniqueIdentifier,ws).input('uid',sql.UniqueIdentifier,uid).input('code',sql.NVarChar(30),code).input('title',sql.NVarChar(250),title).input('status',sql.NVarChar(30),status).input('mode',sql.NVarChar(30),mode).query(`IF NOT EXISTS(SELECT 1 FROM dbo.ContentProjects WHERE WorkspaceId=@ws AND ContentCode=@code) INSERT dbo.ContentProjects(WorkspaceId,ContentCode,WorkingTitle,Status,AutonomyMode,OwnerUserId) VALUES(@ws,@code,@title,@status,@mode,@uid) ELSE UPDATE dbo.ContentProjects SET WorkingTitle=@title,Status=@status,AutonomyMode=@mode,OwnerUserId=@uid,UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@ws AND ContentCode=@code`)}
 const prog:any={'CAC-2026-000124':[9,48,'IMAGE_GENERATION'],'CAC-2026-000123':[17,77,'FINAL_APPROVAL'],'CAC-2026-000122':[8,41,'VIDEO_GENERATION'],'CAC-2026-000121':[5,28,'FACT_CHECK'],'CAC-2026-000120':[22,100,'CONTENT_RECYCLING']};
 for(const code of Object.keys(prog)){const [done,pct,current]=prog[code];await db.request().input('ws',sql.UniqueIdentifier,ws).input('code',sql.NVarChar(30),code).input('done',sql.Int,done).input('pct',sql.Decimal(5,2),pct).input('current',sql.NVarChar(80),current).query(`DECLARE @p UNIQUEIDENTIFIER=(SELECT ContentProjectId FROM dbo.ContentProjects WHERE WorkspaceId=@ws AND ContentCode=@code); MERGE dbo.ProjectStageExecutions t USING(SELECT @p ContentProjectId,d.WorkflowStageDefinitionId,d.StageOrder,d.StageKey FROM dbo.WorkflowStageDefinitions d WHERE d.IsActive=1)s ON t.ContentProjectId=s.ContentProjectId AND t.WorkflowStageDefinitionId=s.WorkflowStageDefinitionId WHEN MATCHED THEN UPDATE SET Status=CASE WHEN s.StageOrder<=@done THEN 'COMPLETED' WHEN s.StageKey=@current THEN CASE WHEN @code='CAC-2026-000123' THEN 'AWAITING_APPROVAL' WHEN @code='CAC-2026-000122' THEN 'PAUSED' WHEN @code='CAC-2026-000121' THEN 'BLOCKED' ELSE 'IN_PROGRESS' END ELSE 'NOT_STARTED' END,ProgressPercent=CASE WHEN s.StageOrder<=@done THEN 100 WHEN s.StageKey=@current THEN @pct ELSE 0 END,UpdatedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(ContentProjectId,WorkflowStageDefinitionId,Status,ProgressPercent) VALUES(s.ContentProjectId,s.WorkflowStageDefinitionId,CASE WHEN s.StageOrder<=@done THEN 'COMPLETED' WHEN s.StageKey=@current THEN CASE WHEN @code='CAC-2026-000123' THEN 'AWAITING_APPROVAL' WHEN @code='CAC-2026-000122' THEN 'PAUSED' WHEN @code='CAC-2026-000121' THEN 'BLOCKED' ELSE 'IN_PROGRESS' END ELSE 'NOT_STARTED' END,CASE WHEN s.StageOrder<=@done THEN 100 WHEN s.StageKey=@current THEN @pct ELSE 0 END);`) }
 const work=[['Approve final content package','APPROVAL','URGENT','FINAL_APPROVAL','CAC-2026-000123'],['Resolve conflicting source claim','EXCEPTION','HIGH','FACT_CHECK','CAC-2026-000121'],['Review image variants for scenes 10–14','REVIEW','HIGH','IMAGE_GENERATION','CAC-2026-000124'],['Choose video provider fallback','DECISION','MEDIUM','VIDEO_GENERATION','CAC-2026-000122']];
 for(const [title,type,priority,stage,code] of work){await db.request().input('ws',sql.UniqueIdentifier,ws).input('uid',sql.UniqueIdentifier,uid).input('title',sql.NVarChar(220),title).input('type',sql.NVarChar(40),type).input('priority',sql.NVarChar(20),priority).input('stage',sql.NVarChar(80),stage).input('code',sql.NVarChar(30),code).query(`IF NOT EXISTS(SELECT 1 FROM dbo.WorkItems WHERE WorkspaceId=@ws AND Title=@title) INSERT dbo.WorkItems(WorkspaceId,ContentProjectId,StageKey,Title,WorkType,Priority,AssignedUserId,DueAt) SELECT @ws,ContentProjectId,@stage,@title,@type,@priority,@uid,DATEADD(hour,24,SYSUTCDATETIME()) FROM dbo.ContentProjects WHERE WorkspaceId=@ws AND ContentCode=@code`)}
 const notes=[['Workflow','CRITICAL','Project blocked at Fact Check','CAC-2026-000121 has a conflicting factual claim that requires human resolution before the workflow can continue.'],['Approval','WARNING','Final approval is waiting','What Happens When AI Becomes Your Boss? is ready for final human approval.'],['Generation','INFO','Image batch completed','Scenes 10–14 generated image variants and require selection.']];for(const [cat,sev,title,msg] of notes){await db.request().input('ws',sql.UniqueIdentifier,ws).input('uid',sql.UniqueIdentifier,uid).input('cat',sql.NVarChar(40),cat).input('sev',sql.NVarChar(20),sev).input('title',sql.NVarChar(220),title).input('msg',sql.NVarChar(1500),msg).query(`IF NOT EXISTS(SELECT 1 FROM dbo.Notifications WHERE UserId=@uid AND Title=@title) INSERT dbo.Notifications(WorkspaceId,UserId,Category,Severity,Title,Message) VALUES(@ws,@uid,@cat,@sev,@title,@msg)`)}
 const agents=[['image-agent','Image Director','IMAGE_GENERATION','RUNNING',72,'CAC-2026-000124'],['continuity-agent','Continuity Guardian','IMAGE_GENERATION','RUNNING',83,'CAC-2026-000124'],['publishing-agent','Publishing Agent','PUBLISHING','WAITING',0,'CAC-2026-000123'],['fact-agent','Fact Checker','FACT_CHECK','FAILED',63,'CAC-2026-000121'],['analytics-agent','Analytics Agent','PERFORMANCE','ONLINE',0,null]];for(const [key,name,stage,status,progress,code] of agents as any[]){await db.request().input('ws',sql.UniqueIdentifier,ws).input('key',sql.NVarChar(100),key).input('name',sql.NVarChar(150),name).input('stage',sql.NVarChar(80),stage).input('status',sql.NVarChar(30),status).input('progress',sql.Decimal(5,2),progress).input('code',sql.NVarChar(30),code).query(`IF NOT EXISTS(SELECT 1 FROM dbo.AgentRuns WHERE WorkspaceId=@ws AND AgentKey=@key AND Status=@status) INSERT dbo.AgentRuns(WorkspaceId,ContentProjectId,AgentKey,AgentName,StageKey,Status,ProgressPercent,Provider) SELECT @ws,(SELECT ContentProjectId FROM dbo.ContentProjects WHERE WorkspaceId=@ws AND ContentCode=@code),@key,@name,@stage,@status,@progress,'Cacsms Agent'`)}
 await db.request().input('ws',sql.UniqueIdentifier,ws).query(`IF NOT EXISTS(SELECT 1 FROM dbo.GenerationUsage WHERE WorkspaceId=@ws) BEGIN DECLARE @i INT=0; WHILE @i<86 BEGIN INSERT dbo.GenerationUsage(WorkspaceId,UsageType,Provider,Quantity,EstimatedCost) VALUES(@ws,CASE WHEN @i<64 THEN 'IMAGE' ELSE 'VIDEO' END,'Subscription Agent',1,CASE WHEN @i<64 THEN .08 ELSE .60 END); SET @i=@i+1; END END`);
 for(const [code,platform,days] of [['CAC-2026-000123','YOUTUBE',2],['CAC-2026-000124','YOUTUBE',4],['CAC-2026-000122','YOUTUBE_SHORTS',5]] as any[]){await db.request().input('ws',sql.UniqueIdentifier,ws).input('code',sql.NVarChar(30),code).input('platform',sql.NVarChar(50),platform).input('days',sql.Int,days).query(`DECLARE @p UNIQUEIDENTIFIER=(SELECT ContentProjectId FROM dbo.ContentProjects WHERE WorkspaceId=@ws AND ContentCode=@code);IF NOT EXISTS(SELECT 1 FROM dbo.PublishingSchedule WHERE ContentProjectId=@p AND Platform=@platform) INSERT dbo.PublishingSchedule(WorkspaceId,ContentProjectId,Platform,ScheduledAt) VALUES(@ws,@p,@platform,DATEADD(day,@days,SYSUTCDATETIME()))`)}
 console.log('Module 02 command-center demo/operational bootstrap complete.');
}finally{await closeDb()}
