import {closeDb,getDb,sql} from './index.js';
const email=process.env.BOOTSTRAP_ADMIN_EMAIL||'pipsengine@gmail.com';
try{
  const db=await getDb();
  const base=(await db.request().input('email',sql.NVarChar(320),email).query(`SELECT TOP 1 u.UserId,w.WorkspaceId FROM dbo.Users u CROSS JOIN dbo.Workspaces w WHERE u.Email=@email AND w.Slug='cacsms-cinema'`)).recordset[0];
  if(!base)throw new Error('Run Module 01 bootstrap first.');
  const p=(await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).query(`SELECT TOP 1 p.ContentProjectId,sp.ScenePackageId,sp.ApprovedVersionId ScenePackageVersionId,cb.CharacterBibleId,cb.ApprovedVersionId CharacterBibleVersionId FROM dbo.ContentProjects p JOIN dbo.ScenePackages sp ON sp.ContentProjectId=p.ContentProjectId JOIN dbo.CharacterBibles cb ON cb.ContentProjectId=p.ContentProjectId WHERE p.WorkspaceId=@ws ORDER BY p.UpdatedAt DESC`)).recordset[0];
  if(!p)throw new Error('Run Module 08 bootstrap first.');
  let spv=p.ScenePackageVersionId; let cbv=p.CharacterBibleVersionId;
  if(!spv){const v=(await db.request().input('sp',sql.UniqueIdentifier,p.ScenePackageId).query(`SELECT TOP 1 ScenePackageVersionId FROM dbo.ScenePackageVersions WHERE ScenePackageId=@sp ORDER BY VersionNumber DESC`)).recordset[0];spv=v?.ScenePackageVersionId;}
  if(!cbv){const v=(await db.request().input('cb',sql.UniqueIdentifier,p.CharacterBibleId).query(`SELECT TOP 1 CharacterBibleVersionId FROM dbo.CharacterBibleVersions WHERE CharacterBibleId=@cb ORDER BY VersionNumber DESC`)).recordset[0];cbv=v?.CharacterBibleVersionId;}
  if(!spv||!cbv)throw new Error('Approved production versions are required.');
  await db.request().input('sp',sql.UniqueIdentifier,p.ScenePackageId).input('spv',sql.UniqueIdentifier,spv).input('cb',sql.UniqueIdentifier,p.CharacterBibleId).input('cbv',sql.UniqueIdentifier,cbv).input('uid',sql.UniqueIdentifier,base.UserId).input('pid',sql.UniqueIdentifier,p.ContentProjectId).query(`UPDATE dbo.ScenePackages SET Status='APPROVED',ApprovedVersionId=@spv,ApprovedByUserId=@uid,ApprovedAt=COALESCE(ApprovedAt,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE ScenePackageId=@sp; UPDATE dbo.ScenePackageVersions SET Status='APPROVED',ReviewedByUserId=@uid,ReviewedAt=COALESCE(ReviewedAt,SYSUTCDATETIME()) WHERE ScenePackageVersionId=@spv; UPDATE dbo.CharacterBibles SET Status='APPROVED',ApprovedVersionId=@cbv,ApprovedByUserId=@uid,ApprovedAt=COALESCE(ApprovedAt,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE CharacterBibleId=@cb; UPDATE dbo.CharacterBibleVersions SET Status='APPROVED',ReviewedByUserId=@uid,ReviewedAt=COALESCE(ReviewedAt,SYSUTCDATETIME()) WHERE CharacterBibleVersionId=@cbv; UPDATE dbo.ProjectStageExecutions SET Status='COMPLETED',ProgressPercent=100,CompletedAt=COALESCE(CompletedAt,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE ContentProjectId=@pid AND WorkflowStageDefinitionId IN(SELECT WorkflowStageDefinitionId FROM dbo.WorkflowStageDefinitions WHERE StageKey IN('CHARACTER_BIBLE','SCENE_MATRIX'))`);
  const providers:any[]=[['OPENAI_IMAGE','Image Agent Subscription','IMAGE','configured-image-model',1,1],['GOOGLE_VIDEO','Video Agent Subscription','VIDEO','configured-video-model',1,1],['ELEVENLABS','Voice Agent','VOICE','multilingual-v2',0,1],['AUDIO_AGENT','Music & SFX Agent','AUDIO','production-audio',0,1]];
  for(const x of providers)await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).input('key',sql.NVarChar(80),x[0]).input('name',sql.NVarChar(160),x[1]).input('cap',sql.NVarChar(40),x[2]).input('model',sql.NVarChar(120),x[3]).input('refs',sql.Bit,x[4]).input('batch',sql.Bit,x[5]).query(`IF NOT EXISTS(SELECT 1 FROM dbo.GenerationProviders WHERE WorkspaceId=@ws AND ProviderKey=@key) INSERT dbo.GenerationProviders(WorkspaceId,ProviderKey,DisplayName,Capability,DefaultModel,SupportsReferences,SupportsBatch) VALUES(@ws,@key,@name,@cap,@model,@refs,@batch)`);
  const scenes=(await db.request().input('sp',sql.UniqueIdentifier,p.ScenePackageId).query(`SELECT TOP 5 SceneId,SceneCode,ImagePrompt,NegativePrompt,AnimationPrompt,Dialogue,Voiceover,DurationSeconds FROM dbo.Scenes WHERE ScenePackageId=@sp ORDER BY SceneNumber`)).recordset;
  for(let i=0;i<scenes.length;i++){
    const s=scenes[i]; const states=i===0?'COMPLETED':i===1?'IN_PROGRESS':i===2?'FAILED':'QUEUED';
    await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).input('pid',sql.UniqueIdentifier,p.ContentProjectId).input('scene',sql.UniqueIdentifier,s.SceneId).input('spv',sql.UniqueIdentifier,spv).input('cbv',sql.UniqueIdentifier,cbv).input('status',sql.NVarChar(30),states).input('prompt',sql.NVarChar(sql.MAX),s.ImagePrompt||'').input('neg',sql.NVarChar(sql.MAX),s.NegativePrompt||'').input('uid',sql.UniqueIdentifier,base.UserId).query(`IF NOT EXISTS(SELECT 1 FROM dbo.GenerationJobs WHERE ContentProjectId=@pid AND SceneId=@scene AND Capability='IMAGE') INSERT dbo.GenerationJobs(WorkspaceId,ContentProjectId,SceneId,ScenePackageVersionId,CharacterBibleVersionId,Capability,ProviderKey,Model,PromptText,NegativePrompt,ReferenceJson,SettingsJson,Status,ProgressPercent,EstimatedCost,CreatedByUserId,StartedAt,CompletedAt) VALUES(@ws,@pid,@scene,@spv,@cbv,'IMAGE','OPENAI_IMAGE','configured-image-model',@prompt,@neg,'["character-lock","location-lock"]','{"aspectRatio":"16:9","resolution":"4K"}',@status,CASE WHEN @status='COMPLETED' THEN 100 WHEN @status='IN_PROGRESS' THEN 48 WHEN @status='FAILED' THEN 100 ELSE 0 END,.18,@uid,CASE WHEN @status IN('COMPLETED','IN_PROGRESS','FAILED') THEN SYSUTCDATETIME() ELSE NULL END,CASE WHEN @status IN('COMPLETED','FAILED') THEN SYSUTCDATETIME() ELSE NULL END)`);
    if(i<2)await db.request().input('ws',sql.UniqueIdentifier,base.WorkspaceId).input('pid',sql.UniqueIdentifier,p.ContentProjectId).input('scene',sql.UniqueIdentifier,s.SceneId).input('jid',sql.UniqueIdentifier,(await db.request().input('pid2',sql.UniqueIdentifier,p.ContentProjectId).input('scene2',sql.UniqueIdentifier,s.SceneId).query(`SELECT TOP 1 GenerationJobId FROM dbo.GenerationJobs WHERE ContentProjectId=@pid2 AND SceneId=@scene2 AND Capability='IMAGE' ORDER BY QueuedAt DESC`)).recordset[0].GenerationJobId).input('uri',sql.NVarChar(1000),`seed://module09/${s.SceneCode.toLowerCase()}/image-master.png`).input('uid',sql.UniqueIdentifier,base.UserId).query(`IF NOT EXISTS(SELECT 1 FROM dbo.GeneratedAssets WHERE ContentProjectId=@pid AND SceneId=@scene AND AssetType='IMAGE' AND IsMaster=1) INSERT dbo.GeneratedAssets(WorkspaceId,ContentProjectId,SceneId,GenerationJobId,AssetType,AssetRole,StorageUri,MimeType,Width,Height,VersionNumber,ApprovalStatus,IsMaster,ApprovedByUserId,ApprovedAt) VALUES(@ws,@pid,@scene,@jid,'IMAGE','SCENE_MASTER',@uri,'image/png',3840,2160,1,'APPROVED',1,@uid,SYSUTCDATETIME())`);
  }
  await db.request().input('pid',sql.UniqueIdentifier,p.ContentProjectId).query(`UPDATE dbo.ProjectStageExecutions SET Status='IN_PROGRESS',ProgressPercent=45,StartedAt=COALESCE(StartedAt,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE ContentProjectId=@pid AND WorkflowStageDefinitionId IN(SELECT WorkflowStageDefinitionId FROM dbo.WorkflowStageDefinitions WHERE StageKey IN('IMAGE_GENERATION','VIDEO_GENERATION','VOICE_DIALOGUE','MUSIC_SFX'))`);
  console.log('Module 09 AI Generation Studio bootstrap complete.');
}finally{await closeDb()}
