-- Research & Evidence Stage 04 (MSSQL)
-- No fabricated sources, claims, citations, scores, or acknowledgements.

IF OBJECT_ID(N'[dbo].[re_intake_packages]', N'U') IS NOT NULL
BEGIN
  PRINT 'Research & Evidence tables already exist; skipping.';
END
ELSE
BEGIN
SET XACT_ABORT ON; BEGIN TRANSACTION;
CREATE TABLE re_intake_packages(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,source_run_id uniqueidentifier NOT NULL,strategy_version_id uniqueidentifier NOT NULL,checksum char(64) NOT NULL,package_json nvarchar(max) NOT NULL CHECK(isjson(package_json)=1),status varchar(20) NOT NULL CHECK(status IN('RECEIVED','ACKNOWLEDGED','REJECTED')),received_at datetime2 NOT NULL DEFAULT sysutcdatetime(),acknowledged_at datetime2 NULL,CONSTRAINT UQ_re_intake UNIQUE(source_run_id,checksum));
CREATE TABLE re_cycles(id uniqueidentifier NOT NULL PRIMARY KEY,intake_package_id uniqueidentifier NOT NULL REFERENCES re_intake_packages(id),idempotency_key varchar(100) NOT NULL UNIQUE,status varchar(30) NOT NULL CHECK(status IN('QUEUED','RUNNING','COMPLETED','PARTIAL','FAILED','BLOCKED','CANCELLED')),started_at datetime2 NULL,completed_at datetime2 NULL,failure_reason nvarchar(2000),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),row_version rowversion);
CREATE TABLE re_candidates(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NOT NULL REFERENCES re_cycles(id),upstream_opportunity_id uniqueidentifier NOT NULL,title nvarchar(300) NOT NULL,summary nvarchar(max) NOT NULL,domain nvarchar(160) NOT NULL,geography nvarchar(160),audience nvarchar(160),format_hint nvarchar(100),status varchar(30) NOT NULL CHECK(status IN('RECEIVED','NORMALISING','EVALUATING','QUALIFIED','REJECTED','BLOCKED','SELECTED','HANDED_OFF','ARCHIVED')),score decimal(6,2) NOT NULL DEFAULT 0,confidence decimal(5,2) NOT NULL DEFAULT 0,gate_status varchar(20) NOT NULL DEFAULT 'NOT_EVALUATED',decision varchar(20),decision_reason nvarchar(2000),source_payload_json nvarchar(max) NOT NULL CHECK(isjson(source_payload_json)=1),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),updated_at datetime2 NOT NULL DEFAULT sysutcdatetime(),row_version rowversion,CONSTRAINT UQ_re_upstream_candidate UNIQUE(cycle_id,upstream_opportunity_id));
CREATE TABLE re_evidence_checks(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),rule_code varchar(100) NOT NULL,rule_version int NOT NULL,status varchar(20) NOT NULL,severity varchar(20) NOT NULL,blocking bit NOT NULL,evidence_json nvarchar(max),checked_at datetime2 NOT NULL DEFAULT sysutcdatetime(),CONSTRAINT UQ_re_evidence_rule UNIQUE(candidate_id,rule_code,rule_version));
CREATE TABLE re_duplicate_checks(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),compared_asset_type varchar(30) NOT NULL,compared_asset_id uniqueidentifier NOT NULL,similarity decimal(5,2) NOT NULL,model_version varchar(80) NOT NULL,blocking bit NOT NULL,explanation nvarchar(max),checked_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_risk_assessments(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),category varchar(40) NOT NULL,severity varchar(20) NOT NULL,likelihood decimal(5,2) NOT NULL,risk_score decimal(5,2) NOT NULL,blocking bit NOT NULL,mitigation nvarchar(2000),evidence_json nvarchar(max),assessed_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_scores(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),model_version varchar(80) NOT NULL,factors_json nvarchar(max) NOT NULL CHECK(isjson(factors_json)=1),weights_json nvarchar(max) NOT NULL CHECK(isjson(weights_json)=1),thresholds_json nvarchar(max) NOT NULL CHECK(isjson(thresholds_json)=1),total_score decimal(6,2) NOT NULL,confidence decimal(5,2) NOT NULL,explanation nvarchar(max),scored_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_gate_results(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),score_id uniqueidentifier NOT NULL REFERENCES re_scores(id),gate_code varchar(100) NOT NULL,actual_value decimal(8,2),required_value nvarchar(100),status varchar(20) NOT NULL,blocking bit NOT NULL,explanation nvarchar(max),evaluated_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_rankings(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NOT NULL REFERENCES re_cycles(id),candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),rank_position int NOT NULL,portfolio_effect_json nvarchar(max),ranked_at datetime2 NOT NULL DEFAULT sysutcdatetime(),CONSTRAINT UQ_re_rank_position UNIQUE(cycle_id,rank_position),CONSTRAINT UQ_re_rank_candidate UNIQUE(cycle_id,candidate_id));
CREATE TABLE re_decisions(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),decision varchar(20) NOT NULL CHECK(decision IN('QUALIFY','REJECT','BLOCK','REASSESS')),reason nvarchar(2000) NOT NULL,decision_source varchar(30) NOT NULL DEFAULT 'SYSTEM',policy_version varchar(80),score_id uniqueidentifier NULL REFERENCES re_scores(id),created_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_handoffs(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,candidate_id uniqueidentifier NOT NULL REFERENCES re_candidates(id),status varchar(30) NOT NULL CHECK(status IN('PENDING','DISPATCHED','ACKNOWLEDGED','FAILED','BLOCKED')),idempotency_key varchar(100) NOT NULL UNIQUE,checksum char(64) NOT NULL,payload_json nvarchar(max) NOT NULL CHECK(isjson(payload_json)=1),content_project_id uniqueidentifier NULL,retry_count int NOT NULL DEFAULT 0,acknowledged_at datetime2 NULL,failure_reason nvarchar(2000),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),updated_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE UNIQUE INDEX UX_re_single_open_handoff ON re_handoffs(candidate_id) WHERE status IN('PENDING','DISPATCHED','ACKNOWLEDGED');
CREATE TABLE re_blockers(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NULL REFERENCES re_cycles(id),candidate_id uniqueidentifier NULL REFERENCES re_candidates(id),severity varchar(20) NOT NULL,message nvarchar(2000) NOT NULL,recommendation nvarchar(2000),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),resolved_at datetime2 NULL);
CREATE TABLE re_jobs(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NULL REFERENCES re_cycles(id),job_type varchar(60) NOT NULL,status varchar(20) NOT NULL,attempt_count int NOT NULL DEFAULT 0,max_attempts int NOT NULL DEFAULT 5,next_attempt_at datetime2 NULL,lease_until datetime2 NULL,payload_json nvarchar(max),last_error nvarchar(2000),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),updated_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_outbox(id bigint IDENTITY PRIMARY KEY,event_type varchar(100) NOT NULL,aggregate_id uniqueidentifier NOT NULL,payload_json nvarchar(max) NOT NULL CHECK(isjson(payload_json)=1),status varchar(20) NOT NULL DEFAULT 'PENDING',attempts int NOT NULL DEFAULT 0,next_attempt_at datetime2 NULL,created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),processed_at datetime2 NULL);
CREATE TABLE re_audit_events(id bigint IDENTITY PRIMARY KEY,cycle_id uniqueidentifier NULL,candidate_id uniqueidentifier NULL,action varchar(100) NOT NULL,actor_type varchar(30) NOT NULL DEFAULT 'SYSTEM',actor_reference nvarchar(200),request_id varchar(100),correlation_id varchar(100),previous_value nvarchar(max),new_value nvarchar(max),reason nvarchar(1000),created_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_research_briefs(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NOT NULL REFERENCES re_cycles(id),objective nvarchar(max) NOT NULL,scope_json nvarchar(max) NOT NULL CHECK(isjson(scope_json)=1),completion_rules_json nvarchar(max) NOT NULL CHECK(isjson(completion_rules_json)=1),status varchar(20) NOT NULL DEFAULT 'DRAFT',created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),updated_at datetime2 NOT NULL DEFAULT sysutcdatetime(),row_version rowversion);
CREATE TABLE re_research_questions(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,brief_id uniqueidentifier NOT NULL REFERENCES re_research_briefs(id),parent_question_id uniqueidentifier NULL,question nvarchar(1000) NOT NULL,question_type varchar(30) NOT NULL,priority int NOT NULL DEFAULT 3,status varchar(20) NOT NULL DEFAULT 'OPEN',answered_at datetime2 NULL,created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),CONSTRAINT FK_re_question_parent FOREIGN KEY(parent_question_id) REFERENCES re_research_questions(id));
CREATE TABLE re_sources(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NOT NULL REFERENCES re_cycles(id),canonical_url nvarchar(2048),title nvarchar(1000) NOT NULL,source_type varchar(40) NOT NULL,publisher nvarchar(500),author nvarchar(500),published_at datetime2 NULL,retrieved_at datetime2 NOT NULL DEFAULT sysutcdatetime(),language_code varchar(20),country_code char(2),authority_score decimal(5,2),bias_notes nvarchar(2000),correction_status varchar(30),content_checksum char(64) NOT NULL,metadata_json nvarchar(max),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),CONSTRAINT UQ_re_source_snapshot UNIQUE(cycle_id,content_checksum));
CREATE TABLE re_source_snapshots(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,source_id uniqueidentifier NOT NULL REFERENCES re_sources(id),storage_reference nvarchar(1000) NOT NULL,mime_type varchar(150),byte_size bigint,extracted_text_checksum char(64),captured_at datetime2 NOT NULL DEFAULT sysutcdatetime(),is_immutable bit NOT NULL DEFAULT 1);
CREATE TABLE re_claims(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NOT NULL REFERENCES re_cycles(id),claim_text nvarchar(max) NOT NULL,claim_type varchar(40) NOT NULL,material bit NOT NULL DEFAULT 1,required_source_count int NOT NULL DEFAULT 2,status varchar(30) NOT NULL DEFAULT 'UNVERIFIED',confidence decimal(5,2),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),updated_at datetime2 NOT NULL DEFAULT sysutcdatetime(),row_version rowversion);
CREATE TABLE re_claim_evidence(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,claim_id uniqueidentifier NOT NULL REFERENCES re_claims(id),source_id uniqueidentifier NOT NULL REFERENCES re_sources(id),relationship varchar(20) NOT NULL CHECK(relationship IN('SUPPORTS','CONTRADICTS','CONTEXTUALISES')),locator nvarchar(1000),excerpt_hash char(64),independence_group nvarchar(200),relevance_score decimal(5,2),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),CONSTRAINT UQ_re_claim_source_locator UNIQUE(claim_id,source_id,locator));
CREATE TABLE re_contradictions(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,claim_id uniqueidentifier NOT NULL REFERENCES re_claims(id),description nvarchar(max) NOT NULL,severity varchar(20) NOT NULL,status varchar(20) NOT NULL DEFAULT 'OPEN',resolution nvarchar(max),resolved_at datetime2 NULL,created_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_citations(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,claim_id uniqueidentifier NOT NULL REFERENCES re_claims(id),source_id uniqueidentifier NOT NULL REFERENCES re_sources(id),citation_style varchar(40) NOT NULL,citation_text nvarchar(max) NOT NULL,locator nvarchar(1000),validated bit NOT NULL DEFAULT 0,created_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_rights_checks(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,source_id uniqueidentifier NOT NULL REFERENCES re_sources(id),rights_status varchar(30) NOT NULL,licence_name nvarchar(300),licence_url nvarchar(2048),permitted_uses_json nvarchar(max),evidence_reference nvarchar(1000),expires_at datetime2 NULL,checked_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE re_fact_checks(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,claim_id uniqueidentifier NOT NULL REFERENCES re_claims(id),rule_code varchar(100) NOT NULL,status varchar(20) NOT NULL,severity varchar(20) NOT NULL,explanation nvarchar(max),checked_at datetime2 NOT NULL DEFAULT sysutcdatetime(),CONSTRAINT UQ_re_fact_rule UNIQUE(claim_id,rule_code));
CREATE TABLE re_research_dossiers(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,cycle_id uniqueidentifier NOT NULL REFERENCES re_cycles(id),version_number int NOT NULL,checksum char(64) NOT NULL,status varchar(30) NOT NULL CHECK(status IN('BUILDING','BLOCKED','READY','HANDED_OFF','SUPERSEDED')),package_json nvarchar(max) NOT NULL CHECK(isjson(package_json)=1),generated_at datetime2 NOT NULL DEFAULT sysutcdatetime(),CONSTRAINT UQ_re_dossier_version UNIQUE(cycle_id,version_number),CONSTRAINT UQ_re_dossier_checksum UNIQUE(checksum));
CREATE TABLE re_dossier_handoffs(id uniqueidentifier NOT NULL DEFAULT newid() PRIMARY KEY,dossier_id uniqueidentifier NOT NULL REFERENCES re_research_dossiers(id),status varchar(30) NOT NULL CHECK(status IN('PENDING','DISPATCHED','ACKNOWLEDGED','FAILED','BLOCKED')),idempotency_key varchar(100) NOT NULL UNIQUE,checksum char(64) NOT NULL,payload_json nvarchar(max) NOT NULL CHECK(isjson(payload_json)=1),script_project_id uniqueidentifier NULL,retry_count int NOT NULL DEFAULT 0,acknowledged_at datetime2 NULL,failure_reason nvarchar(2000),created_at datetime2 NOT NULL DEFAULT sysutcdatetime(),updated_at datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE UNIQUE INDEX UX_re_single_open_dossier_handoff ON re_dossier_handoffs(dossier_id) WHERE status IN('PENDING','DISPATCHED','ACKNOWLEDGED');
CREATE INDEX IX_re_candidates_status_score ON re_candidates(status,gate_status,score DESC);CREATE INDEX IX_re_jobs_claim ON re_jobs(status,next_attempt_at);CREATE INDEX IX_re_outbox_claim ON re_outbox(status,next_attempt_at);CREATE INDEX IX_re_blockers_open ON re_blockers(severity,created_at DESC) WHERE resolved_at IS NULL;CREATE INDEX IX_re_claims_status ON re_claims(cycle_id,status,material);CREATE INDEX IX_re_claim_evidence_claim ON re_claim_evidence(claim_id,relationship);CREATE INDEX IX_re_sources_authority ON re_sources(cycle_id,source_type,authority_score DESC);
COMMIT;

END