export const scriptProject={id:'11111111-1111-1111-1111-111111111124',code:'CAC-2026-000124',title:'Hidden AI: What Your Morning Already Knew',scriptVersion:2,status:'IN_REVIEW'};
export const concepts=[
 {id:'c1',code:'CON-001',title:'Your Day Was Predicted Before Breakfast',angle:'Reveal invisible AI through one ordinary day.',hook:'Before breakfast, several AI systems had already influenced what appeared in front of you.',structure:['Cold open','Morning','Commute','Work','Limits','Takeaway'],score:92,retention:94,globalAppeal:88,visual:90,safety:96,status:'APPROVED',selectedAt:'2026-09-04T10:12:00Z'},
 {id:'c2',code:'CON-002',title:'The Algorithm That Decides Your Dinner',angle:'Food delivery ranking as behavioural architecture.',hook:'Two identical restaurants, two identical ratings — but one gets 6× more orders.',structure:['Hook','Ranking','Defaults','The test','Why it matters'],score:84,retention:82,globalAppeal:90,visual:80,safety:98,status:'SHORTLISTED'},
 {id:'c3',code:'CON-003',title:'AI That Reads Your Face in a Job Interview',angle:'Hiring tools trained on tone and microexpressions.',hook:'In 2026, 41% of first-round interviews are fully analysed by emotion models.',structure:['Hook','How scoring works','The candidates','What humans miss','Limits'],score:77,retention:79,globalAppeal:72,visual:85,safety:74,status:'REJECTED'},
 {id:'c4',code:'CON-004',title:'The Hidden Bias in "Neutral" AI Translation',angle:'When AI translates, it also rewrites intent.',hook:'The same sentence, translated 10 times, returns 10 different gendered narratives.',structure:['Hook','The experiment','Why it happens','Real-world costs','Reading the room'],score:71,retention:70,globalAppeal:83,visual:72,safety:92,status:'SHORTLISTED'}
];
export const scriptSections=[
 {id:'s1',order:1,type:'HOOK',title:'Cold Open — The Ordinary Morning',start:'00:00',end:'00:48',words:158,status:'APPROVED',content:'06:42. You reach for the phone. Before your thumb touches glass, the sleep-tracker has already sent a signal. Low deep-sleep window. Prediction: mood 6/10. Caffeine recommendation: strong. The phone lights up. Not an alarm — a curated "wake-up headline". Picked for you. From 14,000 candidates. In 230 ms.',purpose:'Create immediate personal relevance and curiosity.'},
 {id:'s2',order:2,type:'CHAPTER',title:'Breakfast — Five Models, One Kitchen',start:'00:48',end:'01:56',words:221,status:'REVIEW',content:'The smart speaker confirms the weather. It does more. It listens for hesitation. It adjusts the recipe pitch. The recipe app shows two options. One is highlighted. "96% match". The match is not your match — it is the match of 2.1 million users who look like you. Tap. The delivery app quietly re-ranks the supermarket list.',purpose:'Stack micro-interactions to show scale.'},
 {id:'s3',order:3,type:'CHAPTER',title:'Commute — The Silent Auction of Your Attention',start:'01:56',end:'03:30',words:312,status:'APPROVED',content:'You step outside. Navigation app opens. Shortest route. It is not the shortest route. It is the route with the highest predicted ad completion rate because a billboard owner paid the navigation bid. Podcast ad slot was sold last night in a 29-bidder auction against 5 other listeners matching your demographic profile. The host read the ad yesterday. You hear it today.',purpose:'Introduce the auction metaphor.'},
 {id:'s4',order:4,type:'CHAPTER',title:'Work — The AI That Writes Before You Do',start:'03:30',end:'05:40',words:490,status:'REVIEW',content:'At your desk, autocomplete drafts 63% of what eventually becomes the final email. In an adjacent team, a hiring AI shortlists 12 candidates from 4,300 applicants. At 09:17, a model flags a sales call transcript as "high churn risk, 78%". The model cannot tell you *why*. Only that people who sounded like this, 77% of the time, left within 90 days.',purpose:'Anchor workplace impact with verifiable evidence.'},
 {id:'s5',order:5,type:'CHAPTER',title:'What The Models Can Never Know',start:'05:40',end:'07:30',words:398,status:'DRAFT',content:'Now the hard part. The prediction does not see the friend\'s text that made you pause. It does not see the migraine. It does not see the rent letter slipped under the door. It sees averages — and averages, applied to a single human life, are the most reliable form of unfairness we have ever built at scale.',purpose:'Flip from capability to limits.'},
 {id:'s6',order:6,type:'TAKEAWAY',title:'How to Live With Systems That Guess',start:'07:30',end:'09:02',words:338,status:'DRAFT',content:'None of this means the systems are bad. It means the defaults were written for someone else. You get to rewrite them. Keep a human in the loop where the outcome matters. Audit where the data came from. Ask: what would I choose if the "96% match" label was not there? Then choose that.',purpose:'End with concrete, actionable guidance.'}
];
export const claimLinks=[
 {id:'l1',code:'CLAIM-R-003',claimText:'Sleep tracker data combined with demographic cohorts predicts mood within ±1.2 standard deviations.',verification:'VERIFIED',confidence:0.91,usage:'APPROVED',section:'Cold Open — The Ordinary Morning',source:'Research Sources, S1'},
 {id:'l2',code:'CLAIM-R-007',claimText:'41% of first-round interviews analysed by emotion models in 2026.',verification:'VERIFIED',confidence:0.88,usage:'APPROVED',section:'Work — The AI That Writes Before You Do',source:'Regulatory report, Q1 2026'},
 {id:'l3',code:'CLAIM-R-010',claimText:'Ad slot auctions for podcast listeners complete in < 200 ms with 20+ bidders.',verification:'VERIFIED',confidence:0.94,usage:'APPROVED',section:'Commute — The Silent Auction of Your Attention',source:'Publishers transparency report'},
 {id:'l4',code:'CLAIM-R-012',claimText:'Autocomplete writes 63% of final email output in benchmarked knowledge-work samples.',verification:'VERIFIED',confidence:0.90,usage:'APPROVED',section:'Work — The AI That Writes Before You Do',source:'SaaS vendor aggregate study'},
 {id:'l5',code:'CLAIM-R-015',claimText:'"96% match" recipe ranking was derived from 2.1M nearest-neighbour users, not personal history.',verification:'CONFLICTING',confidence:0.72,usage:'NEEDS_REVIEW',section:'Breakfast — Five Models, One Kitchen',source:'Vendor blog vs vendor data team'}
];
export const retentionChecks=[
 {id:'r1',section:1,startSecond:0,endSecond:48,score:90,status:'KEEP',type:'HOOK',note:'Personal-relevance hook lands within 8s.'},
 {id:'r2',section:2,startSecond:48,endSecond:116,score:86,status:'KEEP',type:'PATTERN',note:'Kitchen metaphor repeats the "one ordinary moment" frame.'},
 {id:'r3',section:3,startSecond:116,endSecond:210,score:82,status:'ACTION',type:'DURATION',note:'Auction explanation runs 14s long vs target; trim bid-count detail.'},
 {id:'r4',section:4,startSecond:210,endSecond:340,score:95,status:'KEEP',type:'CLIFF',note:'63% email stat is a strong mid-video cliffhanger number.'},
 {id:'r5',section:5,startSecond:340,endSecond:450,score:80,status:'ACTION',type:'REPEAT',note:'"does not see" triplet is powerful but sentence length drifts; tighten.'},
 {id:'r6',section:6,startSecond:450,endSecond:542,score:94,status:'KEEP',type:'CALLBACK',note:'Three concrete actions mirror the three-part cold open.'}
];
export const scriptVersions=[
 {id:'v2',number:2,status:'IN_REVIEW',createdAt:'2026-09-05T06:12:00Z',by:'Research Editor',words:1917,duration:'09:02',summary:'Added section 2 "Five Models, One Kitchen"; tightened intro; fixed factual citations.'},
 {id:'v1',number:1,status:'APPROVED',createdAt:'2026-09-03T14:08:00Z',by:'Pips Engine',words:1402,duration:'06:38',summary:'First approved concept-to-script draft from CON-001.'}
];
