export const sceneProject={id:'11111111-1111-1111-1111-111111111124',code:'CAC-2026-000124',title:'Hidden AI: What Your Morning Already Knew',scriptVersion:2,status:'IN_PROGRESS',characterStatus:'LOCKED',sceneStatus:'IN_REVIEW'};
export const characters=[
{id:'char-1',code:'CHR-001',name:'Amara',role:'Lead viewer proxy',age:'28–32',gender:'Female',nationality:'Nigerian',skin:'Deep brown',hair:'Neat shoulder-length natural twists',build:'Average height, slim-athletic build',wardrobe:'Smart-casual cream blouse, dark navy trousers, simple wristwatch',voice:'Warm neutral Nigerian English, intelligent and conversational',locked:true,prompt:'Photorealistic Nigerian woman, early 30s, deep brown skin, oval face, expressive dark eyes, neat shoulder-length natural twists, slim-athletic build, cream blouse, dark navy trousers, understated wristwatch, realistic skin texture, cinematic natural light',negative:'different hairstyle, different skin tone, changing age, different wardrobe, excessive makeup, cartoon, distorted hands'},
{id:'char-2',code:'CHR-002',name:'Tunde',role:'Colleague / supporting character',age:'32–36',gender:'Male',nationality:'Nigerian',skin:'Dark brown',hair:'Low clean haircut, trimmed beard',build:'Tall, medium build',wardrobe:'Muted blue Oxford shirt, charcoal chinos, black belt',voice:'Neutral Nigerian English, relaxed professional delivery',locked:true,prompt:'Photorealistic Nigerian man, mid 30s, dark brown skin, low clean haircut, short trimmed beard, tall medium build, muted blue Oxford shirt, charcoal chinos, professional contemporary Lagos appearance',negative:'different beard, bald head, suit jacket, changing shirt colour, cartoon, warped anatomy'}
];
export const wardrobes=[{character:'Amara',code:'WRD-A1',name:'Workday Base',description:'Cream blouse, navy trousers, watch, small stud earrings',locked:true},{character:'Amara',code:'WRD-A2',name:'Evening Home',description:'Soft grey T-shirt, black lounge trousers, same hair and earrings',locked:true},{character:'Tunde',code:'WRD-T1',name:'Office Base',description:'Muted blue Oxford shirt, charcoal chinos, black belt',locked:true}];
export const locations=[
{code:'LOC-001',name:'Amara Apartment',type:'Interior / Home',geo:'Lagos, Nigeria',visual:'Modern middle-class Lagos apartment; neutral walls, warm timber, compact open-plan kitchen, large window, realistic lived-in details',lighting:'Warm dawn/daylight through window; practical warm lamps at night',locked:true},
{code:'LOC-002',name:'Lagos Office',type:'Interior / Workplace',geo:'Lagos, Nigeria',visual:'Modern open-plan technology office; glass meeting rooms, dark desks, restrained blue accents, no visible corporate logos',lighting:'Soft daylight plus neutral overhead office lights',locked:true},
{code:'LOC-003',name:'City Commute',type:'Exterior / Urban',geo:'Lagos, Nigeria',visual:'Contemporary Lagos arterial road and pedestrian streets, real traffic density, clean modern city texture without identifiable plates',lighting:'Bright overcast morning for continuity',locked:true}
];
export const scenes=[
{n:1,code:'SC-001',chapter:'Cold Open',title:'Before Breakfast',start:'00:00',end:'00:18',duration:18,characters:['Amara'],location:'Amara Apartment',dialogue:'',voiceover:'Before you finished breakfast, several AI systems had already ranked, filtered or predicted parts of your day.',visual:'Amara reaches for her phone beside breakfast; subtle visual overlays imply ranking signals without fake UI text.',shot:'Medium close-up → insert',camera:'Slow push-in',lens:'50mm',lighting:'Warm morning window light',mood:'Curious, intimate',image:'Photorealistic cinematic morning in a modern Lagos apartment, Amara consistent with locked character reference, seated at breakfast table reaching for smartphone, warm dawn light, shallow depth of field, realistic skin and interior details, no readable phone text',negative:'different woman, different hairstyle, logos, fake readable UI text, distorted hands',animation:'Slow cinematic push toward Amara, natural hand reaches for phone, subtle rack focus to device, believable micro-movements, preserve face and wardrobe exactly',sfx:'Soft room tone, subtle phone pickup',music:'Minimal curiosity pulse begins',transition:'Hard cut on hand movement',status:'APPROVED'},
{n:2,code:'SC-002',chapter:'Cold Open',title:'Invisible Ranking',start:'00:18',end:'00:38',duration:20,characters:['Amara'],location:'Amara Apartment',dialogue:'',voiceover:'Not the kind that talks back to you. The quieter kind — deciding which video appears first and what gets surfaced.',visual:'Over-shoulder phone interaction; abstract cards reorder in space beside device, not literal branded interface.',shot:'OTS / macro insert',camera:'Controlled slider',lens:'85mm macro',lighting:'Morning continuity',mood:'Discovery',image:'Over shoulder cinematic shot of same Amara holding smartphone, abstract translucent recommendation cards floating subtly near device, no logos, no readable text, photorealistic hand anatomy, warm apartment light',negative:'brand logos, readable app UI, extra fingers, wardrobe change, cartoon graphics',animation:'Gentle slider right, thumb scrolls once, abstract cards reorder smoothly, keep UI symbolic and text-free',sfx:'Soft swipe, faint digital tick',music:'Curiosity pulse develops',transition:'Match cut to commute screen reflection',status:'APPROVED'},
{n:3,code:'SC-003',chapter:'The AI You Do Not Notice',title:'Morning Commute',start:'00:38',end:'01:05',duration:27,characters:['Amara'],location:'City Commute',dialogue:'',voiceover:'Recommendation systems estimate what may be relevant. Ranking systems decide what information gets surfaced first.',visual:'Amara walks toward transport pickup while checking a map; route choices visualized abstractly.',shot:'Wide tracking → medium',camera:'Gimbal follow',lens:'35mm',lighting:'Bright overcast morning',mood:'Energetic, explanatory',image:'Photorealistic Lagos morning commute, same Amara in cream blouse and navy trousers walking on contemporary urban street while viewing phone map, cinematic realistic traffic and pedestrians, no identifiable plates or logos',negative:'wardrobe change, different face, tourist city, fake street signs, warped cars',animation:'Gimbal follow behind then arc to profile, natural pedestrian motion, abstract route glow appears briefly without text',sfx:'City ambience, distant traffic',music:'Light rhythmic pulse',transition:'Whip-soft dissolve to office',status:'NEEDS_REVIEW'},
{n:4,code:'SC-004',chapter:'The AI You Do Not Notice',title:'Office Arrival',start:'01:05',end:'01:34',duration:29,characters:['Amara','Tunde'],location:'Lagos Office',dialogue:'Tunde: Morning. You beat the traffic today.\nAmara: Barely. My map changed the route twice.',voiceover:'',visual:'Amara enters office and exchanges natural dialogue with Tunde; screens remain generic.',shot:'Two-shot',camera:'Slow lateral move',lens:'40mm',lighting:'Neutral office daylight',mood:'Natural, relatable',image:'Photorealistic modern Lagos office, locked Amara and Tunde character references, natural two-shot conversation beside open-plan desks, realistic Nigerian professionals, clean glass partitions, no logos',negative:'character mismatch, wardrobe changes, duplicated people, fake corporate text',animation:'Slow lateral dolly, both characters speak naturally with accurate lip movement, subtle gestures and eye contact, no camera jump',sfx:'Low office ambience',music:'Music ducks under dialogue',transition:'Cut on Tunde gesture',status:'APPROVED'},
{n:5,code:'SC-005',chapter:'A Normal Morning',title:'Recommendation Loop',start:'01:34',end:'02:05',duration:31,characters:['Amara'],location:'Lagos Office',dialogue:'',voiceover:'The first videos, posts and stories you see were not arranged randomly. Platforms use many signals to rank what they think may be useful or engaging.',visual:'Desk close-up with multiple symbolic content tiles sorting around Amara, while she remains focused on work.',shot:'Medium / graphical composite',camera:'Locked with subtle push',lens:'50mm',lighting:'Office baseline',mood:'Explanatory',image:'Same Amara seated at modern office desk, photorealistic, subtle translucent generic content tiles sorting in depth around her, no readable text, no logos, cinematic restrained technology visualization',negative:'futuristic hologram overload, fake text, character mismatch, wardrobe change',animation:'Very subtle push-in; generic tiles reorganize in three layers, Amara types naturally, preserve locked identity',sfx:'Muted keyboard, soft digital sort',music:'Steady documentary pulse',transition:'Graphic tile wipes frame',status:'APPROVED'}
];
export const continuity=[
{type:'WARDROBE',scene:'SC-003',severity:'MEDIUM',status:'OPEN',description:'Commute image prompt must explicitly retain Amara Workday Base wardrobe from apartment scenes.',recommendation:'Bind WRD-A1 reference and locked character asset to image/video jobs.'},
{type:'LOCATION',scene:'SC-004',severity:'LOW',status:'RESOLVED',description:'Office lighting varied from visual baseline in draft storyboard.',recommendation:'Use neutral daylight + soft overhead baseline.'},
{type:'TIMELINE',scene:'SC-005',severity:'LOW',status:'OPEN',description:'SC-005 currently ends at 02:05 and should align exactly to approved Script Section 2 boundary.',recommendation:'Keep boundary fixed during scene expansion.'},
{type:'CHARACTER',scene:'ALL',severity:'HIGH',status:'RESOLVED',description:'Character identity must remain reference-locked across all image/video providers.',recommendation:'Provider adapter must pass reference image + master prompt + negative prompt.'}
];
export const storyboard=[{scene:'SC-001',frames:3,status:'APPROVED'},{scene:'SC-002',frames:3,status:'APPROVED'},{scene:'SC-003',frames:4,status:'NEEDS_REVIEW'},{scene:'SC-004',frames:3,status:'APPROVED'},{scene:'SC-005',frames:3,status:'APPROVED'}];
