export type OpportunityStatus='DISCOVERED'|'SHORTLISTED'|'SELECTED'|'REJECTED';
export type Opportunity={id:string;code:string;projectId:string;projectCode:string;title:string;topic:string;angle:string;hook:string;status:OpportunityStatus;score:number;trend:number;demand:number;competition:number;global:number;audience:number;revenue:number;evergreen:number;novelty:number;difficulty:number;viral:number;confidence:number;platform:string;format:string;duration:number;markets:string[];keywords:string[];rationale:string;evidence:string;risks:string[];updated:string};
export const opportunities:Opportunity[]=[
{id:'51000000-0000-0000-0000-000000000001',code:'OPP-2026-001',projectId:'11111111-1111-1111-1111-111111111124',projectCode:'CAC-2026-000124',title:'The AI Systems Making Decisions About You Before You Notice',topic:'Invisible everyday AI',angle:'Reveal the invisible recommendation, fraud, pricing and ranking systems people interact with every day.',hook:'Before you finish breakfast, AI may already have decided what you see, what you pay, and whether a transaction looks suspicious.',status:'SELECTED',score:92,trend:91,demand:86,competition:68,global:96,audience:94,revenue:89,evergreen:91,novelty:88,difficulty:54,viral:95,confidence:91,platform:'YouTube',format:'Long Form Documentary',duration:540,markets:['Global','United States','United Kingdom','Canada'],keywords:['everyday AI','recommendation algorithms','AI decisions','hidden algorithms'],rationale:'High global relevance, strong curiosity gap, multiple defensible examples and excellent fit with the approved content brief.',evidence:'Strong recurring interest around AI recommendation systems, automated fraud detection and algorithmic decision-making.',risks:['Avoid implying every automated system uses advanced AI','Verify examples with primary or authoritative sources'],updated:'5 min ago'},
{id:'51000000-0000-0000-0000-000000000002',code:'OPP-2026-002',projectId:'11111111-1111-1111-1111-111111111124',projectCode:'CAC-2026-000124',title:'Your Phone Knows What You Will Do Next',topic:'Predictive AI on smartphones',angle:'Show how mobile devices use signals, recommendations and predictive features to anticipate behaviour.',hook:'Your phone does not need to read your mind to predict what you might do next.',status:'SHORTLISTED',score:88,trend:87,demand:90,competition:72,global:93,audience:91,revenue:84,evergreen:86,novelty:83,difficulty:47,viral:90,confidence:86,platform:'YouTube',format:'Explainer',duration:480,markets:['Global','United States','United Kingdom'],keywords:['phone AI','predictive AI','smartphone algorithms'],rationale:'Strong audience familiarity and good visual storytelling potential.',evidence:'Consistent consumer interest in AI features, recommendations, privacy and personalisation.',risks:['Privacy claims require careful sourcing'],updated:'12 min ago'},
{id:'51000000-0000-0000-0000-000000000003',code:'OPP-2026-003',projectId:'11111111-1111-1111-1111-111111111124',projectCode:'CAC-2026-000124',title:'The Quiet AI Race Inside Supermarkets',topic:'Retail AI',angle:'Explore forecasting, pricing, inventory and loss-prevention systems in modern retail.',hook:'The smartest machine in a supermarket may not be a robot—it may be the software deciding what appears on the shelf tomorrow.',status:'DISCOVERED',score:82,trend:78,demand:72,competition:49,global:88,audience:78,revenue:86,evergreen:90,novelty:91,difficulty:63,viral:79,confidence:83,platform:'YouTube',format:'Mini Documentary',duration:600,markets:['Global','United States','United Kingdom','Canada'],keywords:['retail AI','supermarket technology','inventory AI'],rationale:'Less saturated topic with strong novelty and business relevance.',evidence:'Growing adoption of forecasting, computer vision and inventory optimisation in retail.',risks:['May require more complex visual sourcing'],updated:'28 min ago'},
{id:'51000000-0000-0000-0000-000000000004',code:'OPP-2026-004',projectId:'11111111-1111-1111-1111-111111111124',projectCode:'CAC-2026-000124',title:'AI Is Already Choosing What Millions of People See',topic:'Recommendation systems',angle:'Explain recommendation ranking across major digital platforms without centring on one brand.',hook:'Millions of people open an app thinking they are choosing what to watch. But another system chose what they would see first.',status:'DISCOVERED',score:90,trend:95,demand:94,competition:82,global:98,audience:96,revenue:91,evergreen:88,novelty:78,difficulty:51,viral:96,confidence:92,platform:'YouTube',format:'Long Form Explainer',duration:520,markets:['Global','United States','United Kingdom','Canada','Australia'],keywords:['recommendation algorithm','social media AI','content ranking'],rationale:'Extremely broad relevance and excellent retention potential, although competition is high.',evidence:'Recommendation systems remain one of the most visible and discussed applications of machine learning.',risks:['Highly competitive topic','Avoid oversimplifying ranking systems'],updated:'31 min ago'}
];
export const trendTopics=[
 {topic:'AI agents in everyday work',momentum:96,change:'+38%',market:'Global',competition:'High',fit:94},
 {topic:'Invisible recommendation systems',momentum:94,change:'+31%',market:'Global',competition:'High',fit:97},
 {topic:'Humanoid robots at work',momentum:92,change:'+27%',market:'US / Europe / Asia',competition:'High',fit:91},
 {topic:'AI privacy on smartphones',momentum:88,change:'+22%',market:'Global',competition:'Medium',fit:89},
 {topic:'Retail and supermarket AI',momentum:81,change:'+16%',market:'Global',competition:'Low',fit:84},
 {topic:'AI scams and synthetic identity',momentum:90,change:'+29%',market:'Global',competition:'Medium',fit:86}
];
export const sourceBrief={projectCode:'CAC-2026-000124',version:2,objective:'Educate & grow subscribers',audience:'Global English-speaking viewers · 16–45',creative:'Cinematic documentary',platforms:'YouTube + short-form derivatives',researchFocus:'Invisible AI systems already used in consumer life',status:'APPROVED'};
